"""All ORM models; importing this package registers every table on Base.metadata (used by Alembic)."""
from app.models.audit import ApiAccessLog, AuditLog, LoginAudit, SecurityEvent, WorkflowEvent
from app.models.base import Base, Environment
from app.models.documents import Document, DocumentCategory, DocumentVersion
from app.models.farmers import (
    BankAccountStatus,
    ConsentDefinition,
    Farmer,
    FarmerAgreement,
    FarmerBankAccount,
    FarmerConsent,
    FarmerContact,
    FarmerDocument,
    FarmerStatus,
)
from app.models.farms import (
    Farm,
    FarmBoundary,
    FarmCropHistory,
    FarmDocument,
    FarmEvidence,
    FarmLandHistory,
    FarmOverlapCheck,
    FarmOwnership,
    FarmPracticeHistory,
    FarmStatus,
)
from app.models.identity import (
    Organization,
    OrganizationStatus,
    OrganizationType,
    OrganizationUser,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    RoleScope,
    User,
    UserRole,
    UserSession,
    UserStatus,
)
from app.models.notifications import Notification

__all__ = [
    "ApiAccessLog",
    "AuditLog",
    "BankAccountStatus",
    "Base",
    "ConsentDefinition",
    "Document",
    "DocumentCategory",
    "DocumentVersion",
    "Environment",
    "Farm",
    "FarmBoundary",
    "FarmCropHistory",
    "FarmDocument",
    "FarmEvidence",
    "FarmLandHistory",
    "FarmOverlapCheck",
    "FarmOwnership",
    "FarmPracticeHistory",
    "FarmStatus",
    "Farmer",
    "FarmerAgreement",
    "FarmerBankAccount",
    "FarmerConsent",
    "FarmerContact",
    "FarmerDocument",
    "FarmerStatus",
    "LoginAudit",
    "Notification",
    "Organization",
    "OrganizationStatus",
    "OrganizationType",
    "OrganizationUser",
    "Permission",
    "RefreshToken",
    "Role",
    "RolePermission",
    "RoleScope",
    "SecurityEvent",
    "User",
    "UserRole",
    "UserSession",
    "UserStatus",
    "WorkflowEvent",
]
