"""phase2 decisions consent definitions

Decision D3: versioned consent definitions with required_for_activation; farmer consents reference the
definition version they were granted against, and an older grant is SUPERSEDED (never overwritten) when the
farmer consents to a newer version.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 21:57:10.050218
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_definitions',
    sa.Column('consent_type', sa.Unicode(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.Unicode(length=2000), nullable=True),
    sa.Column('text_version', sa.Unicode(length=40), nullable=True),
    sa.Column('required_for_activation', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('retired_at', mssql.DATETIME2(), nullable=True),
    sa.Column('retired_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'RETIRED')", name=op.f('ck_consent_definitions_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_consent_definitions_created_by_users')),
    sa.ForeignKeyConstraint(['retired_by'], ['users.id'], name=op.f('fk_consent_definitions_retired_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_definitions')),
    sa.UniqueConstraint('consent_type', 'version', name=op.f('uq_consent_definitions_consent_type_version'))
    )
    op.create_index('uq_consent_definitions_active', 'consent_definitions', ['consent_type'], unique=True, mssql_where=sa.text("status = 'ACTIVE'"))
    op.add_column('farmer_consents', sa.Column('consent_definition_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_farmer_consents_consent_definition_id'), 'farmer_consents', ['consent_definition_id'], unique=False)
    op.create_foreign_key(op.f('fk_farmer_consents_consent_definition_id_consent_definitions'), 'farmer_consents', 'consent_definitions', ['consent_definition_id'], ['id'])
    # ### end Alembic commands ###
    op.drop_constraint(op.f('ck_farmer_consents_status'), 'farmer_consents', type_='check')
    op.create_check_constraint(op.f('ck_farmer_consents_status'), 'farmer_consents', "status IN ('GRANTED', 'WITHDRAWN', 'SUPERSEDED')")
    # Baseline definition = the consent that Phase 2 required (DATA_PROCESSING); link existing grants to it.
    op.execute("""
INSERT INTO dbo.consent_definitions (id, consent_type, version, title, description, text_version, required_for_activation, status)
SELECT NEWID(), N'DATA_PROCESSING', 1, N'Personal data processing',
       N'Consent to collect and process the farmer''s personal data for platform operations.', NULL, 1, N'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM dbo.consent_definitions WHERE consent_type = N'DATA_PROCESSING')""")
    op.execute("""
UPDATE c SET c.consent_definition_id = d.id
FROM dbo.farmer_consents c JOIN dbo.consent_definitions d ON d.consent_type = c.consent_type AND d.version = 1
WHERE c.consent_definition_id IS NULL""")


def downgrade() -> None:
    op.execute("UPDATE dbo.farmer_consents SET status = N'WITHDRAWN' WHERE status = N'SUPERSEDED'")
    op.drop_constraint(op.f('ck_farmer_consents_status'), 'farmer_consents', type_='check')
    op.create_check_constraint(op.f('ck_farmer_consents_status'), 'farmer_consents', "status IN ('GRANTED', 'WITHDRAWN')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_farmer_consents_consent_definition_id_consent_definitions'), 'farmer_consents', type_='foreignkey')
    op.drop_index(op.f('ix_farmer_consents_consent_definition_id'), table_name='farmer_consents')
    op.drop_column('farmer_consents', 'consent_definition_id')
    op.drop_index('uq_consent_definitions_active', table_name='consent_definitions', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('consent_definitions')
    # ### end Alembic commands ###
