"""phase2 farmer farm

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 20:43:46.673956
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

import app.models.gis

# Business codes come from SQL Server sequences so concurrent registrations never collide.
SEQUENCES = ("seq_farmer_code", "seq_farm_code", "seq_agreement_number")

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('entity_type', sa.Unicode(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Unicode(length=30), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('sensitivity', sa.Unicode(length=12), nullable=False),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'OTHER')", name=op.f('ck_documents_category')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_documents_environment')),
    sa.CheckConstraint("sensitivity IN ('RESTRICTED', 'INTERNAL')", name=op.f('ck_documents_sensitivity')),
    sa.CheckConstraint("status IN ('ACTIVE', 'QUARANTINED', 'ARCHIVED')", name=op.f('ck_documents_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_entity', 'documents', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Unicode(length=60), nullable=False),
    sa.Column('channel', sa.Unicode(length=10), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('body', sa.Unicode(length=2000), nullable=True),
    sa.Column('entity_type', sa.Unicode(length=40), nullable=True),
    sa.Column('entity_id', sa.Unicode(length=64), nullable=True),
    sa.Column('link', sa.Unicode(length=300), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('sent_at', mssql.DATETIME2(), nullable=True),
    sa.Column('read_at', mssql.DATETIME2(), nullable=True),
    sa.Column('error', sa.Unicode(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("channel IN ('IN_APP', 'EMAIL', 'SMS', 'WHATSAPP')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED')", name=op.f('ck_notifications_status')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['recipient_user_id', 'read_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.Unicode(length=200), nullable=False),
    sa.Column('storage_key', sa.Unicode(length=400), nullable=False),
    sa.Column('mime_type', sa.Unicode(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('scan_status', sa.Unicode(length=15), nullable=False),
    sa.Column('scan_detail', sa.Unicode(length=400), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("scan_status IN ('NOT_SCANNED', 'CLEAN', 'INFECTED', 'ERROR')", name=op.f('ck_document_versions_scan_status')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name=op.f('uq_document_versions_document_id_version')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_versions_storage_key'))
    )
    op.create_index(op.f('ix_document_versions_checksum_sha256'), 'document_versions', ['checksum_sha256'], unique=False)
    op.create_table('farmers',
    sa.Column('farmer_code', sa.Unicode(length=30), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('group_organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.Unicode(length=200), nullable=False),
    sa.Column('gender', sa.Unicode(length=12), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_language', sa.Unicode(length=10), nullable=True),
    sa.Column('participation_type', sa.Unicode(length=15), nullable=False),
    sa.Column('address_line', sa.Unicode(length=300), nullable=True),
    sa.Column('village', sa.Unicode(length=120), nullable=True),
    sa.Column('sub_district', sa.Unicode(length=120), nullable=True),
    sa.Column('district', sa.Unicode(length=120), nullable=True),
    sa.Column('state', sa.Unicode(length=120), nullable=True),
    sa.Column('postal_code', sa.Unicode(length=20), nullable=True),
    sa.Column('country', sa.Unicode(length=2), nullable=False),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('kyc_id_type', sa.Unicode(length=20), nullable=True),
    sa.Column('kyc_id_last4', sa.Unicode(length=4), nullable=True),
    sa.Column('kyc_id_hash', sa.Unicode(length=64), nullable=True),
    sa.Column('kyc_document_id', sa.Uuid(), nullable=True),
    sa.Column('kyc_possible_duplicate', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('kyc_submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('kyc_submitted_by', sa.Uuid(), nullable=True),
    sa.Column('kyc_verified_at', mssql.DATETIME2(), nullable=True),
    sa.Column('kyc_verified_by', sa.Uuid(), nullable=True),
    sa.Column('kyc_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('registered_by', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_farmers_environment')),
    sa.CheckConstraint("gender IS NULL OR gender IN ('FEMALE', 'MALE', 'OTHER', 'UNDISCLOSED')", name=op.f('ck_farmers_gender')),
    sa.CheckConstraint("kyc_id_type IS NULL OR kyc_id_type IN ('NATIONAL_ID', 'VOTER_ID', 'TAX_ID', 'PASSPORT', 'DRIVING_LICENSE', 'OTHER')", name=op.f('ck_farmers_kyc_id_type')),
    sa.CheckConstraint("participation_type IN ('INDIVIDUAL', 'GROUP_MEMBER')", name=op.f('ck_farmers_participation_type')),
    sa.CheckConstraint("status IN ('DRAFT', 'REGISTERED', 'KYC_PENDING', 'KYC_VERIFIED', 'ACTIVE', 'SUSPENDED')", name=op.f('ck_farmers_status')),
    sa.ForeignKeyConstraint(['group_organization_id'], ['organizations.id'], name=op.f('fk_farmers_group_organization_id_organizations')),
    sa.ForeignKeyConstraint(['kyc_document_id'], ['documents.id'], name=op.f('fk_farmers_kyc_document_id_documents')),
    sa.ForeignKeyConstraint(['kyc_submitted_by'], ['users.id'], name=op.f('fk_farmers_kyc_submitted_by_users')),
    sa.ForeignKeyConstraint(['kyc_verified_by'], ['users.id'], name=op.f('fk_farmers_kyc_verified_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_farmers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], name=op.f('fk_farmers_registered_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farmers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmers')),
    sa.UniqueConstraint('farmer_code', name=op.f('uq_farmers_farmer_code'))
    )
    op.create_index(op.f('ix_farmers_full_name'), 'farmers', ['full_name'], unique=False)
    op.create_index('ix_farmers_kyc_id_hash', 'farmers', ['kyc_id_hash'], unique=False)
    op.create_index(op.f('ix_farmers_organization_id'), 'farmers', ['organization_id'], unique=False)
    op.create_index('uq_farmers_user_id', 'farmers', ['user_id'], unique=True, mssql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('farmer_agreements',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_number', sa.Unicode(length=60), nullable=False),
    sa.Column('agreement_type', sa.Unicode(length=40), nullable=False),
    sa.Column('template_version', sa.Unicode(length=40), nullable=False),
    sa.Column('counterparty_organization_id', sa.Uuid(), nullable=False),
    sa.Column('terms_summary', sa.UnicodeText(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('signed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('signature_method', sa.Unicode(length=20), nullable=True),
    sa.Column('signed_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'SIGNED', 'TERMINATED', 'EXPIRED', 'VOID')", name=op.f('ck_farmer_agreements_status')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name=op.f('ck_farmer_agreements_dates')),
    sa.ForeignKeyConstraint(['counterparty_organization_id'], ['organizations.id'], name=op.f('fk_farmer_agreements_counterparty_organization_id_organizations')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farmer_agreements_created_by_users')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_agreements_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['signed_document_id'], ['documents.id'], name=op.f('fk_farmer_agreements_signed_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_agreements')),
    sa.UniqueConstraint('agreement_number', name=op.f('uq_farmer_agreements_agreement_number'))
    )
    op.create_index(op.f('ix_farmer_agreements_farmer_id'), 'farmer_agreements', ['farmer_id'], unique=False)
    op.create_table('farmer_bank_accounts',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('account_holder_name', sa.Unicode(length=200), nullable=False),
    sa.Column('bank_name', sa.Unicode(length=200), nullable=False),
    sa.Column('branch_name', sa.Unicode(length=200), nullable=True),
    sa.Column('routing_code', sa.Unicode(length=30), nullable=False),
    sa.Column('account_number_enc', sa.Unicode(length=500), nullable=False),
    sa.Column('account_last4', sa.Unicode(length=4), nullable=False),
    sa.Column('account_number_hash', sa.Unicode(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Unicode(length=25), nullable=False),
    sa.Column('proof_document_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', mssql.DATETIME2(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', 'INACTIVE')", name=op.f('ck_farmer_bank_accounts_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farmer_bank_accounts_created_by_users')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_bank_accounts_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['proof_document_id'], ['documents.id'], name=op.f('fk_farmer_bank_accounts_proof_document_id_documents')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_farmer_bank_accounts_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_bank_accounts'))
    )
    op.create_index(op.f('ix_farmer_bank_accounts_account_number_hash'), 'farmer_bank_accounts', ['account_number_hash'], unique=False)
    op.create_index(op.f('ix_farmer_bank_accounts_farmer_id'), 'farmer_bank_accounts', ['farmer_id'], unique=False)
    op.create_table('farmer_consents',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Unicode(length=40), nullable=False),
    sa.Column('consent_text_version', sa.Unicode(length=40), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=True),
    sa.Column('capture_method', sa.Unicode(length=20), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('captured_at', mssql.DATETIME2(), nullable=False),
    sa.Column('captured_by', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', mssql.DATETIME2(), nullable=True),
    sa.Column('withdrawn_by', sa.Uuid(), nullable=True),
    sa.Column('withdrawal_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("capture_method IN ('PAPER_SIGNED', 'DIGITAL_SIGNATURE', 'VERBAL_RECORDED', 'OTP', 'ONLINE_CHECKBOX')", name=op.f('ck_farmer_consents_capture_method')),
    sa.CheckConstraint("status IN ('GRANTED', 'WITHDRAWN')", name=op.f('ck_farmer_consents_status')),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], name=op.f('fk_farmer_consents_captured_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_farmer_consents_document_id_documents')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_consents_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['withdrawn_by'], ['users.id'], name=op.f('fk_farmer_consents_withdrawn_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_consents'))
    )
    op.create_index(op.f('ix_farmer_consents_farmer_id'), 'farmer_consents', ['farmer_id'], unique=False)
    op.create_table('farmer_contacts',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('contact_type', sa.Unicode(length=20), nullable=False),
    sa.Column('value', sa.Unicode(length=320), nullable=False),
    sa.Column('label', sa.Unicode(length=60), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("contact_type IN ('PHONE', 'EMAIL', 'ALTERNATE_PHONE', 'ADDRESS')", name=op.f('ck_farmer_contacts_contact_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farmer_contacts_created_by_users')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_contacts_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_contacts'))
    )
    op.create_index(op.f('ix_farmer_contacts_farmer_id'), 'farmer_contacts', ['farmer_id'], unique=False)
    op.create_table('farmer_documents',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.Unicode(length=12), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("review_status IN ('UNREVIEWED', 'ACCEPTED', 'REJECTED')", name=op.f('ck_farmer_documents_review_status')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_farmer_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_documents_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_farmer_documents_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_documents')),
    sa.UniqueConstraint('document_id', name=op.f('uq_farmer_documents_document_id'))
    )
    op.create_index(op.f('ix_farmer_documents_farmer_id'), 'farmer_documents', ['farmer_id'], unique=False)
    op.create_table('farms',
    sa.Column('farm_code', sa.Unicode(length=30), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('village', sa.Unicode(length=120), nullable=True),
    sa.Column('sub_district', sa.Unicode(length=120), nullable=True),
    sa.Column('district', sa.Unicode(length=120), nullable=True),
    sa.Column('state', sa.Unicode(length=120), nullable=True),
    sa.Column('country', sa.Unicode(length=2), nullable=False),
    sa.Column('land_tenure', sa.Unicode(length=25), nullable=False),
    sa.Column('declared_area_hectares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('current_boundary_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', mssql.DATETIME2(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_farms_environment')),
    sa.CheckConstraint("land_tenure IN ('OWNED', 'LEASED', 'SHARECROPPED', 'COMMUNITY', 'GOVERNMENT_ALLOTTED', 'CUSTOMARY', 'OTHER')", name=op.f('ck_farms_land_tenure')),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'GIS_REVIEW', 'VERIFIED', 'REJECTED', 'INACTIVE')", name=op.f('ck_farms_status')),
    sa.CheckConstraint('area_hectares IS NULL OR area_hectares > 0', name=op.f('ck_farms_area_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farms_created_by_users')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farms_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_farms_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_farms_reviewed_by_users')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_farms_submitted_by_users')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_farms_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms')),
    sa.UniqueConstraint('farm_code', name=op.f('uq_farms_farm_code'))
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farms_organization_id'), 'farms', ['organization_id'], unique=False)
    op.create_table('farm_boundaries',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('boundary', app.models.gis.Geography(), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('perimeter_m', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('centroid_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('centroid_lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('vertex_count', sa.Integer(), nullable=False),
    sa.Column('validation_notes', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("source IN ('DRAWN', 'GEOJSON_UPLOAD', 'KML_UPLOAD', 'GPS_WALK', 'SURVEY', 'IMPORT')", name=op.f('ck_farm_boundaries_source')),
    sa.CheckConstraint("status IN ('CURRENT', 'SUPERSEDED')", name=op.f('ck_farm_boundaries_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farm_boundaries_created_by_users')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_boundaries_farm_id_farms')),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_farm_boundaries_source_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_boundaries')),
    sa.UniqueConstraint('farm_id', 'version', name=op.f('uq_farm_boundaries_farm_id_version'))
    )
    op.create_index('uq_farm_boundaries_current', 'farm_boundaries', ['farm_id'], unique=True, mssql_where=sa.text("status = 'CURRENT'"))
    op.create_table('farm_crop_history',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Unicode(length=40), nullable=True),
    sa.Column('crop_name', sa.Unicode(length=120), nullable=False),
    sa.Column('crop_variety', sa.Unicode(length=120), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('yield_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('yield_unit', sa.Unicode(length=20), nullable=True),
    sa.Column('irrigation', sa.Unicode(length=10), nullable=True),
    sa.Column('residue_management', sa.Unicode(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Unicode(length=15), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Unicode(length=15), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("irrigation IS NULL OR irrigation IN ('RAINFED', 'IRRIGATED', 'PARTIAL')", name=op.f('ck_farm_crop_history_irrigation')),
    sa.CheckConstraint("source IN ('FARMER_CLAIM', 'FIELD_AGENT', 'SATELLITE', 'DOCUMENT', 'INPUT_RECORD', 'OTHER')", name=op.f('ck_farm_crop_history_source')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED')", name=op.f('ck_farm_crop_history_verification_status')),
    sa.CheckConstraint('harvest_date IS NULL OR planting_date IS NULL OR harvest_date >= planting_date', name=op.f('ck_farm_crop_history_dates')),
    sa.CheckConstraint('year BETWEEN 1950 AND 2100', name=op.f('ck_farm_crop_history_year')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_crop_history_farm_id_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_crop_history')),
    sa.UniqueConstraint('record_id', 'version', name='uq_farm_crop_history_record_version')
    )
    op.create_index('ix_farm_crop_history_farm_current', 'farm_crop_history', ['farm_id', 'is_current'], unique=False)
    op.create_index('uq_farm_crop_history_current', 'farm_crop_history', ['record_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('farm_documents',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_farm_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_documents_farm_id_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_documents')),
    sa.UniqueConstraint('document_id', name=op.f('uq_farm_documents_document_id'))
    )
    op.create_index(op.f('ix_farm_documents_farm_id'), 'farm_documents', ['farm_id'], unique=False)
    op.create_table('farm_evidence',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('claim_type', sa.Unicode(length=15), nullable=False),
    sa.Column('claim_record_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Unicode(length=15), nullable=False),
    sa.Column('description', sa.Unicode(length=2000), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('external_reference', sa.Unicode(length=300), nullable=True),
    sa.Column('observed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('verification_status', sa.Unicode(length=15), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('captured_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("claim_type IN ('BOUNDARY', 'OWNERSHIP', 'LAND_USE', 'CROP', 'PRACTICE', 'OTHER')", name=op.f('ck_farm_evidence_claim_type')),
    sa.CheckConstraint("source_type IN ('FARMER_CLAIM', 'FIELD_AGENT', 'SATELLITE', 'DOCUMENT', 'INPUT_RECORD', 'OTHER')", name=op.f('ck_farm_evidence_source_type')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED')", name=op.f('ck_farm_evidence_verification_status')),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)', name=op.f('ck_farm_evidence_location')),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], name=op.f('fk_farm_evidence_captured_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_farm_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_evidence_farm_id_farms')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_farm_evidence_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_evidence'))
    )
    op.create_index(op.f('ix_farm_evidence_farm_id'), 'farm_evidence', ['farm_id'], unique=False)
    op.create_table('farm_land_history',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('land_use', sa.Unicode(length=20), nullable=False),
    sa.Column('land_use_detail', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Unicode(length=15), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Unicode(length=15), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("land_use IN ('CROPLAND', 'GRASSLAND', 'FOREST', 'FALLOW', 'WETLAND', 'SETTLEMENT', 'AGROFORESTRY', 'OTHER')", name=op.f('ck_farm_land_history_land_use')),
    sa.CheckConstraint("source IN ('FARMER_CLAIM', 'FIELD_AGENT', 'SATELLITE', 'DOCUMENT', 'INPUT_RECORD', 'OTHER')", name=op.f('ck_farm_land_history_source')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED')", name=op.f('ck_farm_land_history_verification_status')),
    sa.CheckConstraint('year BETWEEN 1950 AND 2100', name=op.f('ck_farm_land_history_year')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_land_history_farm_id_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_land_history')),
    sa.UniqueConstraint('record_id', 'version', name='uq_farm_land_history_record_version')
    )
    op.create_index('ix_farm_land_history_farm_current', 'farm_land_history', ['farm_id', 'is_current'], unique=False)
    op.create_index('uq_farm_land_history_current', 'farm_land_history', ['record_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('farm_ownership',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.Unicode(length=15), nullable=False),
    sa.Column('owner_farmer_id', sa.Uuid(), nullable=True),
    sa.Column('owner_name', sa.Unicode(length=200), nullable=False),
    sa.Column('operator_relationship', sa.Unicode(length=15), nullable=False),
    sa.Column('ownership_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('title_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('end_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('verification_status', sa.Unicode(length=15), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("operator_relationship IN ('OWNER', 'CO_OWNER', 'TENANT', 'LESSEE', 'SHARECROPPER', 'CUSTODIAN', 'OTHER')", name=op.f('ck_farm_ownership_operator_relationship')),
    sa.CheckConstraint("owner_type IN ('FARMER', 'INDIVIDUAL', 'ORGANIZATION', 'GOVERNMENT', 'COMMUNITY')", name=op.f('ck_farm_ownership_owner_type')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED')", name=op.f('ck_farm_ownership_verification_status')),
    sa.CheckConstraint('ownership_share_pct IS NULL OR (ownership_share_pct > 0 AND ownership_share_pct <= 100)', name=op.f('ck_farm_ownership_share')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name=op.f('ck_farm_ownership_dates')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_farm_ownership_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_ownership_farm_id_farms')),
    sa.ForeignKeyConstraint(['owner_farmer_id'], ['farmers.id'], name=op.f('fk_farm_ownership_owner_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_farm_ownership_recorded_by_users')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_farm_ownership_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_ownership'))
    )
    op.create_index(op.f('ix_farm_ownership_farm_id'), 'farm_ownership', ['farm_id'], unique=False)
    op.create_table('farm_practice_history',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Unicode(length=40), nullable=True),
    sa.Column('practice_phase', sa.Unicode(length=12), nullable=False),
    sa.Column('practice_category', sa.Unicode(length=20), nullable=False),
    sa.Column('practice_type', sa.Unicode(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.Unicode(length=30), nullable=True),
    sa.Column('frequency', sa.Unicode(length=60), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('implementation_status', sa.Unicode(length=15), nullable=True),
    sa.Column('expected_change', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('source', sa.Unicode(length=15), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.Unicode(length=15), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("implementation_status IS NULL OR implementation_status IN ('PLANNED', 'IN_PROGRESS', 'IMPLEMENTED', 'ABANDONED')", name=op.f('ck_farm_practice_history_implementation_status')),
    sa.CheckConstraint("practice_category IN ('TILLAGE', 'FERTILIZER', 'MANURE', 'IRRIGATION', 'RESIDUE', 'WATER_MANAGEMENT', 'GRAZING', 'COVER_CROP', 'CROP_ROTATION', 'AGROFORESTRY', 'OTHER')", name=op.f('ck_farm_practice_history_practice_category')),
    sa.CheckConstraint("practice_phase IN ('HISTORICAL', 'CURRENT', 'PROPOSED')", name=op.f('ck_farm_practice_history_practice_phase')),
    sa.CheckConstraint("source IN ('FARMER_CLAIM', 'FIELD_AGENT', 'SATELLITE', 'DOCUMENT', 'INPUT_RECORD', 'OTHER')", name=op.f('ck_farm_practice_history_source')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'NEEDS_REVIEW', 'REJECTED')", name=op.f('ck_farm_practice_history_verification_status')),
    sa.CheckConstraint('year BETWEEN 1950 AND 2100', name=op.f('ck_farm_practice_history_year')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_practice_history_farm_id_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_practice_history')),
    sa.UniqueConstraint('record_id', 'version', name='uq_farm_practice_history_record_version')
    )
    op.create_index('ix_farm_practice_history_farm_current', 'farm_practice_history', ['farm_id', 'is_current'], unique=False)
    op.create_index('uq_farm_practice_history_current', 'farm_practice_history', ['record_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('farm_overlap_checks',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('boundary_id', sa.Uuid(), nullable=False),
    sa.Column('other_farm_id', sa.Uuid(), nullable=False),
    sa.Column('other_boundary_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Unicode(length=10), nullable=False),
    sa.Column('overlap_area_m2', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overlap_pct_of_farm', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('overlap_pct_of_other', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('same_farmer', sa.Boolean(), nullable=False),
    sa.Column('same_organization', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('detected_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('resolution_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("relation IN ('PARTIAL', 'CONTAINS', 'WITHIN', 'EQUAL')", name=op.f('ck_farm_overlap_checks_relation')),
    sa.CheckConstraint("status IN ('OPEN', 'CLEARED', 'CONFIRMED_CONFLICT', 'OBSOLETE')", name=op.f('ck_farm_overlap_checks_status')),
    sa.ForeignKeyConstraint(['boundary_id'], ['farm_boundaries.id'], name=op.f('fk_farm_overlap_checks_boundary_id_farm_boundaries')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_overlap_checks_farm_id_farms')),
    sa.ForeignKeyConstraint(['other_boundary_id'], ['farm_boundaries.id'], name=op.f('fk_farm_overlap_checks_other_boundary_id_farm_boundaries')),
    sa.ForeignKeyConstraint(['other_farm_id'], ['farms.id'], name=op.f('fk_farm_overlap_checks_other_farm_id_farms')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_farm_overlap_checks_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_overlap_checks'))
    )
    op.create_index('ix_farm_overlap_checks_farm_status', 'farm_overlap_checks', ['farm_id', 'status'], unique=False)
    op.create_index(op.f('ix_farm_overlap_checks_other_farm_id'), 'farm_overlap_checks', ['other_farm_id'], unique=False)
    # ### end Alembic commands ###
    # farms <-> farm_boundaries reference each other; add this FK once both tables exist.
    op.create_foreign_key('fk_farms_current_boundary_id_farm_boundaries', 'farms', 'farm_boundaries',
                          ['current_boundary_id'], ['id'])
    # Spatial index for STIntersects / STDistance / point-in-polygon on farm boundaries.
    op.execute("CREATE SPATIAL INDEX six_farm_boundaries_boundary ON dbo.farm_boundaries(boundary) "
               "USING GEOGRAPHY_AUTO_GRID")
    for seq in SEQUENCES:
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    # Uploaded file versions are immutable evidence.
    op.execute("""
CREATE TRIGGER trg_document_versions_append_only ON dbo.document_versions
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'document_versions is append-only: updates and deletes are not permitted.', 1;
END""")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_document_versions_append_only")
    for seq in SEQUENCES:
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    op.execute("DROP INDEX IF EXISTS six_farm_boundaries_boundary ON dbo.farm_boundaries")
    op.drop_constraint('fk_farms_current_boundary_id_farm_boundaries', 'farms', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_overlap_checks_other_farm_id'), table_name='farm_overlap_checks')
    op.drop_index('ix_farm_overlap_checks_farm_status', table_name='farm_overlap_checks')
    op.drop_table('farm_overlap_checks')
    op.drop_index('uq_farm_practice_history_current', table_name='farm_practice_history', mssql_where=sa.text('is_current = 1'))
    op.drop_index('ix_farm_practice_history_farm_current', table_name='farm_practice_history')
    op.drop_table('farm_practice_history')
    op.drop_index(op.f('ix_farm_ownership_farm_id'), table_name='farm_ownership')
    op.drop_table('farm_ownership')
    op.drop_index('uq_farm_land_history_current', table_name='farm_land_history', mssql_where=sa.text('is_current = 1'))
    op.drop_index('ix_farm_land_history_farm_current', table_name='farm_land_history')
    op.drop_table('farm_land_history')
    op.drop_index(op.f('ix_farm_evidence_farm_id'), table_name='farm_evidence')
    op.drop_table('farm_evidence')
    op.drop_index(op.f('ix_farm_documents_farm_id'), table_name='farm_documents')
    op.drop_table('farm_documents')
    op.drop_index('uq_farm_crop_history_current', table_name='farm_crop_history', mssql_where=sa.text('is_current = 1'))
    op.drop_index('ix_farm_crop_history_farm_current', table_name='farm_crop_history')
    op.drop_table('farm_crop_history')
    op.drop_index('uq_farm_boundaries_current', table_name='farm_boundaries', mssql_where=sa.text("status = 'CURRENT'"))
    op.drop_table('farm_boundaries')
    op.drop_index(op.f('ix_farms_organization_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_farmer_documents_farmer_id'), table_name='farmer_documents')
    op.drop_table('farmer_documents')
    op.drop_index(op.f('ix_farmer_contacts_farmer_id'), table_name='farmer_contacts')
    op.drop_table('farmer_contacts')
    op.drop_index(op.f('ix_farmer_consents_farmer_id'), table_name='farmer_consents')
    op.drop_table('farmer_consents')
    op.drop_index(op.f('ix_farmer_bank_accounts_farmer_id'), table_name='farmer_bank_accounts')
    op.drop_index(op.f('ix_farmer_bank_accounts_account_number_hash'), table_name='farmer_bank_accounts')
    op.drop_table('farmer_bank_accounts')
    op.drop_index(op.f('ix_farmer_agreements_farmer_id'), table_name='farmer_agreements')
    op.drop_table('farmer_agreements')
    op.drop_index('uq_farmers_user_id', table_name='farmers', mssql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index(op.f('ix_farmers_organization_id'), table_name='farmers')
    op.drop_index('ix_farmers_kyc_id_hash', table_name='farmers')
    op.drop_index(op.f('ix_farmers_full_name'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_document_versions_checksum_sha256'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_entity', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
