"""Phase 7 — carbon calculation.

4 tables (calculation runs, frozen inputs, outputs, QA reviews), sequence CALC, filtered unique indexes (one open and one APPROVED
run per reporting period, one final output per run), append-only triggers on inputs and outputs, completed-QA immutability, and
the run immutability trigger (identity fixed; frozen columns only while DRAFT; outputs only while INPUTS_FROZEN; final states
never change; APPROVED → SUPERSEDED only; no deletes). No change to earlier tables (the project statuses already exist).

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-03 11:55:35.831397
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_runs',
    sa.Column('run_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('crediting_period_id', sa.Uuid(), nullable=True),
    sa.Column('mrv_dataset_id', sa.Uuid(), nullable=True),
    sa.Column('methodology_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('project_methodology_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_rules_version', sa.Integer(), nullable=False),
    sa.Column('monitoring_rules_version', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.Unicode(length=80), nullable=True),
    sa.Column('module_version', sa.Unicode(length=30), nullable=True),
    sa.Column('module_readiness', sa.Unicode(length=25), nullable=True),
    sa.Column('engine_version', sa.Unicode(length=30), nullable=False),
    sa.Column('parameters', sa.UnicodeText(), nullable=True),
    sa.Column('input_snapshot', sa.UnicodeText(), nullable=True),
    sa.Column('input_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('output_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('net_result', sa.Unicode(length=80), nullable=True),
    sa.Column('net_unit', sa.Unicode(length=40), nullable=True),
    sa.Column('blockers', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('recalculation_of_run_id', sa.Uuid(), nullable=True),
    sa.Column('recalculation_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('superseded_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('frozen_by', sa.Uuid(), nullable=True),
    sa.Column('frozen_at', mssql.DATETIME2(), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_calculation_runs_environment')),
    sa.CheckConstraint("module_readiness IS NULL OR module_readiness IN ('NOT_PRODUCTION_READY', 'PRODUCTION_READY')", name=op.f('ck_calculation_runs_module_readiness')),
    sa.CheckConstraint("status <> 'INPUTS_FROZEN' OR input_sha256 IS NOT NULL", name=op.f('ck_calculation_runs_frozen_hash')),
    sa.CheckConstraint("status IN ('DRAFT', 'INPUTS_FROZEN', 'CALCULATED', 'QA_REVIEW', 'APPROVED', 'SUPERSEDED', 'BLOCKED', 'CANCELLED', 'REJECTED')", name=op.f('ck_calculation_runs_status')),
    sa.CheckConstraint("status NOT IN ('CALCULATED', 'QA_REVIEW', 'APPROVED', 'SUPERSEDED') OR output_sha256 IS NOT NULL", name=op.f('ck_calculation_runs_output_hash')),
    sa.CheckConstraint('blockers IS NULL OR ISJSON(blockers) = 1', name=op.f('ck_calculation_runs_blockers_json')),
    sa.CheckConstraint('input_snapshot IS NULL OR ISJSON(input_snapshot) = 1', name=op.f('ck_calculation_runs_input_snapshot_json')),
    sa.CheckConstraint('parameters IS NULL OR ISJSON(parameters) = 1', name=op.f('ck_calculation_runs_parameters_json')),
    sa.CheckConstraint('recalculation_of_run_id IS NULL OR recalculation_reason IS NOT NULL', name=op.f('ck_calculation_runs_recalculation_reason')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_calculation_runs_approved_by_users')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_calculation_runs_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calculation_runs_created_by_users')),
    sa.ForeignKeyConstraint(['crediting_period_id'], ['project_crediting_periods.id'], name=op.f('fk_calculation_runs_crediting_period_id_project_crediting_periods')),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_calculation_runs_executed_by_users')),
    sa.ForeignKeyConstraint(['frozen_by'], ['users.id'], name=op.f('fk_calculation_runs_frozen_by_users')),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_calculation_runs_methodology_id_methodologies')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_calculation_runs_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_calculation_runs_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['mrv_dataset_id'], ['mrv_datasets.id'], name=op.f('fk_calculation_runs_mrv_dataset_id_mrv_datasets')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calculation_runs_project_id_projects')),
    sa.ForeignKeyConstraint(['project_methodology_id'], ['project_methodologies.id'], name=op.f('fk_calculation_runs_project_methodology_id_project_methodologies')),
    sa.ForeignKeyConstraint(['recalculation_of_run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_runs_recalculation_of_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_calculation_runs_submitted_by_users')),
    sa.ForeignKeyConstraint(['superseded_by_run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_runs_superseded_by_run_id_calculation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_runs')),
    sa.UniqueConstraint('run_code', name=op.f('uq_calculation_runs_run_code'))
    )
    op.create_index(op.f('ix_calculation_runs_monitoring_period_id'), 'calculation_runs', ['monitoring_period_id'], unique=False)
    op.create_index('ix_calculation_runs_project_status', 'calculation_runs', ['project_id', 'status'], unique=False)
    op.create_index('uq_calculation_runs_approved', 'calculation_runs', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status = 'APPROVED'"))
    op.create_index('uq_calculation_runs_open', 'calculation_runs', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status IN ('DRAFT', 'INPUTS_FROZEN', 'CALCULATED', 'QA_REVIEW')"))
    op.create_table('calculation_inputs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('variable_code', sa.Unicode(length=60), nullable=False),
    sa.Column('source_type', sa.Unicode(length=30), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('source_code', sa.Unicode(length=80), nullable=True),
    sa.Column('value', sa.Unicode(length=1000), nullable=False),
    sa.Column('value_kind', sa.Unicode(length=10), nullable=False),
    sa.Column('unit', sa.Unicode(length=40), nullable=True),
    sa.Column('level', sa.Unicode(length=20), nullable=False),
    sa.Column('stratum_id', sa.Uuid(), nullable=True),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('sampling_point_id', sa.Uuid(), nullable=True),
    sa.Column('field_collection_id', sa.Uuid(), nullable=True),
    sa.Column('sample_id', sa.Uuid(), nullable=True),
    sa.Column('root_sample_id', sa.Uuid(), nullable=True),
    sa.Column('monitoring_rule_id', sa.Uuid(), nullable=True),
    sa.Column('plan_measurement_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_source', sa.Unicode(length=20), nullable=True),
    sa.Column('source_reference', sa.Unicode(length=300), nullable=True),
    sa.Column('source_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("level IN ('PROJECT', 'STRATUM', 'FARM', 'SAMPLING_POINT')", name=op.f('ck_calculation_inputs_level')),
    sa.CheckConstraint("requirement_source IS NULL OR requirement_source IN ('METHODOLOGY', 'PROJECT_CONFIGURED', 'MODULE')", name=op.f('ck_calculation_inputs_requirement_source')),
    sa.CheckConstraint("source_type IN ('LAB_RESULT', 'MONITORING_RECORD', 'STRATUM_AREA', 'SAMPLING_DESIGN_PARAMETER', 'MODULE_CONSTANT')", name=op.f('ck_calculation_inputs_source_type')),
    sa.CheckConstraint("value_kind IN ('NUMBER', 'TEXT')", name=op.f('ck_calculation_inputs_value_kind')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_inputs_run_id_calculation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_inputs')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_calculation_inputs_run_id_seq'))
    )
    op.create_index(op.f('ix_calculation_inputs_run_id'), 'calculation_inputs', ['run_id'], unique=False)
    op.create_index('ix_calculation_inputs_source', 'calculation_inputs', ['source_id'], unique=False)
    op.create_table('calculation_outputs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step', sa.Unicode(length=15), nullable=False),
    sa.Column('output_code', sa.Unicode(length=80), nullable=False),
    sa.Column('calculation_rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.Unicode(length=40), nullable=False),
    sa.Column('equation_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('value', sa.Unicode(length=80), nullable=False),
    sa.Column('unit', sa.Unicode(length=40), nullable=False),
    sa.Column('level', sa.Unicode(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('input_refs', sa.UnicodeText(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("level IN ('PROJECT', 'STRATUM', 'FARM', 'SAMPLING_POINT')", name=op.f('ck_calculation_outputs_level')),
    sa.CheckConstraint("step IN ('BASELINE', 'PROJECT', 'EMISSIONS', 'REMOVALS', 'LEAKAGE', 'UNCERTAINTY', 'ADJUSTMENT', 'NET')", name=op.f('ck_calculation_outputs_step')),
    sa.CheckConstraint('ISJSON(input_refs) = 1', name=op.f('ck_calculation_outputs_input_refs_json')),
    sa.ForeignKeyConstraint(['calculation_rule_id'], ['methodology_calculation_rules.id'], name=op.f('fk_calculation_outputs_calculation_rule_id_methodology_calculation_rules')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_outputs_run_id_calculation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_outputs')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_calculation_outputs_run_id_seq'))
    )
    op.create_index(op.f('ix_calculation_outputs_run_id'), 'calculation_outputs', ['run_id'], unique=False)
    op.create_index('uq_calculation_outputs_final', 'calculation_outputs', ['run_id'], unique=True, mssql_where=sa.text('is_final = 1'))
    op.create_table('calculation_qa_reviews',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('started_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('checks', sa.UnicodeText(), nullable=True),
    sa.Column('result', sa.Unicode(length=10), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("result IS NULL OR result IN ('PASS', 'FAIL')", name=op.f('ck_calculation_qa_reviews_result')),
    sa.CheckConstraint('checks IS NULL OR ISJSON(checks) = 1', name=op.f('ck_calculation_qa_reviews_checks_json')),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_calculation_qa_reviews_completed_by_users')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_qa_reviews_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_calculation_qa_reviews_started_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_qa_reviews'))
    )
    op.create_index(op.f('ix_calculation_qa_reviews_run_id'), 'calculation_qa_reviews', ['run_id'], unique=False)
    # ### end Alembic commands ###

    # ---- hand-written: sequence and immutability triggers
    op.execute("CREATE SEQUENCE dbo.seq_calculation_run_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    for table in ("calculation_inputs", "calculation_outputs"):
        op.execute(f"""
CREATE TRIGGER trg_{table}_append_only ON dbo.{table}
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, '{table} is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_calculation_qa_reviews_completed_immutable ON dbo.calculation_qa_reviews
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF (EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)) OR EXISTS (SELECT 1 FROM deleted WHERE completed_at IS NOT NULL)
    BEGIN;
        THROW 51000, 'calculation_qa_reviews: reviews are never deleted and a completed review is immutable.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_calculation_runs_immutable ON dbo.calculation_runs
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'calculation_runs: calculation runs are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.run_code, i.project_id, i.monitoring_period_id, i.crediting_period_id, i.methodology_id, i.methodology_version_id, i.project_methodology_id, i.calculation_rules_version, i.monitoring_rules_version, i.engine_version, i.environment, i.created_by, i.created_at, i.recalculation_of_run_id, i.recalculation_reason, i.notes, i.parameters EXCEPT SELECT d.run_code, d.project_id, d.monitoring_period_id, d.crediting_period_id, d.methodology_id, d.methodology_version_id, d.project_methodology_id, d.calculation_rules_version, d.monitoring_rules_version, d.engine_version, d.environment, d.created_by, d.created_at, d.recalculation_of_run_id, d.recalculation_reason, d.notes, d.parameters)
           OR (d.status <> 'DRAFT' AND EXISTS (SELECT i.mrv_dataset_id, i.module_code, i.module_version, i.module_readiness, i.input_snapshot, i.input_sha256, i.frozen_by, i.frozen_at EXCEPT SELECT d.mrv_dataset_id, d.module_code, d.module_version, d.module_readiness, d.input_snapshot, d.input_sha256, d.frozen_by, d.frozen_at))
           OR (d.status <> 'INPUTS_FROZEN' AND EXISTS (SELECT i.output_sha256, i.net_result, i.net_unit, i.executed_by, i.executed_at EXCEPT SELECT d.output_sha256, d.net_result, d.net_unit, d.executed_by, d.executed_at))
           OR (d.status IN ('BLOCKED', 'CANCELLED', 'REJECTED', 'SUPERSEDED') AND EXISTS (
                SELECT i.status, i.superseded_by_run_id, i.superseded_at, i.submitted_by, i.submitted_at, i.approved_by, i.approved_at, i.status_reason, i.closed_by, i.closed_at, i.blockers
                EXCEPT SELECT d.status, d.superseded_by_run_id, d.superseded_at, d.submitted_by, d.submitted_at, d.approved_by, d.approved_at, d.status_reason, d.closed_by, d.closed_at, d.blockers))
           OR (d.status = 'APPROVED' AND (i.status NOT IN ('APPROVED', 'SUPERSEDED') OR EXISTS (SELECT i.submitted_by, i.submitted_at, i.approved_by, i.approved_at, i.status_reason, i.closed_by, i.closed_at, i.blockers EXCEPT SELECT d.submitted_by, d.submitted_at, d.approved_by, d.approved_at, d.status_reason, d.closed_by, d.closed_at, d.blockers))))
    BEGIN;
        THROW 51000, 'calculation_runs: a run is immutable after its lifecycle points (only APPROVED -> SUPERSEDED may follow approval).', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: calculation history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.calculation_runs)
BEGIN;
    THROW 51000, 'Downgrade refused: calculation runs exist.', 1;
END""")
    for trigger in ("trg_calculation_runs_immutable", "trg_calculation_qa_reviews_completed_immutable", "trg_calculation_outputs_append_only",
                    "trg_calculation_inputs_append_only"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_calculation_run_code")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_qa_reviews_run_id'), table_name='calculation_qa_reviews')
    op.drop_table('calculation_qa_reviews')
    op.drop_index('uq_calculation_outputs_final', table_name='calculation_outputs', mssql_where=sa.text('is_final = 1'))
    op.drop_index(op.f('ix_calculation_outputs_run_id'), table_name='calculation_outputs')
    op.drop_table('calculation_outputs')
    op.drop_index('ix_calculation_inputs_source', table_name='calculation_inputs')
    op.drop_index(op.f('ix_calculation_inputs_run_id'), table_name='calculation_inputs')
    op.drop_table('calculation_inputs')
    op.drop_index('uq_calculation_runs_open', table_name='calculation_runs', mssql_where=sa.text("status IN ('DRAFT', 'INPUTS_FROZEN', 'CALCULATED', 'QA_REVIEW')"))
    op.drop_index('uq_calculation_runs_approved', table_name='calculation_runs', mssql_where=sa.text("status = 'APPROVED'"))
    op.drop_index('ix_calculation_runs_project_status', table_name='calculation_runs')
    op.drop_index(op.f('ix_calculation_runs_monitoring_period_id'), table_name='calculation_runs')
    op.drop_table('calculation_runs')
    # ### end Alembic commands ###
