"""Phase 10 — marketplace: buyer profiles & KYC, listings, orders, payments, refunds (no fee, tax, commission, revenue or payout).

9 tables (buyer_profiles; buyer_kyc_reviews — append-only; marketplace_listings; listing_documents — append-only; orders; order_items;
payments; payment_events — append-only, unique per (provider, external event id); refunds), sequences LST / ORD / PAY / RFD, filtered
unique indexes (one ACTIVE / PAUSED listing per seller + batch + serial range; one open payment per order; one open / completed refund per
payment; one order item per 9B reservation / transfer; idempotency keys), the documents categories BUYER_KYC_DOCUMENT (restricted),
PAYMENT_EVIDENCE, REFUND_EVIDENCE, ORDER_CONFIRMATION, LISTING_DOCUMENT (removed on downgrade only when unused) and triggers: identities
fixed; a listing's commercial terms frozen once approved; order-item price and quantity immutable; final states frozen; nothing deleted.
No credit quantity or ownership is stored — order items reference the Phase 9B batch / serial range / reservation / transfer only.
No invoice table and no INV sequence: tax / invoice rules are not defined (decision D10 — deferred).

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-03 16:52:13.514391
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0015'
down_revision: str | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('legal_name', sa.Unicode(length=300), nullable=False),
    sa.Column('registration_number', sa.Unicode(length=100), nullable=True),
    sa.Column('country', sa.Unicode(length=2), nullable=True),
    sa.Column('contact_name', sa.Unicode(length=200), nullable=True),
    sa.Column('contact_email', sa.Unicode(length=320), nullable=True),
    sa.Column('identifier_type', sa.Unicode(length=40), nullable=True),
    sa.Column('identifier_last4', sa.Unicode(length=4), nullable=True),
    sa.Column('identifier_hash', sa.Unicode(length=64), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', mssql.DATETIME2(), nullable=True),
    sa.Column('return_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('suspension_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_buyer_profiles_environment')),
    sa.CheckConstraint("status IN ('DRAFT', 'KYC_SUBMITTED', 'KYC_VERIFIED', 'KYC_RETURNED', 'SUSPENDED')", name=op.f('ck_buyer_profiles_status')),
    sa.CheckConstraint('(identifier_type IS NULL AND identifier_last4 IS NULL AND identifier_hash IS NULL) OR (identifier_type IS NOT NULL AND identifier_last4 IS NOT NULL AND identifier_hash IS NOT NULL)', name=op.f('ck_buyer_profiles_identifier')),
    sa.CheckConstraint('verified_by IS NULL OR submitted_by IS NULL OR verified_by <> submitted_by', name=op.f('ck_buyer_profiles_kyc_sod')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_buyer_profiles_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_buyer_profiles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_buyer_profiles_submitted_by_users')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_buyer_profiles_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_profiles')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_buyer_profiles_organization_id'))
    )
    op.create_index('uq_buyer_profiles_request_key', 'buyer_profiles', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('orders',
    sa.Column('order_code', sa.Unicode(length=20), nullable=False),
    sa.Column('buyer_organization_id', sa.Uuid(), nullable=False),
    sa.Column('seller_organization_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transfer_kind', sa.Unicode(length=10), nullable=False),
    sa.Column('recipient_registry_account', sa.Unicode(length=120), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(), nullable=False),
    sa.Column('placed_by', sa.Uuid(), nullable=False),
    sa.Column('placed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('paid_at', mssql.DATETIME2(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('close_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('attention_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_orders_environment')),
    sa.CheckConstraint("status IN ('PLACED', 'PAID', 'TRANSFER_PENDING', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'ATTENTION_REQUIRED', 'REFUND_PENDING', 'REFUNDED')", name=op.f('ck_orders_status')),
    sa.CheckConstraint("transfer_kind <> 'REGISTRY' OR recipient_registry_account IS NOT NULL", name=op.f('ck_orders_registry_account')),
    sa.CheckConstraint("transfer_kind IN ('INTERNAL', 'REGISTRY')", name=op.f('ck_orders_transfer_kind')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_orders_currency_code')),
    sa.CheckConstraint('buyer_organization_id <> seller_organization_id', name=op.f('ck_orders_distinct_parties')),
    sa.CheckConstraint('subtotal > 0 AND total = subtotal', name=op.f('ck_orders_total')),
    sa.ForeignKeyConstraint(['buyer_organization_id'], ['organizations.id'], name=op.f('fk_orders_buyer_organization_id_organizations')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_orders_closed_by_users')),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], name=op.f('fk_orders_placed_by_users')),
    sa.ForeignKeyConstraint(['seller_organization_id'], ['organizations.id'], name=op.f('fk_orders_seller_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_code', name=op.f('uq_orders_order_code'))
    )
    op.create_index('ix_orders_parties', 'orders', ['buyer_organization_id', 'seller_organization_id', 'status'], unique=False)
    op.create_index('uq_orders_request_key', 'orders', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('buyer_kyc_reviews',
    sa.Column('buyer_profile_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Unicode(length=12), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('document_ids', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("action IN ('SUBMITTED', 'VERIFIED', 'RETURNED', 'SUSPENDED', 'REINSTATED')", name=op.f('ck_buyer_kyc_reviews_action')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_buyer_kyc_reviews_actor_id_users')),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], name=op.f('fk_buyer_kyc_reviews_buyer_profile_id_buyer_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_kyc_reviews'))
    )
    op.create_index(op.f('ix_buyer_kyc_reviews_buyer_profile_id'), 'buyer_kyc_reviews', ['buyer_profile_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_code', sa.Unicode(length=20), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payee_organization_id', sa.Uuid(), nullable=False),
    sa.Column('payer_organization_id', sa.Uuid(), nullable=False),
    sa.Column('adapter_code', sa.Unicode(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('status', sa.Unicode(length=25), nullable=False),
    sa.Column('external_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reject_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("adapter_code <> 'MANUAL' OR status IN ('PENDING_CONFIRMATION', 'CONFIRMED', 'REJECTED', 'UNMATCHED', 'REFUNDED')", name=op.f('ck_payments_manual_states')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_payments_environment')),
    sa.CheckConstraint("status <> 'CONFIRMED' OR confirmed_by IS NOT NULL", name=op.f('ck_payments_confirmed')),
    sa.CheckConstraint("status IN ('CREATED', 'PENDING', 'UNCONFIRMED', 'PENDING_CONFIRMATION', 'CONFIRMED', 'REJECTED', 'FAILED', 'UNMATCHED', 'REFUNDED')", name=op.f('ck_payments_status')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_payments_currency_code')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.CheckConstraint('confirmed_by IS NULL OR confirmed_by <> recorded_by', name=op.f('ck_payments_dual_control')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_payments_confirmed_by_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_payments_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.ForeignKeyConstraint(['payee_organization_id'], ['organizations.id'], name=op.f('fk_payments_payee_organization_id_organizations')),
    sa.ForeignKeyConstraint(['payer_organization_id'], ['organizations.id'], name=op.f('fk_payments_payer_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_payments_recorded_by_users')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('fk_payments_rejected_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('payment_code', name=op.f('uq_payments_payment_code'))
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('uq_payments_external', 'payments', ['adapter_code', 'external_reference'], unique=True, mssql_where=sa.text('external_reference IS NOT NULL'))
    op.create_index('uq_payments_open', 'payments', ['order_id'], unique=True, mssql_where=sa.text("status IN ('CREATED', 'PENDING', 'UNCONFIRMED', 'PENDING_CONFIRMATION', 'CONFIRMED')"))
    op.create_index('uq_payments_request_key', 'payments', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('payment_events',
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Unicode(length=20), nullable=False),
    sa.Column('external_event_id', sa.Unicode(length=120), nullable=False),
    sa.Column('external_payment_id', sa.Unicode(length=120), nullable=True),
    sa.Column('event_type', sa.Unicode(length=30), nullable=False),
    sa.Column('payload_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('outcome', sa.Unicode(length=10), nullable=False),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('received_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("outcome IN ('APPLIED', 'UNMATCHED', 'IGNORED')", name=op.f('ck_payment_events_outcome')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_index('uq_payment_events_external', 'payment_events', ['provider', 'external_event_id'], unique=True)
    op.create_table('refunds',
    sa.Column('refund_code', sa.Unicode(length=20), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('after_transfer', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('reason', sa.Unicode(length=2000), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('external_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('reject_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_refunds_environment')),
    sa.CheckConstraint("status <> 'COMPLETED' OR (approved_by IS NOT NULL AND external_reference IS NOT NULL)", name=op.f('ck_refunds_completed')),
    sa.CheckConstraint("status <> 'REJECTED' OR reject_reason IS NOT NULL", name=op.f('ck_refunds_reject_reason')),
    sa.CheckConstraint("status IN ('REQUESTED', 'APPROVED', 'COMPLETED', 'REJECTED')", name=op.f('ck_refunds_status')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_refunds_currency_code')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_amount_positive')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> requested_by', name=op.f('ck_refunds_dual_control')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_refunds_approved_by_users')),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_refunds_completed_by_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_refunds_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('fk_refunds_rejected_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_refunds_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('refund_code', name=op.f('uq_refunds_refund_code'))
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index('uq_refunds_open', 'refunds', ['payment_id'], unique=True, mssql_where=sa.text("status IN ('REQUESTED', 'APPROVED', 'COMPLETED')"))
    op.create_index('uq_refunds_request_key', 'refunds', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('marketplace_listings',
    sa.Column('listing_code', sa.Unicode(length=20), nullable=False),
    sa.Column('seller_organization_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('listed_quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=28, scale=0), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=28, scale=0), nullable=True),
    sa.Column('payment_window_hours', sa.Integer(), nullable=False),
    sa.Column('valid_until', mssql.DATETIME2(), nullable=True),
    sa.Column('co_benefits', sa.Unicode(length=2000), nullable=True),
    sa.Column('disclosure', sa.UnicodeText(), nullable=True),
    sa.Column('disclosure_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('close_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_marketplace_listings_environment')),
    sa.CheckConstraint("status IN ('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'PAUSED', 'CLOSED', 'EXPIRED', 'CANCELLED')", name=op.f('ck_marketplace_listings_status')),
    sa.CheckConstraint("status NOT IN ('ACTIVE', 'PAUSED', 'CLOSED', 'EXPIRED') OR (approved_by IS NOT NULL AND disclosure_sha256 IS NOT NULL)", name=op.f('ck_marketplace_listings_approved')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_marketplace_listings_currency_code')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> created_by', name=op.f('ck_marketplace_listings_approval_sod')),
    sa.CheckConstraint('disclosure IS NULL OR ISJSON(disclosure) = 1', name=op.f('ck_marketplace_listings_disclosure_json')),
    sa.CheckConstraint('listed_quantity > 0', name=op.f('ck_marketplace_listings_listed_quantity_positive')),
    sa.CheckConstraint('max_quantity IS NULL OR max_quantity >= COALESCE(min_quantity, 1)', name=op.f('ck_marketplace_listings_max_quantity')),
    sa.CheckConstraint('min_quantity IS NULL OR min_quantity > 0', name=op.f('ck_marketplace_listings_min_quantity_positive')),
    sa.CheckConstraint('payment_window_hours BETWEEN 1 AND 720', name=op.f('ck_marketplace_listings_payment_window')),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_marketplace_listings_unit_price_positive')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_marketplace_listings_approved_by_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_marketplace_listings_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_marketplace_listings_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_marketplace_listings_created_by_users')),
    sa.ForeignKeyConstraint(['seller_organization_id'], ['organizations.id'], name=op.f('fk_marketplace_listings_seller_organization_id_organizations')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_marketplace_listings_serial_range_id_credit_serial_ranges')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_marketplace_listings_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_listings')),
    sa.UniqueConstraint('listing_code', name=op.f('uq_marketplace_listings_listing_code'))
    )
    op.create_index(op.f('ix_marketplace_listings_batch_id'), 'marketplace_listings', ['batch_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_seller_organization_id'), 'marketplace_listings', ['seller_organization_id'], unique=False)
    op.create_index('uq_marketplace_listings_open', 'marketplace_listings', ['seller_organization_id', 'batch_id', 'serial_range_id'], unique=True, mssql_where=sa.text("status IN ('ACTIVE', 'PAUSED')"))
    op.create_index('uq_marketplace_listings_request_key', 'marketplace_listings', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('listing_documents',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_listing_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_listing_documents_listing_id_marketplace_listings')),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_listing_documents_published_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_documents')),
    sa.UniqueConstraint('document_id', name=op.f('uq_listing_documents_document_id'))
    )
    op.create_index(op.f('ix_listing_documents_listing_id'), 'listing_documents', ['listing_id'], unique=False)
    op.create_table('order_items',
    sa.Column('item_code', sa.Unicode(length=30), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('RESERVED', 'TRANSFER_PENDING', 'DELIVERED', 'FAILED', 'RELEASED', 'EXPIRED')", name=op.f('ck_order_items_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price > 0 AND line_total = unit_price * quantity', name=op.f('ck_order_items_line_total')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_order_items_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], name=op.f('fk_order_items_listing_id_marketplace_listings')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], name=op.f('fk_order_items_reservation_id_credit_reservations')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_order_items_serial_range_id_credit_serial_ranges')),
    sa.ForeignKeyConstraint(['transfer_id'], ['credit_transfers.id'], name=op.f('fk_order_items_transfer_id_credit_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('item_code', name=op.f('uq_order_items_item_code'))
    )
    op.create_index('ix_order_items_listing', 'order_items', ['listing_id', 'status'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index('uq_order_items_reservation', 'order_items', ['reservation_id'], unique=True, mssql_where=sa.text('reservation_id IS NOT NULL'))
    op.create_index('uq_order_items_transfer', 'order_items', ['transfer_id'], unique=True, mssql_where=sa.text('transfer_id IS NOT NULL'))
    # ### end Alembic commands ###
    # ---- hand-written: sequences, documents categories, immutability / append-only triggers
    for seq in ('seq_listing_code', 'seq_order_code', 'seq_payment_code', 'seq_refund_code'):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents',
                               "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE', 'BUYER_KYC_DOCUMENT', 'PAYMENT_EVIDENCE', 'REFUND_EVIDENCE', 'ORDER_CONFIRMATION', 'LISTING_DOCUMENT', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_buyer_kyc_reviews_append_only ON dbo.buyer_kyc_reviews
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'buyer_kyc_reviews is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_payment_events_append_only ON dbo.payment_events
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'payment_events is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_listing_documents_append_only ON dbo.listing_documents
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'listing_documents is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_buyer_profiles_guard ON dbo.buyer_profiles
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'buyer_profiles: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.organization_id, i.created_by, i.request_key, i.environment EXCEPT SELECT d.organization_id, d.created_by, d.request_key, d.environment))
    BEGIN;
        THROW 51000, 'buyer_profiles: the organization, creator and environment of a buyer profile never change.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_marketplace_listings_guard ON dbo.marketplace_listings
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'marketplace_listings: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.listing_code, i.seller_organization_id, i.batch_id, i.serial_range_id, i.created_by, i.request_key, i.environment
                      EXCEPT SELECT d.listing_code, d.seller_organization_id, d.batch_id, d.serial_range_id, d.created_by, d.request_key, d.environment)
           OR (d.approved_by IS NOT NULL AND EXISTS (SELECT i.title, i.listed_quantity, i.unit_price, i.currency, i.min_quantity, i.max_quantity, i.payment_window_hours, i.valid_until, i.co_benefits, i.disclosure, i.disclosure_sha256, i.approved_by, i.approved_at
                                                     EXCEPT SELECT d.title, d.listed_quantity, d.unit_price, d.currency, d.min_quantity, d.max_quantity, d.payment_window_hours, d.valid_until, d.co_benefits, d.disclosure, d.disclosure_sha256, d.approved_by, d.approved_at))
           OR (d.status IN ('CLOSED', 'EXPIRED', 'CANCELLED') AND EXISTS (SELECT i.status, i.closed_by, i.closed_at, i.close_reason, i.action_key
                                                                          EXCEPT SELECT d.status, d.closed_by, d.closed_at, d.close_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'marketplace_listings: identity fixed; price, quantity, terms and disclosure frozen once approved; CLOSED / EXPIRED / CANCELLED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_orders_guard ON dbo.orders
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'orders: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.order_code, i.buyer_organization_id, i.seller_organization_id, i.currency, i.subtotal, i.total, i.transfer_kind, i.recipient_registry_account, i.expires_at, i.placed_by, i.placed_at, i.request_key, i.environment EXCEPT SELECT d.order_code, d.buyer_organization_id, d.seller_organization_id, d.currency, d.subtotal, d.total, d.transfer_kind, d.recipient_registry_account, d.expires_at, d.placed_by, d.placed_at, d.request_key, d.environment)
           OR (d.status IN ('COMPLETED', 'CANCELLED', 'EXPIRED', 'REFUNDED') AND EXISTS (SELECT i.order_code, i.buyer_organization_id, i.seller_organization_id, i.currency, i.subtotal, i.total, i.transfer_kind, i.recipient_registry_account, i.expires_at, i.placed_by, i.placed_at, i.request_key, i.environment, i.status, i.paid_at, i.completed_at, i.closed_by, i.closed_at, i.close_reason, i.attention_reason, i.action_key EXCEPT SELECT d.order_code, d.buyer_organization_id, d.seller_organization_id, d.currency, d.subtotal, d.total, d.transfer_kind, d.recipient_registry_account, d.expires_at, d.placed_by, d.placed_at, d.request_key, d.environment, d.status, d.paid_at, d.completed_at, d.closed_by, d.closed_at, d.close_reason, d.attention_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'orders: parties, currency, amounts and deadline are fixed; COMPLETED / CANCELLED / EXPIRED / REFUNDED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_order_items_guard ON dbo.order_items
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'order_items: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.item_code, i.order_id, i.listing_id, i.batch_id, i.serial_range_id, i.quantity, i.unit_price, i.line_total EXCEPT SELECT d.item_code, d.order_id, d.listing_id, d.batch_id, d.serial_range_id, d.quantity, d.unit_price, d.line_total)
           OR (d.status IN ('DELIVERED', 'RELEASED', 'EXPIRED') AND EXISTS (SELECT i.item_code, i.order_id, i.listing_id, i.batch_id, i.serial_range_id, i.quantity, i.unit_price, i.line_total, i.status, i.reservation_id, i.transfer_id EXCEPT SELECT d.item_code, d.order_id, d.listing_id, d.batch_id, d.serial_range_id, d.quantity, d.unit_price, d.line_total, d.status, d.reservation_id, d.transfer_id)))
    BEGIN;
        THROW 51000, 'order_items: price and quantity are immutable; DELIVERED / RELEASED / EXPIRED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_payments_guard ON dbo.payments
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'payments: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.payment_code, i.order_id, i.payee_organization_id, i.payer_organization_id, i.adapter_code, i.amount, i.currency, i.recorded_by, i.request_key, i.environment EXCEPT SELECT d.payment_code, d.order_id, d.payee_organization_id, d.payer_organization_id, d.adapter_code, d.amount, d.currency, d.recorded_by, d.request_key, d.environment)
           OR (d.status IN ('REJECTED', 'FAILED', 'REFUNDED') AND EXISTS (SELECT i.payment_code, i.order_id, i.payee_organization_id, i.payer_organization_id, i.adapter_code, i.amount, i.currency, i.recorded_by, i.request_key, i.environment, i.status, i.external_reference, i.evidence_document_id, i.confirmed_by, i.confirmed_at, i.rejected_by, i.rejected_at, i.reject_reason, i.action_key EXCEPT SELECT d.payment_code, d.order_id, d.payee_organization_id, d.payer_organization_id, d.adapter_code, d.amount, d.currency, d.recorded_by, d.request_key, d.environment, d.status, d.external_reference, d.evidence_document_id, d.confirmed_by, d.confirmed_at, d.rejected_by, d.rejected_at, d.reject_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'payments: order, parties, adapter and amount are fixed; REJECTED / FAILED / REFUNDED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_refunds_guard ON dbo.refunds
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'refunds: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.refund_code, i.payment_id, i.order_id, i.amount, i.currency, i.after_transfer, i.reason, i.requested_by, i.request_key, i.environment EXCEPT SELECT d.refund_code, d.payment_id, d.order_id, d.amount, d.currency, d.after_transfer, d.reason, d.requested_by, d.request_key, d.environment)
           OR (d.status IN ('COMPLETED', 'REJECTED') AND EXISTS (SELECT i.refund_code, i.payment_id, i.order_id, i.amount, i.currency, i.after_transfer, i.reason, i.requested_by, i.request_key, i.environment, i.status, i.approved_by, i.approved_at, i.completed_by, i.completed_at, i.external_reference, i.evidence_document_id, i.rejected_by, i.reject_reason, i.action_key EXCEPT SELECT d.refund_code, d.payment_id, d.order_id, d.amount, d.currency, d.after_transfer, d.reason, d.requested_by, d.request_key, d.environment, d.status, d.approved_by, d.approved_at, d.completed_by, d.completed_at, d.external_reference, d.evidence_document_id, d.rejected_by, d.reject_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'refunds: payment and amount are fixed; COMPLETED / REJECTED are final.', 1;
    END;
END""")



def downgrade() -> None:
    # ---- hand-written: Phase 10 commercial history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.buyer_profiles) OR EXISTS (SELECT 1 FROM dbo.buyer_kyc_reviews) OR EXISTS (SELECT 1 FROM dbo.marketplace_listings)
   OR EXISTS (SELECT 1 FROM dbo.listing_documents) OR EXISTS (SELECT 1 FROM dbo.orders) OR EXISTS (SELECT 1 FROM dbo.order_items)
   OR EXISTS (SELECT 1 FROM dbo.payments) OR EXISTS (SELECT 1 FROM dbo.payment_events) OR EXISTS (SELECT 1 FROM dbo.refunds)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('BUYER_KYC_DOCUMENT', 'PAYMENT_EVIDENCE', 'REFUND_EVIDENCE', 'ORDER_CONFIRMATION', 'LISTING_DOCUMENT'))
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 10 buyer profiles, listings, orders, payments, payment events, refunds or marketplace documents exist.', 1;
END""")
    for trigger in ('trg_refunds_guard', 'trg_payments_guard', 'trg_order_items_guard', 'trg_orders_guard', 'trg_marketplace_listings_guard', 'trg_buyer_profiles_guard', 'trg_listing_documents_append_only', 'trg_payment_events_append_only', 'trg_buyer_kyc_reviews_append_only'):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE', 'OTHER')")
    for seq in ('seq_listing_code', 'seq_order_code', 'seq_payment_code', 'seq_refund_code'):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_order_items_transfer', table_name='order_items', mssql_where=sa.text('transfer_id IS NOT NULL'))
    op.drop_index('uq_order_items_reservation', table_name='order_items', mssql_where=sa.text('reservation_id IS NOT NULL'))
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index('ix_order_items_listing', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_listing_documents_listing_id'), table_name='listing_documents')
    op.drop_table('listing_documents')
    op.drop_index('uq_marketplace_listings_request_key', table_name='marketplace_listings', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_marketplace_listings_open', table_name='marketplace_listings', mssql_where=sa.text("status IN ('ACTIVE', 'PAUSED')"))
    op.drop_index(op.f('ix_marketplace_listings_seller_organization_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_batch_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index('uq_refunds_request_key', table_name='refunds', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_refunds_open', table_name='refunds', mssql_where=sa.text("status IN ('REQUESTED', 'APPROVED', 'COMPLETED')"))
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('uq_payment_events_external', table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('uq_payments_request_key', table_name='payments', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_payments_open', table_name='payments', mssql_where=sa.text("status IN ('CREATED', 'PENDING', 'UNCONFIRMED', 'PENDING_CONFIRMATION', 'CONFIRMED')"))
    op.drop_index('uq_payments_external', table_name='payments', mssql_where=sa.text('external_reference IS NOT NULL'))
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_buyer_kyc_reviews_buyer_profile_id'), table_name='buyer_kyc_reviews')
    op.drop_table('buyer_kyc_reviews')
    op.drop_index('uq_orders_request_key', table_name='orders', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('ix_orders_parties', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_buyer_profiles_request_key', table_name='buyer_profiles', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
