"""phase3 projects

Project domain (spec section 7.4) plus the standard/activity catalog (section 7.5, reference entries only):
projects, project farms (participation), participants, standard/activity selection history, crediting periods,
baseline metadata (versioned), carbon-rights references, documents, derived project boundaries (geography,
spatial index) and the append-only project status history.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 22:12:50.282848
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

import app.models.gis

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('category', sa.Unicode(length=60), nullable=True),
    sa.Column('description', sa.Unicode(length=2000), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_activities_environment')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_activities_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_activities_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('code', name=op.f('uq_activities_code'))
    )
    op.create_table('standards',
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('owner_name', sa.Unicode(length=200), nullable=True),
    sa.Column('program_type', sa.Unicode(length=15), nullable=False),
    sa.Column('description', sa.Unicode(length=2000), nullable=True),
    sa.Column('source_url', sa.Unicode(length=500), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_standards_environment')),
    sa.CheckConstraint("program_type IN ('VOLUNTARY', 'COMPLIANCE', 'OTHER')", name=op.f('ck_standards_program_type')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_standards_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_standards_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standards')),
    sa.UniqueConstraint('code', name=op.f('uq_standards_code'))
    )
    op.create_table('projects',
    sa.Column('project_code', sa.Unicode(length=30), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.Unicode(length=4000), nullable=True),
    sa.Column('project_type', sa.Unicode(length=40), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.Unicode(length=2), nullable=False),
    sa.Column('region', sa.Unicode(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Unicode(length=25), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('methodology_status', sa.Unicode(length=20), nullable=False),
    sa.Column('current_boundary_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('eligibility_reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('eligibility_reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_projects_environment')),
    sa.CheckConstraint("methodology_status IN ('NOT_SELECTED')", name=op.f('ck_projects_methodology_status')),
    sa.CheckConstraint("project_type IN ('AGRICULTURAL_LAND_MANAGEMENT', 'AGROFORESTRY', 'RICE_CULTIVATION', 'GRASSLAND_MANAGEMENT', 'OTHER')", name=op.f('ck_projects_project_type')),
    sa.CheckConstraint("status IN ('DRAFT', 'DATA_COLLECTION', 'ELIGIBILITY_REVIEW', 'STANDARD_SELECTED', 'ACTIVITY_SELECTED', 'METHODOLOGY_REVIEW', 'METHODOLOGY_CONFIRMED', 'MRV_PLANNED', 'MONITORING', 'CALCULATION_READY', 'CALCULATED', 'VALIDATION', 'VERIFICATION', 'VERIFIED', 'REGISTRY_SUBMISSION', 'REGISTERED', 'ISSUANCE_PENDING', 'ISSUED', 'ACTIVE', 'CLOSED')", name=op.f('ck_projects_status')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_projects_activity_id_activities')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.ForeignKeyConstraint(['eligibility_reviewed_by'], ['users.id'], name=op.f('fk_projects_eligibility_reviewed_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_projects_standard_id_standards')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_projects_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('project_code', name=op.f('uq_projects_project_code'))
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('standard_activities',
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_standard_activities_activity_id_activities')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_standard_activities_created_by_users')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_standard_activities_standard_id_standards')),
    sa.PrimaryKeyConstraint('standard_id', 'activity_id', name=op.f('pk_standard_activities'))
    )
    op.create_index(op.f('ix_standard_activities_activity_id'), 'standard_activities', ['activity_id'], unique=False)
    op.create_table('project_activities',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('selected_by', sa.Uuid(), nullable=True),
    sa.Column('selected_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('superseded_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_project_activities_activity_id_activities')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_activities_project_id_projects')),
    sa.ForeignKeyConstraint(['selected_by'], ['users.id'], name=op.f('fk_project_activities_selected_by_users')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_project_activities_standard_id_standards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_activities'))
    )
    op.create_index(op.f('ix_project_activities_project_id'), 'project_activities', ['project_id'], unique=False)
    op.create_index('uq_project_activities_current', 'project_activities', ['project_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('project_baselines',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('description', sa.Unicode(length=4000), nullable=True),
    sa.Column('data_sources', sa.Unicode(length=2000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_project_baselines_dates')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_baselines_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_baselines_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_baselines')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_project_baselines_project_id_version'))
    )
    op.create_index(op.f('ix_project_baselines_project_id'), 'project_baselines', ['project_id'], unique=False)
    op.create_index('uq_project_baselines_current', 'project_baselines', ['project_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('project_boundaries',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('boundary', app.models.gis.Geography(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('sum_farm_area_hectares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('internal_overlap_hectares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('farm_count', sa.Integer(), nullable=False),
    sa.Column('farm_boundary_ids', sa.UnicodeText(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('project_overlaps', sa.UnicodeText(), nullable=True),
    sa.Column('computed_by', sa.Uuid(), nullable=True),
    sa.Column('computed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_status', sa.Unicode(length=10), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("review_status IN ('PENDING', 'ACCEPTED', 'ISSUES')", name=op.f('ck_project_boundaries_review_status')),
    sa.CheckConstraint("status IN ('CURRENT', 'SUPERSEDED')", name=op.f('ck_project_boundaries_status')),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], name=op.f('fk_project_boundaries_computed_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_boundaries_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_project_boundaries_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_boundaries')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_project_boundaries_project_id_version'))
    )
    op.create_index('uq_project_boundaries_current', 'project_boundaries', ['project_id'], unique=True, mssql_where=sa.text("status = 'CURRENT'"))
    op.create_table('project_crediting_periods',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('replaces_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('status_changed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('status_changed_by', sa.Uuid(), nullable=True),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'SUPERSEDED', 'CANCELLED', 'CONFIRMED', 'ACTIVE', 'ENDED')", name=op.f('ck_project_crediting_periods_status')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_project_crediting_periods_dates')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_crediting_periods_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_crediting_periods_project_id_projects')),
    sa.ForeignKeyConstraint(['replaces_id'], ['project_crediting_periods.id'], name=op.f('fk_project_crediting_periods_replaces_id_project_crediting_periods')),
    sa.ForeignKeyConstraint(['status_changed_by'], ['users.id'], name=op.f('fk_project_crediting_periods_status_changed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_crediting_periods')),
    sa.UniqueConstraint('project_id', 'period_number', name=op.f('uq_project_crediting_periods_project_id_period_number'))
    )
    op.create_index(op.f('ix_project_crediting_periods_project_id'), 'project_crediting_periods', ['project_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('linked_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_project_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_documents_project_id_projects')),
    sa.PrimaryKeyConstraint('project_id', 'document_id', name=op.f('pk_project_documents'))
    )
    op.create_table('project_participants',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_role', sa.Unicode(length=40), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), nullable=True),
    sa.Column('removed_by', sa.Uuid(), nullable=True),
    sa.Column('removed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('removal_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("project_role IN ('PROJECT_MANAGER', 'MRV_MANAGER', 'METHODOLOGY_SPECIALIST', 'FIELD_SUPERVISOR', 'FIELD_AGENT', 'GIS_SPECIALIST', 'PLATFORM_GIS_SPECIALIST', 'QA_OFFICER', 'FINANCE_MANAGER', 'CALCULATION_ANALYST', 'REGISTRY_MANAGER', 'CREDIT_MANAGER', 'SUPPORT')", name=op.f('ck_project_participants_project_role')),
    sa.CheckConstraint("status IN ('ACTIVE', 'REMOVED')", name=op.f('ck_project_participants_status')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_project_participants_dates')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_project_participants_added_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_participants_project_id_projects')),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], name=op.f('fk_project_participants_removed_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_participants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_participants'))
    )
    op.create_index(op.f('ix_project_participants_project_id'), 'project_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_participants_user_id'), 'project_participants', ['user_id'], unique=False)
    op.create_index('uq_project_participants_active', 'project_participants', ['project_id', 'user_id', 'project_role'], unique=True, mssql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('project_standards',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('selected_by', sa.Uuid(), nullable=True),
    sa.Column('selected_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_standards_project_id_projects')),
    sa.ForeignKeyConstraint(['selected_by'], ['users.id'], name=op.f('fk_project_standards_selected_by_users')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_project_standards_standard_id_standards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_standards'))
    )
    op.create_index(op.f('ix_project_standards_project_id'), 'project_standards', ['project_id'], unique=False)
    op.create_index('uq_project_standards_current', 'project_standards', ['project_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('project_status_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Unicode(length=25), nullable=True),
    sa.Column('to_status', sa.Unicode(length=25), nullable=False),
    sa.Column('action', sa.Unicode(length=40), nullable=False),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_project_status_history_changed_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_status_history_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_status_history'))
    )
    op.create_index(op.f('ix_project_status_history_project_id'), 'project_status_history', ['project_id'], unique=False)
    op.create_table('project_farms',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('participation_start', sa.Date(), nullable=False),
    sa.Column('participation_end', sa.Date(), nullable=True),
    sa.Column('farm_boundary_id', sa.Uuid(), nullable=False),
    sa.Column('farm_area_hectares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('conflicts_acknowledged', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('conflict_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('conflicts_snapshot', sa.UnicodeText(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('added_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('removed_by', sa.Uuid(), nullable=True),
    sa.Column('removed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('removal_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REMOVED')", name=op.f('ck_project_farms_status')),
    sa.CheckConstraint('participation_end IS NULL OR participation_end >= participation_start', name=op.f('ck_project_farms_dates')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_project_farms_added_by_users')),
    sa.ForeignKeyConstraint(['farm_boundary_id'], ['farm_boundaries.id'], name=op.f('fk_project_farms_farm_boundary_id_farm_boundaries')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_project_farms_farm_id_farms')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_project_farms_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_farms_project_id_projects')),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], name=op.f('fk_project_farms_removed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_farms'))
    )
    op.create_index(op.f('ix_project_farms_farm_id'), 'project_farms', ['farm_id'], unique=False)
    op.create_index(op.f('ix_project_farms_farmer_id'), 'project_farms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_project_farms_project_id'), 'project_farms', ['project_id'], unique=False)
    op.create_index('uq_project_farms_active', 'project_farms', ['project_id', 'farm_id'], unique=True, mssql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('project_carbon_rights',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_farm_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('holder_type', sa.Unicode(length=15), nullable=False),
    sa.Column('holder_farmer_id', sa.Uuid(), nullable=True),
    sa.Column('holder_organization_id', sa.Uuid(), nullable=True),
    sa.Column('holder_name', sa.Unicode(length=200), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('agreement_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.Unicode(length=200), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('verification_status', sa.Unicode(length=12), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('end_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("holder_type IN ('FARMER', 'LANDOWNER', 'ORGANIZATION', 'FARMER_GROUP', 'OTHER')", name=op.f('ck_project_carbon_rights_holder_type')),
    sa.CheckConstraint("status IN ('ACTIVE', 'ENDED', 'VOID')", name=op.f('ck_project_carbon_rights_status')),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED', 'REJECTED')", name=op.f('ck_project_carbon_rights_verification_status')),
    sa.CheckConstraint('agreement_id IS NOT NULL OR document_id IS NOT NULL OR reference IS NOT NULL', name=op.f('ck_project_carbon_rights_has_reference')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_project_carbon_rights_dates')),
    sa.CheckConstraint('share_pct IS NULL OR (share_pct > 0 AND share_pct <= 100)', name=op.f('ck_project_carbon_rights_share')),
    sa.ForeignKeyConstraint(['agreement_id'], ['farmer_agreements.id'], name=op.f('fk_project_carbon_rights_agreement_id_farmer_agreements')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_carbon_rights_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_project_carbon_rights_document_id_documents')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_project_carbon_rights_farm_id_farms')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_project_carbon_rights_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['holder_farmer_id'], ['farmers.id'], name=op.f('fk_project_carbon_rights_holder_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['holder_organization_id'], ['organizations.id'], name=op.f('fk_project_carbon_rights_holder_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_farm_id'], ['project_farms.id'], name=op.f('fk_project_carbon_rights_project_farm_id_project_farms')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_carbon_rights_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_project_carbon_rights_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_carbon_rights'))
    )
    op.create_index(op.f('ix_project_carbon_rights_farm_id'), 'project_carbon_rights', ['farm_id'], unique=False)
    op.create_index(op.f('ix_project_carbon_rights_project_farm_id'), 'project_carbon_rights', ['project_farm_id'], unique=False)
    op.create_index(op.f('ix_project_carbon_rights_project_id'), 'project_carbon_rights', ['project_id'], unique=False)
    # ### end Alembic commands ###
    # projects <-> project_boundaries reference each other; add this FK once both tables exist.
    op.create_foreign_key('fk_projects_current_boundary_id_project_boundaries', 'projects', 'project_boundaries',
                          ['current_boundary_id'], ['id'])
    op.execute("CREATE SPATIAL INDEX six_project_boundaries_boundary ON dbo.project_boundaries(boundary) USING GEOGRAPHY_AUTO_GRID")
    op.execute("CREATE SEQUENCE dbo.seq_project_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_project_status_history_append_only ON dbo.project_status_history
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'project_status_history is append-only: updates and deletes are not permitted.', 1;
END""")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_project_status_history_append_only")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'OTHER')")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_project_code")
    op.execute("DROP INDEX IF EXISTS six_project_boundaries_boundary ON dbo.project_boundaries")
    op.drop_constraint('fk_projects_current_boundary_id_project_boundaries', 'projects', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_carbon_rights_project_id'), table_name='project_carbon_rights')
    op.drop_index(op.f('ix_project_carbon_rights_project_farm_id'), table_name='project_carbon_rights')
    op.drop_index(op.f('ix_project_carbon_rights_farm_id'), table_name='project_carbon_rights')
    op.drop_table('project_carbon_rights')
    op.drop_index('uq_project_farms_active', table_name='project_farms', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_project_farms_project_id'), table_name='project_farms')
    op.drop_index(op.f('ix_project_farms_farmer_id'), table_name='project_farms')
    op.drop_index(op.f('ix_project_farms_farm_id'), table_name='project_farms')
    op.drop_table('project_farms')
    op.drop_index(op.f('ix_project_status_history_project_id'), table_name='project_status_history')
    op.drop_table('project_status_history')
    op.drop_index('uq_project_standards_current', table_name='project_standards', mssql_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_project_standards_project_id'), table_name='project_standards')
    op.drop_table('project_standards')
    op.drop_index('uq_project_participants_active', table_name='project_participants', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_project_participants_user_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_project_id'), table_name='project_participants')
    op.drop_table('project_participants')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_project_crediting_periods_project_id'), table_name='project_crediting_periods')
    op.drop_table('project_crediting_periods')
    op.drop_index('uq_project_boundaries_current', table_name='project_boundaries', mssql_where=sa.text("status = 'CURRENT'"))
    op.drop_table('project_boundaries')
    op.drop_index('uq_project_baselines_current', table_name='project_baselines', mssql_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_project_baselines_project_id'), table_name='project_baselines')
    op.drop_table('project_baselines')
    op.drop_index('uq_project_activities_current', table_name='project_activities', mssql_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_project_activities_project_id'), table_name='project_activities')
    op.drop_table('project_activities')
    op.drop_index(op.f('ix_standard_activities_activity_id'), table_name='standard_activities')
    op.drop_table('standard_activities')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('standards')
    op.drop_table('activities')
    # ### end Alembic commands ###
