"""Phase 11 — revenue, project costs, revenue-share versions, farm allocations, settlement runs, farmer entitlements, payouts.

13 tables (revenue_records — append-only, one RECOGNITION per order item, one REVERSAL per recognition; revenue_share_versions;
farm_allocation_versions; farm_allocation_lines — append-only; project_costs; settlement_runs; settlement_revenue_items /
settlement_cost_items — one ACTIVE claim per record; farmer_entitlements — append-only; payouts — one open payout per run and farmer;
payout_transactions / payout_reconciliations — append-only; payout_adjustments — one recovery case per reversal), sequences RVN / RSH / FAL /
PCS / SET / PYT / ADJ, the documents categories COST_EVIDENCE, PAYOUT_EVIDENCE and RECONCILIATION_EVIDENCE (the last two restricted) and
triggers: identities fixed, approved configuration / calculated figures / paid execution frozen, final states frozen, nothing deleted.
Money is Numeric(19,4) with an ISO-4217 currency; the migration stores no farmer percentage, fee or tax value.

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-03 19:08:49.656140
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0016'
down_revision: str | None = '0015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_share_versions',
    sa.Column('version_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('farmer_share_pct', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('deduct_approved_costs', sa.Boolean(), nullable=False),
    sa.Column('rounding_mode', sa.Unicode(length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.Unicode(length=500), nullable=False),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('return_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_revenue_share_versions_environment')),
    sa.CheckConstraint("rounding_mode IN ('HALF_UP', 'HALF_EVEN', 'DOWN')", name=op.f('ck_revenue_share_versions_rounding_mode')),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'SUPERSEDED')", name=op.f('ck_revenue_share_versions_status')),
    sa.CheckConstraint("status NOT IN ('APPROVED', 'SUPERSEDED') OR approved_by IS NOT NULL", name=op.f('ck_revenue_share_versions_approved')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> created_by', name=op.f('ck_revenue_share_versions_approval_sod')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_revenue_share_versions_dates')),
    sa.CheckConstraint('farmer_share_pct > 0 AND farmer_share_pct <= 100', name=op.f('ck_revenue_share_versions_farmer_share')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_revenue_share_versions_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_revenue_share_versions_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_revenue_share_versions_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_revenue_share_versions_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_share_versions')),
    sa.UniqueConstraint('version_code', name=op.f('uq_revenue_share_versions_version_code'))
    )
    op.create_index(op.f('ix_revenue_share_versions_project_id'), 'revenue_share_versions', ['project_id'], unique=False)
    op.create_index('uq_revenue_share_versions_no', 'revenue_share_versions', ['project_id', 'version_no'], unique=True)
    op.create_index('uq_revenue_share_versions_request_key', 'revenue_share_versions', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('farm_allocation_versions',
    sa.Column('version_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('basis_reference', sa.Unicode(length=500), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('return_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_farm_allocation_versions_environment')),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'SUPERSEDED')", name=op.f('ck_farm_allocation_versions_status')),
    sa.CheckConstraint("status NOT IN ('APPROVED', 'SUPERSEDED') OR approved_by IS NOT NULL", name=op.f('ck_farm_allocation_versions_approved')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> created_by', name=op.f('ck_farm_allocation_versions_approval_sod')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_farm_allocation_versions_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_farm_allocation_versions_created_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_farm_allocation_versions_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_farm_allocation_versions_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_farm_allocation_versions_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_allocation_versions')),
    sa.UniqueConstraint('version_code', name=op.f('uq_farm_allocation_versions_version_code'))
    )
    op.create_index(op.f('ix_farm_allocation_versions_project_id'), 'farm_allocation_versions', ['project_id'], unique=False)
    op.create_index('uq_farm_allocation_versions_no', 'farm_allocation_versions', ['project_id', 'monitoring_period_id', 'version_no'], unique=True)
    op.create_index('uq_farm_allocation_versions_request_key', 'farm_allocation_versions', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('project_costs',
    sa.Column('cost_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Unicode(length=60), nullable=False),
    sa.Column('description', sa.Unicode(length=1000), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=False),
    sa.Column('external_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('corrects_cost_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reject_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_project_costs_environment')),
    sa.CheckConstraint("status <> 'REJECTED' OR reject_reason IS NOT NULL", name=op.f('ck_project_costs_reject_reason')),
    sa.CheckConstraint("status IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED')", name=op.f('ck_project_costs_status')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_project_costs_currency_code')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_project_costs_amount_nonzero')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> created_by', name=op.f('ck_project_costs_approval_sod')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_project_costs_approved_by_users')),
    sa.ForeignKeyConstraint(['corrects_cost_id'], ['project_costs.id'], name=op.f('fk_project_costs_corrects_cost_id_project_costs')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_costs_created_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_project_costs_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_costs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_costs')),
    sa.UniqueConstraint('cost_code', name=op.f('uq_project_costs_cost_code'))
    )
    op.create_index(op.f('ix_project_costs_project_id'), 'project_costs', ['project_id'], unique=False)
    op.create_index('uq_project_costs_request_key', 'project_costs', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('farm_allocation_lines',
    sa.Column('allocation_version_id', sa.Uuid(), nullable=False),
    sa.Column('project_farm_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('share_pct > 0 AND share_pct <= 100', name=op.f('ck_farm_allocation_lines_share')),
    sa.ForeignKeyConstraint(['allocation_version_id'], ['farm_allocation_versions.id'], name=op.f('fk_farm_allocation_lines_allocation_version_id_farm_allocation_versions')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_allocation_lines_farm_id_farms')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farm_allocation_lines_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['project_farm_id'], ['project_farms.id'], name=op.f('fk_farm_allocation_lines_project_farm_id_project_farms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_allocation_lines'))
    )
    op.create_index(op.f('ix_farm_allocation_lines_allocation_version_id'), 'farm_allocation_lines', ['allocation_version_id'], unique=False)
    op.create_index('uq_farm_allocation_lines_farm', 'farm_allocation_lines', ['allocation_version_id', 'project_farm_id'], unique=True)
    op.create_table('settlement_runs',
    sa.Column('run_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('revenue_share_version_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_version_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_version', sa.Unicode(length=20), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('deducted_costs', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('distributable', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('farmer_total', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('developer_residual', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('input_snapshot', sa.UnicodeText(), nullable=True),
    sa.Column('input_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('calculated_by', sa.Uuid(), nullable=True),
    sa.Column('calculated_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('close_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_settlement_runs_environment')),
    sa.CheckConstraint("status IN ('DRAFT', 'CALCULATED', 'PENDING_APPROVAL', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED')", name=op.f('ck_settlement_runs_status')),
    sa.CheckConstraint("status IN ('DRAFT', 'CANCELLED') OR input_sha256 IS NOT NULL", name=op.f('ck_settlement_runs_calculated')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_settlement_runs_currency_code')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> calculated_by', name=op.f('ck_settlement_runs_approval_sod')),
    sa.ForeignKeyConstraint(['allocation_version_id'], ['farm_allocation_versions.id'], name=op.f('fk_settlement_runs_allocation_version_id_farm_allocation_versions')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_settlement_runs_approved_by_users')),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], name=op.f('fk_settlement_runs_calculated_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_settlement_runs_created_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_settlement_runs_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_settlement_runs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_settlement_runs_project_id_projects')),
    sa.ForeignKeyConstraint(['revenue_share_version_id'], ['revenue_share_versions.id'], name=op.f('fk_settlement_runs_revenue_share_version_id_revenue_share_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_runs')),
    sa.UniqueConstraint('run_code', name=op.f('uq_settlement_runs_run_code'))
    )
    op.create_index(op.f('ix_settlement_runs_project_id'), 'settlement_runs', ['project_id'], unique=False)
    op.create_index('uq_settlement_runs_request_key', 'settlement_runs', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('farmer_entitlements',
    sa.Column('settlement_run_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_line_id', sa.Uuid(), nullable=False),
    sa.Column('project_farm_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_line_id'], ['farm_allocation_lines.id'], name=op.f('fk_farmer_entitlements_allocation_line_id_farm_allocation_lines')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farmer_entitlements_farm_id_farms')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_farmer_entitlements_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['project_farm_id'], ['project_farms.id'], name=op.f('fk_farmer_entitlements_project_farm_id_project_farms')),
    sa.ForeignKeyConstraint(['settlement_run_id'], ['settlement_runs.id'], name=op.f('fk_farmer_entitlements_settlement_run_id_settlement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_entitlements'))
    )
    op.create_index('ix_farmer_entitlements_farmer', 'farmer_entitlements', ['farmer_id', 'settlement_run_id'], unique=False)
    op.create_index(op.f('ix_farmer_entitlements_settlement_run_id'), 'farmer_entitlements', ['settlement_run_id'], unique=False)
    op.create_index('uq_farmer_entitlements_line', 'farmer_entitlements', ['settlement_run_id', 'allocation_line_id'], unique=True)
    op.create_table('payouts',
    sa.Column('payout_code', sa.Unicode(length=20), nullable=False),
    sa.Column('settlement_run_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('adapter_code', sa.Unicode(length=20), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=True),
    sa.Column('bank_last4', sa.Unicode(length=4), nullable=True),
    sa.Column('external_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('replaces_payout_id', sa.Uuid(), nullable=True),
    sa.Column('calculated_by', sa.Uuid(), nullable=False),
    sa.Column('calculated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('paid_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reconciled_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('action_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_payouts_environment')),
    sa.CheckConstraint("status IN ('CALCULATED', 'PENDING_APPROVAL', 'APPROVED', 'PAYMENT_PENDING', 'PAID', 'RECONCILED', 'REJECTED', 'CANCELLED', 'FAILED', 'UNCONFIRMED', 'ON_HOLD')", name=op.f('ck_payouts_status')),
    sa.CheckConstraint("status NOT IN ('APPROVED', 'PAYMENT_PENDING', 'PAID', 'RECONCILED', 'UNCONFIRMED') OR bank_account_id IS NOT NULL", name=op.f('ck_payouts_bank_account')),
    sa.CheckConstraint("status NOT IN ('PAID', 'RECONCILED') OR (external_reference IS NOT NULL AND executed_by IS NOT NULL)", name=op.f('ck_payouts_paid_evidence')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_payouts_currency_code')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payouts_amount_positive')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> calculated_by', name=op.f('ck_payouts_approval_sod')),
    sa.CheckConstraint('executed_by IS NULL OR approved_by IS NULL OR executed_by <> approved_by', name=op.f('ck_payouts_execution_sod')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_payouts_approved_by_users')),
    sa.ForeignKeyConstraint(['bank_account_id'], ['farmer_bank_accounts.id'], name=op.f('fk_payouts_bank_account_id_farmer_bank_accounts')),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], name=op.f('fk_payouts_calculated_by_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_payouts_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_payouts_executed_by_users')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_payouts_farmer_id_farmers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payouts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['replaces_payout_id'], ['payouts.id'], name=op.f('fk_payouts_replaces_payout_id_payouts')),
    sa.ForeignKeyConstraint(['settlement_run_id'], ['settlement_runs.id'], name=op.f('fk_payouts_settlement_run_id_settlement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts')),
    sa.UniqueConstraint('payout_code', name=op.f('uq_payouts_payout_code'))
    )
    op.create_index(op.f('ix_payouts_farmer_id'), 'payouts', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_payouts_settlement_run_id'), 'payouts', ['settlement_run_id'], unique=False)
    op.create_index('uq_payouts_external', 'payouts', ['adapter_code', 'external_reference'], unique=True, mssql_where=sa.text('external_reference IS NOT NULL'))
    op.create_index('uq_payouts_open', 'payouts', ['settlement_run_id', 'farmer_id'], unique=True, mssql_where=sa.text("status IN ('CALCULATED', 'PENDING_APPROVAL', 'APPROVED', 'ON_HOLD', 'PAYMENT_PENDING', 'UNCONFIRMED', 'PAID', 'RECONCILED')"))
    op.create_index('uq_payouts_request_key', 'payouts', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('settlement_cost_items',
    sa.Column('settlement_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_cost_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_cost_id'], ['project_costs.id'], name=op.f('fk_settlement_cost_items_project_cost_id_project_costs')),
    sa.ForeignKeyConstraint(['settlement_run_id'], ['settlement_runs.id'], name=op.f('fk_settlement_cost_items_settlement_run_id_settlement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_cost_items'))
    )
    op.create_index(op.f('ix_settlement_cost_items_settlement_run_id'), 'settlement_cost_items', ['settlement_run_id'], unique=False)
    op.create_index('uq_settlement_cost_items_active', 'settlement_cost_items', ['project_cost_id'], unique=True, mssql_where=sa.text('active = 1'))
    op.create_table('payout_reconciliations',
    sa.Column('payout_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.Unicode(length=10), nullable=False),
    sa.Column('statement_reference', sa.Unicode(length=120), nullable=False),
    sa.Column('statement_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('statement_currency', sa.Unicode(length=3), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('reconciled_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("result IN ('MATCHED', 'EXCEPTION')", name=op.f('ck_payout_reconciliations_result')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_payout_reconciliations_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_payout_reconciliations_payout_id_payouts')),
    sa.ForeignKeyConstraint(['reconciled_by'], ['users.id'], name=op.f('fk_payout_reconciliations_reconciled_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_reconciliations'))
    )
    op.create_index(op.f('ix_payout_reconciliations_payout_id'), 'payout_reconciliations', ['payout_id'], unique=False)
    op.create_table('payout_transactions',
    sa.Column('payout_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Unicode(length=20), nullable=False),
    sa.Column('adapter_code', sa.Unicode(length=20), nullable=False),
    sa.Column('external_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('INITIATED', 'PAID', 'FAILED', 'UNCONFIRMED', 'STATUS_QUERIED')", name=op.f('ck_payout_transactions_kind')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_payout_transactions_actor_id_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_payout_transactions_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_payout_transactions_payout_id_payouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_transactions'))
    )
    op.create_index(op.f('ix_payout_transactions_payout_id'), 'payout_transactions', ['payout_id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('revenue_code', sa.Unicode(length=20), nullable=False),
    sa.Column('kind', sa.Unicode(length=12), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('seller_organization_id', sa.Uuid(), nullable=False),
    sa.Column('reverses_revenue_id', sa.Uuid(), nullable=True),
    sa.Column('refund_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(kind = 'RECOGNITION' AND amount > 0 AND reverses_revenue_id IS NULL AND refund_id IS NULL) OR (kind = 'REVERSAL' AND amount < 0 AND reverses_revenue_id IS NOT NULL AND refund_id IS NOT NULL)", name=op.f('ck_revenue_records_kind_shape')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_revenue_records_environment')),
    sa.CheckConstraint("kind IN ('RECOGNITION', 'REVERSAL')", name=op.f('ck_revenue_records_kind')),
    sa.CheckConstraint('LEN(currency) = 3', name=op.f('ck_revenue_records_currency_code')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_revenue_records_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_revenue_records_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_revenue_records_order_id_orders')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_revenue_records_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_revenue_records_payment_id_payments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_revenue_records_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_revenue_records_recorded_by_users')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_revenue_records_refund_id_refunds')),
    sa.ForeignKeyConstraint(['reverses_revenue_id'], ['revenue_records.id'], name=op.f('fk_revenue_records_reverses_revenue_id_revenue_records')),
    sa.ForeignKeyConstraint(['seller_organization_id'], ['organizations.id'], name=op.f('fk_revenue_records_seller_organization_id_organizations')),
    sa.ForeignKeyConstraint(['transfer_id'], ['credit_transfers.id'], name=op.f('fk_revenue_records_transfer_id_credit_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_records')),
    sa.UniqueConstraint('revenue_code', name=op.f('uq_revenue_records_revenue_code'))
    )
    op.create_index(op.f('ix_revenue_records_order_id'), 'revenue_records', ['order_id'], unique=False)
    op.create_index('ix_revenue_records_scope', 'revenue_records', ['project_id', 'monitoring_period_id', 'currency'], unique=False)
    op.create_index('uq_revenue_records_recognition', 'revenue_records', ['order_item_id'], unique=True, mssql_where=sa.text("kind = 'RECOGNITION'"))
    op.create_index('uq_revenue_records_reversal', 'revenue_records', ['reverses_revenue_id'], unique=True, mssql_where=sa.text('reverses_revenue_id IS NOT NULL'))
    op.create_table('payout_adjustments',
    sa.Column('adjustment_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('reversal_revenue_id', sa.Uuid(), nullable=False),
    sa.Column('original_settlement_run_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.Unicode(length=3), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('resolution', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_payout_adjustments_environment')),
    sa.CheckConstraint("status <> 'CLOSED' OR (closed_by IS NOT NULL AND resolution IS NOT NULL)", name=op.f('ck_payout_adjustments_closed')),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name=op.f('ck_payout_adjustments_status')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_payout_adjustments_closed_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payout_adjustments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['original_settlement_run_id'], ['settlement_runs.id'], name=op.f('fk_payout_adjustments_original_settlement_run_id_settlement_runs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_payout_adjustments_project_id_projects')),
    sa.ForeignKeyConstraint(['reversal_revenue_id'], ['revenue_records.id'], name=op.f('fk_payout_adjustments_reversal_revenue_id_revenue_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_adjustments')),
    sa.UniqueConstraint('adjustment_code', name=op.f('uq_payout_adjustments_adjustment_code'))
    )
    op.create_index(op.f('ix_payout_adjustments_project_id'), 'payout_adjustments', ['project_id'], unique=False)
    op.create_index('uq_payout_adjustments_reversal', 'payout_adjustments', ['reversal_revenue_id'], unique=True)
    op.create_table('settlement_revenue_items',
    sa.Column('settlement_run_id', sa.Uuid(), nullable=False),
    sa.Column('revenue_record_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['revenue_record_id'], ['revenue_records.id'], name=op.f('fk_settlement_revenue_items_revenue_record_id_revenue_records')),
    sa.ForeignKeyConstraint(['settlement_run_id'], ['settlement_runs.id'], name=op.f('fk_settlement_revenue_items_settlement_run_id_settlement_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_revenue_items'))
    )
    op.create_index(op.f('ix_settlement_revenue_items_settlement_run_id'), 'settlement_revenue_items', ['settlement_run_id'], unique=False)
    op.create_index('uq_settlement_revenue_items_active', 'settlement_revenue_items', ['revenue_record_id'], unique=True, mssql_where=sa.text('active = 1'))
    # ### end Alembic commands ###
    # ---- hand-written: sequences, documents categories, append-only / immutability triggers
    for seq in ('seq_revenue_code', 'seq_revenue_share_code', 'seq_allocation_code', 'seq_cost_code', 'seq_settlement_code', 'seq_payout_code', 'seq_adjustment_code'):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents',
                               "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE', 'BUYER_KYC_DOCUMENT', 'PAYMENT_EVIDENCE', 'REFUND_EVIDENCE', 'ORDER_CONFIRMATION', 'LISTING_DOCUMENT', 'COST_EVIDENCE', 'PAYOUT_EVIDENCE', 'RECONCILIATION_EVIDENCE', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_revenue_records_append_only ON dbo.revenue_records
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'revenue_records is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_farmer_entitlements_append_only ON dbo.farmer_entitlements
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'farmer_entitlements is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_payout_transactions_append_only ON dbo.payout_transactions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'payout_transactions is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_payout_reconciliations_append_only ON dbo.payout_reconciliations
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'payout_reconciliations is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_farm_allocation_lines_append_only ON dbo.farm_allocation_lines
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'farm_allocation_lines is append-only: rows are never changed or deleted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_revenue_share_versions_guard ON dbo.revenue_share_versions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'revenue_share_versions: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE (d.status = 'APPROVED' AND i.status NOT IN ('APPROVED', 'SUPERSEDED'))
           OR EXISTS (SELECT i.version_code, i.project_id, i.version_no, i.created_by, i.created_at, i.request_key, i.environment EXCEPT SELECT d.version_code, d.project_id, d.version_no, d.created_by, d.created_at, d.request_key, d.environment)
           OR (d.status <> 'DRAFT' AND EXISTS (SELECT i.farmer_share_pct, i.deduct_approved_costs, i.rounding_mode, i.effective_from, i.effective_to, i.source_reference, i.notes EXCEPT SELECT d.farmer_share_pct, d.deduct_approved_costs, d.rounding_mode, d.effective_from, d.effective_to, d.source_reference, d.notes))
           OR (d.status = 'APPROVED' AND EXISTS (SELECT i.farmer_share_pct, i.deduct_approved_costs, i.rounding_mode, i.effective_from, i.effective_to, i.source_reference, i.notes, i.submitted_by, i.approved_by, i.approved_at, i.return_reason EXCEPT SELECT d.farmer_share_pct, d.deduct_approved_costs, d.rounding_mode, d.effective_from, d.effective_to, d.source_reference, d.notes, d.submitted_by, d.approved_by, d.approved_at, d.return_reason))
           OR (d.status = 'SUPERSEDED' AND EXISTS (SELECT i.farmer_share_pct, i.deduct_approved_costs, i.rounding_mode, i.effective_from, i.effective_to, i.source_reference, i.notes, i.submitted_by, i.approved_by, i.approved_at, i.return_reason, i.status, i.action_key EXCEPT SELECT d.farmer_share_pct, d.deduct_approved_costs, d.rounding_mode, d.effective_from, d.effective_to, d.source_reference, d.notes, d.submitted_by, d.approved_by, d.approved_at, d.return_reason, d.status, d.action_key)))
    BEGIN;
        THROW 51000, 'revenue_share_versions: identity fixed; values frozen once submitted; APPROVED versions only become SUPERSEDED; SUPERSEDED is final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_farm_allocation_versions_guard ON dbo.farm_allocation_versions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'farm_allocation_versions: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE (d.status = 'APPROVED' AND i.status NOT IN ('APPROVED', 'SUPERSEDED'))
           OR EXISTS (SELECT i.version_code, i.project_id, i.monitoring_period_id, i.version_no, i.created_by, i.created_at, i.request_key, i.environment EXCEPT SELECT d.version_code, d.project_id, d.monitoring_period_id, d.version_no, d.created_by, d.created_at, d.request_key, d.environment)
           OR (d.status <> 'DRAFT' AND EXISTS (SELECT i.basis_reference EXCEPT SELECT d.basis_reference))
           OR (d.status = 'APPROVED' AND EXISTS (SELECT i.basis_reference, i.submitted_by, i.approved_by, i.approved_at, i.return_reason EXCEPT SELECT d.basis_reference, d.submitted_by, d.approved_by, d.approved_at, d.return_reason))
           OR (d.status = 'SUPERSEDED' AND EXISTS (SELECT i.basis_reference, i.submitted_by, i.approved_by, i.approved_at, i.return_reason, i.status, i.action_key EXCEPT SELECT d.basis_reference, d.submitted_by, d.approved_by, d.approved_at, d.return_reason, d.status, d.action_key)))
    BEGIN;
        THROW 51000, 'farm_allocation_versions: identity fixed; values frozen once submitted; APPROVED versions only become SUPERSEDED; SUPERSEDED is final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_project_costs_guard ON dbo.project_costs
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'project_costs: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.cost_code, i.project_id, i.monitoring_period_id, i.category, i.description, i.amount, i.currency, i.incurred_on, i.external_reference, i.corrects_cost_id, i.created_by, i.created_at, i.request_key, i.environment EXCEPT SELECT d.cost_code, d.project_id, d.monitoring_period_id, d.category, d.description, d.amount, d.currency, d.incurred_on, d.external_reference, d.corrects_cost_id, d.created_by, d.created_at, d.request_key, d.environment)
           OR (d.status IN ('APPROVED', 'REJECTED') AND EXISTS (SELECT i.cost_code, i.project_id, i.monitoring_period_id, i.category, i.description, i.amount, i.currency, i.incurred_on, i.external_reference, i.corrects_cost_id, i.created_by, i.created_at, i.request_key, i.environment, i.status, i.approved_by, i.approved_at, i.reject_reason, i.action_key EXCEPT SELECT d.cost_code, d.project_id, d.monitoring_period_id, d.category, d.description, d.amount, d.currency, d.incurred_on, d.external_reference, d.corrects_cost_id, d.created_by, d.created_at, d.request_key, d.environment, d.status, d.approved_by, d.approved_at, d.reject_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'project_costs: category and amount are fixed; APPROVED / REJECTED are final (corrections are new negative costs).', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_settlement_runs_guard ON dbo.settlement_runs
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'settlement_runs: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE (d.status = 'APPROVED' AND i.status NOT IN ('APPROVED', 'COMPLETED'))
           OR EXISTS (SELECT i.run_code, i.project_id, i.organization_id, i.monitoring_period_id, i.currency, i.revenue_share_version_id, i.allocation_version_id, i.created_by, i.created_at, i.request_key, i.environment EXCEPT SELECT d.run_code, d.project_id, d.organization_id, d.monitoring_period_id, d.currency, d.revenue_share_version_id, d.allocation_version_id, d.created_by, d.created_at, d.request_key, d.environment)
           OR (d.calculated_at IS NOT NULL AND EXISTS (SELECT i.calculation_version, i.gross_revenue, i.deducted_costs, i.distributable, i.farmer_total, i.developer_residual, i.input_snapshot, i.input_sha256, i.calculated_by, i.calculated_at EXCEPT SELECT d.calculation_version, d.gross_revenue, d.deducted_costs, d.distributable, d.farmer_total, d.developer_residual, d.input_snapshot, d.input_sha256, d.calculated_by, d.calculated_at))
           OR (d.status IN ('APPROVED', 'COMPLETED') AND EXISTS (SELECT i.calculation_version, i.gross_revenue, i.deducted_costs, i.distributable, i.farmer_total, i.developer_residual, i.input_snapshot, i.input_sha256, i.calculated_by, i.calculated_at, i.approved_by, i.approved_at EXCEPT SELECT d.calculation_version, d.gross_revenue, d.deducted_costs, d.distributable, d.farmer_total, d.developer_residual, d.input_snapshot, d.input_sha256, d.calculated_by, d.calculated_at, d.approved_by, d.approved_at))
           OR (d.status IN ('COMPLETED', 'REJECTED', 'CANCELLED') AND EXISTS (SELECT i.run_code, i.project_id, i.organization_id, i.monitoring_period_id, i.currency, i.revenue_share_version_id, i.allocation_version_id, i.created_by, i.created_at, i.request_key, i.environment, i.calculation_version, i.gross_revenue, i.deducted_costs, i.distributable, i.farmer_total, i.developer_residual, i.input_snapshot, i.input_sha256, i.calculated_by, i.calculated_at, i.status, i.approved_by, i.approved_at, i.close_reason, i.action_key EXCEPT SELECT d.run_code, d.project_id, d.organization_id, d.monitoring_period_id, d.currency, d.revenue_share_version_id, d.allocation_version_id, d.created_by, d.created_at, d.request_key, d.environment, d.calculation_version, d.gross_revenue, d.deducted_costs, d.distributable, d.farmer_total, d.developer_residual, d.input_snapshot, d.input_sha256, d.calculated_by, d.calculated_at, d.status, d.approved_by, d.approved_at, d.close_reason, d.action_key)))
    BEGIN;
        THROW 51000, 'settlement_runs: identity fixed; figures and the input snapshot are frozen once calculated; APPROVED only becomes COMPLETED; COMPLETED / REJECTED / CANCELLED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_settlement_revenue_items_guard ON dbo.settlement_revenue_items
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'settlement_revenue_items: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.settlement_run_id, i.revenue_record_id, i.amount EXCEPT SELECT d.settlement_run_id, d.revenue_record_id, d.amount)
           OR (d.active = 0 AND i.active = 1))
    BEGIN;
        THROW 51000, 'settlement_revenue_items: run, record and amount are fixed; an inactive link is never re-activated.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_settlement_cost_items_guard ON dbo.settlement_cost_items
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'settlement_cost_items: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.settlement_run_id, i.project_cost_id, i.amount EXCEPT SELECT d.settlement_run_id, d.project_cost_id, d.amount)
           OR (d.active = 0 AND i.active = 1))
    BEGIN;
        THROW 51000, 'settlement_cost_items: run, record and amount are fixed; an inactive link is never re-activated.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_payouts_guard ON dbo.payouts
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'payouts: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE (d.status = 'PAID' AND i.status NOT IN ('PAID', 'RECONCILED'))
           OR EXISTS (SELECT i.payout_code, i.settlement_run_id, i.organization_id, i.farmer_id, i.amount, i.currency, i.replaces_payout_id, i.calculated_by, i.calculated_at, i.request_key, i.environment EXCEPT SELECT d.payout_code, d.settlement_run_id, d.organization_id, d.farmer_id, d.amount, d.currency, d.replaces_payout_id, d.calculated_by, d.calculated_at, d.request_key, d.environment)
           OR (d.status IN ('PAID', 'RECONCILED') AND EXISTS (SELECT i.payout_code, i.settlement_run_id, i.organization_id, i.farmer_id, i.amount, i.currency, i.replaces_payout_id, i.calculated_by, i.calculated_at, i.request_key, i.environment, i.adapter_code, i.bank_account_id, i.bank_last4, i.external_reference, i.evidence_document_id, i.approved_by, i.approved_at, i.executed_by, i.paid_at EXCEPT SELECT d.payout_code, d.settlement_run_id, d.organization_id, d.farmer_id, d.amount, d.currency, d.replaces_payout_id, d.calculated_by, d.calculated_at, d.request_key, d.environment, d.adapter_code, d.bank_account_id, d.bank_last4, d.external_reference, d.evidence_document_id, d.approved_by, d.approved_at, d.executed_by, d.paid_at))
           OR (d.status IN ('RECONCILED', 'REJECTED', 'CANCELLED', 'FAILED') AND EXISTS (SELECT i.payout_code, i.settlement_run_id, i.organization_id, i.farmer_id, i.amount, i.currency, i.replaces_payout_id, i.calculated_by, i.calculated_at, i.request_key, i.environment, i.adapter_code, i.bank_account_id, i.bank_last4, i.external_reference, i.evidence_document_id, i.approved_by, i.approved_at, i.executed_by, i.paid_at, i.status, i.reconciled_at, i.reason, i.action_key EXCEPT SELECT d.payout_code, d.settlement_run_id, d.organization_id, d.farmer_id, d.amount, d.currency, d.replaces_payout_id, d.calculated_by, d.calculated_at, d.request_key, d.environment, d.adapter_code, d.bank_account_id, d.bank_last4, d.external_reference, d.evidence_document_id, d.approved_by, d.approved_at, d.executed_by, d.paid_at, d.status, d.reconciled_at, d.reason, d.action_key)))
    BEGIN;
        THROW 51000, 'payouts: farmer, run and amount are fixed; execution evidence frozen once PAID (then only RECONCILED); RECONCILED / REJECTED / CANCELLED / FAILED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_payout_adjustments_guard ON dbo.payout_adjustments
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'payout_adjustments: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.adjustment_code, i.project_id, i.organization_id, i.reversal_revenue_id, i.original_settlement_run_id, i.amount, i.currency, i.created_at, i.environment EXCEPT SELECT d.adjustment_code, d.project_id, d.organization_id, d.reversal_revenue_id, d.original_settlement_run_id, d.amount, d.currency, d.created_at, d.environment)
           OR (d.status = 'CLOSED' AND EXISTS (SELECT i.adjustment_code, i.project_id, i.organization_id, i.reversal_revenue_id, i.original_settlement_run_id, i.amount, i.currency, i.created_at, i.environment, i.status, i.closed_by, i.closed_at, i.resolution EXCEPT SELECT d.adjustment_code, d.project_id, d.organization_id, d.reversal_revenue_id, d.original_settlement_run_id, d.amount, d.currency, d.created_at, d.environment, d.status, d.closed_by, d.closed_at, d.resolution)))
    BEGIN;
        THROW 51000, 'payout_adjustments: identity and amount are fixed; CLOSED is final.', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: Phase 11 financial history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.revenue_records) OR EXISTS (SELECT 1 FROM dbo.revenue_share_versions) OR EXISTS (SELECT 1 FROM dbo.farm_allocation_versions)
   OR EXISTS (SELECT 1 FROM dbo.farm_allocation_lines) OR EXISTS (SELECT 1 FROM dbo.project_costs) OR EXISTS (SELECT 1 FROM dbo.settlement_runs)
   OR EXISTS (SELECT 1 FROM dbo.settlement_revenue_items) OR EXISTS (SELECT 1 FROM dbo.settlement_cost_items) OR EXISTS (SELECT 1 FROM dbo.farmer_entitlements)
   OR EXISTS (SELECT 1 FROM dbo.payouts) OR EXISTS (SELECT 1 FROM dbo.payout_transactions) OR EXISTS (SELECT 1 FROM dbo.payout_reconciliations)
   OR EXISTS (SELECT 1 FROM dbo.payout_adjustments)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('COST_EVIDENCE', 'PAYOUT_EVIDENCE', 'RECONCILIATION_EVIDENCE'))
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 11 revenue, sharing configuration, costs, settlements, payouts or financial documents exist.', 1;
END""")
    for trigger in ('trg_revenue_records_append_only', 'trg_farmer_entitlements_append_only', 'trg_payout_transactions_append_only', 'trg_payout_reconciliations_append_only', 'trg_farm_allocation_lines_append_only', 'trg_revenue_share_versions_guard', 'trg_farm_allocation_versions_guard', 'trg_project_costs_guard', 'trg_settlement_runs_guard', 'trg_settlement_revenue_items_guard', 'trg_settlement_cost_items_guard', 'trg_payouts_guard', 'trg_payout_adjustments_guard'):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE', 'BUYER_KYC_DOCUMENT', 'PAYMENT_EVIDENCE', 'REFUND_EVIDENCE', 'ORDER_CONFIRMATION', 'LISTING_DOCUMENT', 'OTHER')")
    for seq in ('seq_revenue_code', 'seq_revenue_share_code', 'seq_allocation_code', 'seq_cost_code', 'seq_settlement_code', 'seq_payout_code', 'seq_adjustment_code'):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_settlement_revenue_items_active', table_name='settlement_revenue_items', mssql_where=sa.text('active = 1'))
    op.drop_index(op.f('ix_settlement_revenue_items_settlement_run_id'), table_name='settlement_revenue_items')
    op.drop_table('settlement_revenue_items')
    op.drop_index('uq_payout_adjustments_reversal', table_name='payout_adjustments')
    op.drop_index(op.f('ix_payout_adjustments_project_id'), table_name='payout_adjustments')
    op.drop_table('payout_adjustments')
    op.drop_index('uq_revenue_records_reversal', table_name='revenue_records', mssql_where=sa.text('reverses_revenue_id IS NOT NULL'))
    op.drop_index('uq_revenue_records_recognition', table_name='revenue_records', mssql_where=sa.text("kind = 'RECOGNITION'"))
    op.drop_index('ix_revenue_records_scope', table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_order_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_payout_transactions_payout_id'), table_name='payout_transactions')
    op.drop_table('payout_transactions')
    op.drop_index(op.f('ix_payout_reconciliations_payout_id'), table_name='payout_reconciliations')
    op.drop_table('payout_reconciliations')
    op.drop_index('uq_settlement_cost_items_active', table_name='settlement_cost_items', mssql_where=sa.text('active = 1'))
    op.drop_index(op.f('ix_settlement_cost_items_settlement_run_id'), table_name='settlement_cost_items')
    op.drop_table('settlement_cost_items')
    op.drop_index('uq_payouts_request_key', table_name='payouts', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_payouts_open', table_name='payouts', mssql_where=sa.text("status IN ('CALCULATED', 'PENDING_APPROVAL', 'APPROVED', 'ON_HOLD', 'PAYMENT_PENDING', 'UNCONFIRMED', 'PAID', 'RECONCILED')"))
    op.drop_index('uq_payouts_external', table_name='payouts', mssql_where=sa.text('external_reference IS NOT NULL'))
    op.drop_index(op.f('ix_payouts_settlement_run_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_farmer_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('uq_farmer_entitlements_line', table_name='farmer_entitlements')
    op.drop_index(op.f('ix_farmer_entitlements_settlement_run_id'), table_name='farmer_entitlements')
    op.drop_index('ix_farmer_entitlements_farmer', table_name='farmer_entitlements')
    op.drop_table('farmer_entitlements')
    op.drop_index('uq_settlement_runs_request_key', table_name='settlement_runs', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index(op.f('ix_settlement_runs_project_id'), table_name='settlement_runs')
    op.drop_table('settlement_runs')
    op.drop_index('uq_farm_allocation_lines_farm', table_name='farm_allocation_lines')
    op.drop_index(op.f('ix_farm_allocation_lines_allocation_version_id'), table_name='farm_allocation_lines')
    op.drop_table('farm_allocation_lines')
    op.drop_index('uq_project_costs_request_key', table_name='project_costs', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index(op.f('ix_project_costs_project_id'), table_name='project_costs')
    op.drop_table('project_costs')
    op.drop_index('uq_farm_allocation_versions_request_key', table_name='farm_allocation_versions', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_farm_allocation_versions_no', table_name='farm_allocation_versions')
    op.drop_index(op.f('ix_farm_allocation_versions_project_id'), table_name='farm_allocation_versions')
    op.drop_table('farm_allocation_versions')
    op.drop_index('uq_revenue_share_versions_request_key', table_name='revenue_share_versions', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_revenue_share_versions_no', table_name='revenue_share_versions')
    op.drop_index(op.f('ix_revenue_share_versions_project_id'), table_name='revenue_share_versions')
    op.drop_table('revenue_share_versions')
    # ### end Alembic commands ###
