"""Phase 6 — laboratory & sample analysis.

9 tables (engagements + scope, samples, custody events, shipments + items, tests, results, QA reviews), sequences
SMP / SHP / LT, documents categories LAB_REPORT + CUSTODY_DOCUMENT (removed on downgrade only when unused), append-only
triggers on custody events and lab QA reviews, and the approved-result immutability trigger on lab_results.

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-03 02:42:21.921978
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_laboratory_engagements',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_org_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('replaces_engagement_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('proposed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('ended_by', sa.Uuid(), nullable=True),
    sa.Column('ended_at', mssql.DATETIME2(), nullable=True),
    sa.Column('ended_side', sa.Unicode(length=10), nullable=True),
    sa.Column('end_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("ended_side IS NULL OR ended_side IN ('PROJECT', 'LABORATORY')", name=op.f('ck_project_laboratory_engagements_ended_side')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_project_laboratory_engagements_environment')),
    sa.CheckConstraint("status <> 'ENDED' OR (end_reason IS NOT NULL AND ended_by IS NOT NULL)", name=op.f('ck_project_laboratory_engagements_end_reason')),
    sa.CheckConstraint("status = 'PROPOSED' OR accepted_by IS NOT NULL OR status = 'ENDED'", name=op.f('ck_project_laboratory_engagements_accepted')),
    sa.CheckConstraint("status IN ('PROPOSED', 'ACTIVE', 'ENDED')", name=op.f('ck_project_laboratory_engagements_status')),
    sa.CheckConstraint('accepted_by IS NULL OR accepted_by <> proposed_by', name=op.f('ck_project_laboratory_engagements_proposer_not_accepter')),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name=op.f('fk_project_laboratory_engagements_accepted_by_users')),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], name=op.f('fk_project_laboratory_engagements_ended_by_users')),
    sa.ForeignKeyConstraint(['laboratory_org_id'], ['organizations.id'], name=op.f('fk_project_laboratory_engagements_laboratory_org_id_organizations')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_project_laboratory_engagements_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_laboratory_engagements_project_id_projects')),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_project_laboratory_engagements_proposed_by_users')),
    sa.ForeignKeyConstraint(['replaces_engagement_id'], ['project_laboratory_engagements.id'], name=op.f('fk_project_laboratory_engagements_replaces_engagement_id_project_laboratory_engagements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_laboratory_engagements'))
    )
    op.create_index(op.f('ix_project_laboratory_engagements_laboratory_org_id'), 'project_laboratory_engagements', ['laboratory_org_id'], unique=False)
    op.create_index(op.f('ix_project_laboratory_engagements_project_id'), 'project_laboratory_engagements', ['project_id'], unique=False)
    op.create_index('uq_lab_engagements_active', 'project_laboratory_engagements', ['project_id', 'laboratory_org_id'], unique=True, mssql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('uq_lab_engagements_proposed', 'project_laboratory_engagements', ['project_id', 'laboratory_org_id'], unique=True, mssql_where=sa.text("status = 'PROPOSED'"))
    op.create_table('lab_shipments',
    sa.Column('shipment_code', sa.Unicode(length=30), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('carrier', sa.Unicode(length=120), nullable=True),
    sa.Column('tracking_number', sa.Unicode(length=120), nullable=True),
    sa.Column('notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('dispatched_by', sa.Uuid(), nullable=True),
    sa.Column('dispatched_at', mssql.DATETIME2(), nullable=True),
    sa.Column('received_at', mssql.DATETIME2(), nullable=True),
    sa.Column('cancel_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_lab_shipments_environment')),
    sa.CheckConstraint("status <> 'CANCELLED' OR cancel_reason IS NOT NULL", name=op.f('ck_lab_shipments_cancel_reason')),
    sa.CheckConstraint("status IN ('DRAFT', 'DISPATCHED', 'RECEIVED', 'CANCELLED')", name=op.f('ck_lab_shipments_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lab_shipments_created_by_users')),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], name=op.f('fk_lab_shipments_dispatched_by_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_laboratory_engagements.id'], name=op.f('fk_lab_shipments_engagement_id_project_laboratory_engagements')),
    sa.ForeignKeyConstraint(['laboratory_org_id'], ['organizations.id'], name=op.f('fk_lab_shipments_laboratory_org_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lab_shipments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_shipments')),
    sa.UniqueConstraint('shipment_code', name=op.f('uq_lab_shipments_shipment_code'))
    )
    op.create_index('ix_lab_shipments_lab_status', 'lab_shipments', ['laboratory_org_id', 'status'], unique=False)
    op.create_index(op.f('ix_lab_shipments_project_id'), 'lab_shipments', ['project_id'], unique=False)
    op.create_table('project_laboratory_engagement_rules',
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_monitoring_rule_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_laboratory_engagements.id'], name=op.f('fk_project_laboratory_engagement_rules_engagement_id_project_laboratory_engagements')),
    sa.ForeignKeyConstraint(['methodology_monitoring_rule_id'], ['methodology_monitoring_rules.id'], name=op.f('fk_project_laboratory_engagement_rules_methodology_monitoring_rule_id_methodology_monitoring_rules')),
    sa.PrimaryKeyConstraint('engagement_id', 'methodology_monitoring_rule_id', name=op.f('pk_project_laboratory_engagement_rules'))
    )
    op.create_table('lab_samples',
    sa.Column('sample_code', sa.Unicode(length=30), nullable=False),
    sa.Column('root_sample_id', sa.Uuid(), nullable=False),
    sa.Column('parent_sample_id', sa.Uuid(), nullable=True),
    sa.Column('field_collection_id', sa.Uuid(), nullable=False),
    sa.Column('sampling_point_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=500), nullable=False),
    sa.Column('depth_top_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('depth_bottom_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('quantity_unit', sa.Unicode(length=20), nullable=True),
    sa.Column('container_label', sa.Unicode(length=100), nullable=True),
    sa.Column('seal_number', sa.Unicode(length=100), nullable=True),
    sa.Column('accession_number', sa.Unicode(length=100), nullable=True),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('registered_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('sealed_by', sa.Uuid(), nullable=True),
    sa.Column('sealed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_lab_samples_environment')),
    sa.CheckConstraint("status IN ('REGISTERED', 'SEALED', 'IN_SHIPMENT', 'DISPATCHED', 'IN_TRANSIT', 'LAB_RECEIVED', 'REJECTED_AT_RECEIPT', 'LAB_REGISTERED', 'IN_ANALYSIS', 'ANALYSED', 'EXCEPTION', 'VOIDED')", name=op.f('ck_lab_samples_status')),
    sa.CheckConstraint('depth_bottom_cm > depth_top_cm', name=op.f('ck_lab_samples_depth')),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name=op.f('ck_lab_samples_quantity')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_laboratory_engagements.id'], name=op.f('fk_lab_samples_engagement_id_project_laboratory_engagements')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_lab_samples_farm_id_farms')),
    sa.ForeignKeyConstraint(['field_collection_id'], ['field_collection_records.id'], name=op.f('fk_lab_samples_field_collection_id_field_collection_records')),
    sa.ForeignKeyConstraint(['laboratory_org_id'], ['organizations.id'], name=op.f('fk_lab_samples_laboratory_org_id_organizations')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_lab_samples_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_lab_samples_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['lab_samples.id'], name=op.f('fk_lab_samples_parent_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lab_samples_project_id_projects')),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], name=op.f('fk_lab_samples_registered_by_users')),
    sa.ForeignKeyConstraint(['root_sample_id'], ['lab_samples.id'], name=op.f('fk_lab_samples_root_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['sampling_points.id'], name=op.f('fk_lab_samples_sampling_point_id_sampling_points')),
    sa.ForeignKeyConstraint(['sealed_by'], ['users.id'], name=op.f('fk_lab_samples_sealed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_samples')),
    sa.UniqueConstraint('sample_code', name=op.f('uq_lab_samples_sample_code'))
    )
    op.create_index(op.f('ix_lab_samples_field_collection_id'), 'lab_samples', ['field_collection_id'], unique=False)
    op.create_index(op.f('ix_lab_samples_laboratory_org_id'), 'lab_samples', ['laboratory_org_id'], unique=False)
    op.create_index(op.f('ix_lab_samples_root_sample_id'), 'lab_samples', ['root_sample_id'], unique=False)
    op.create_table('lab_shipment_items',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('added_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('receipt_condition', sa.Unicode(length=500), nullable=True),
    sa.Column('receipt_seal_number', sa.Unicode(length=100), nullable=True),
    sa.Column('receipt_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('received_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status <> 'REJECTED' OR receipt_reason IS NOT NULL", name=op.f('ck_lab_shipment_items_rejection_reason')),
    sa.CheckConstraint("status IN ('IN_SHIPMENT', 'REMOVED', 'RECEIVED', 'REJECTED')", name=op.f('ck_lab_shipment_items_status')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_lab_shipment_items_added_by_users')),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_lab_shipment_items_received_by_users')),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], name=op.f('fk_lab_shipment_items_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['shipment_id'], ['lab_shipments.id'], name=op.f('fk_lab_shipment_items_shipment_id_lab_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_shipment_items')),
    sa.UniqueConstraint('shipment_id', 'sample_id', name=op.f('uq_lab_shipment_items_shipment_id_sample_id'))
    )
    op.create_index(op.f('ix_lab_shipment_items_sample_id'), 'lab_shipment_items', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lab_shipment_items_shipment_id'), 'lab_shipment_items', ['shipment_id'], unique=False)
    op.create_index('uq_lab_shipment_items_open', 'lab_shipment_items', ['sample_id'], unique=True, mssql_where=sa.text("status = 'IN_SHIPMENT'"))
    op.create_table('lab_tests',
    sa.Column('test_code', sa.Unicode(length=30), nullable=False),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('root_sample_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_org_id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_monitoring_rule_id', sa.Uuid(), nullable=False),
    sa.Column('mrv_plan_measurement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('method_reported', sa.Unicode(length=500), nullable=True),
    sa.Column('retest_of_test_id', sa.Uuid(), nullable=True),
    sa.Column('retest_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('retest_requested_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_lab_tests_environment')),
    sa.CheckConstraint("status IN ('REQUESTED', 'IN_PROGRESS', 'RESULT_SUBMITTED', 'CLOSED', 'CANCELLED')", name=op.f('ck_lab_tests_status')),
    sa.CheckConstraint('retest_of_test_id IS NULL OR (retest_reason IS NOT NULL AND retest_requested_by IS NOT NULL)', name=op.f('ck_lab_tests_retest_reason')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lab_tests_created_by_users')),
    sa.ForeignKeyConstraint(['engagement_id'], ['project_laboratory_engagements.id'], name=op.f('fk_lab_tests_engagement_id_project_laboratory_engagements')),
    sa.ForeignKeyConstraint(['laboratory_org_id'], ['organizations.id'], name=op.f('fk_lab_tests_laboratory_org_id_organizations')),
    sa.ForeignKeyConstraint(['methodology_monitoring_rule_id'], ['methodology_monitoring_rules.id'], name=op.f('fk_lab_tests_methodology_monitoring_rule_id_methodology_monitoring_rules')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_lab_tests_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['mrv_plan_measurement_id'], ['mrv_plan_measurements.id'], name=op.f('fk_lab_tests_mrv_plan_measurement_id_mrv_plan_measurements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lab_tests_project_id_projects')),
    sa.ForeignKeyConstraint(['retest_of_test_id'], ['lab_tests.id'], name=op.f('fk_lab_tests_retest_of_test_id_lab_tests')),
    sa.ForeignKeyConstraint(['retest_requested_by'], ['users.id'], name=op.f('fk_lab_tests_retest_requested_by_users')),
    sa.ForeignKeyConstraint(['root_sample_id'], ['lab_samples.id'], name=op.f('fk_lab_tests_root_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], name=op.f('fk_lab_tests_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_lab_tests_started_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_tests')),
    sa.UniqueConstraint('test_code', name=op.f('uq_lab_tests_test_code'))
    )
    op.create_index('ix_lab_tests_lab_status', 'lab_tests', ['laboratory_org_id', 'status'], unique=False)
    op.create_index(op.f('ix_lab_tests_sample_id'), 'lab_tests', ['sample_id'], unique=False)
    op.create_index('uq_lab_tests_sample_rule', 'lab_tests', ['sample_id', 'methodology_monitoring_rule_id'], unique=True, mssql_where=sa.text("retest_of_test_id IS NULL AND status <> 'CANCELLED'"))
    op.create_table('sample_custody_events',
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Unicode(length=25), nullable=False),
    sa.Column('from_state', sa.Unicode(length=20), nullable=True),
    sa.Column('to_state', sa.Unicode(length=20), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_org_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.Unicode(length=40), nullable=True),
    sa.Column('actor_side', sa.Unicode(length=10), nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), nullable=False),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('location_text', sa.Unicode(length=300), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('seal_number', sa.Unicode(length=100), nullable=True),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.Unicode(length=15), nullable=True),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("actor_side IN ('PROJECT', 'LABORATORY')", name=op.f('ck_sample_custody_events_actor_side')),
    sa.CheckConstraint("event_type <> 'EXCEPTION_RECORDED' OR exception_type IS NOT NULL", name=op.f('ck_sample_custody_events_exception_type_required')),
    sa.CheckConstraint("event_type IN ('REGISTERED', 'SEALED', 'ADDED_TO_SHIPMENT', 'REMOVED_FROM_SHIPMENT', 'DISPATCHED', 'TRANSFERRED', 'RECEIVED', 'REJECTED', 'LAB_REGISTERED', 'ANALYSIS_STARTED', 'ANALYSIS_COMPLETED', 'EXCEPTION_RECORDED', 'EXCEPTION_RESOLVED', 'VOIDED')", name=op.f('ck_sample_custody_events_event_type')),
    sa.CheckConstraint("event_type NOT IN ('REJECTED', 'EXCEPTION_RECORDED', 'EXCEPTION_RESOLVED', 'VOIDED') OR reason IS NOT NULL", name=op.f('ck_sample_custody_events_reason_required')),
    sa.CheckConstraint("exception_type IS NULL OR exception_type IN ('DAMAGED', 'SEAL_BROKEN', 'LOST', 'OTHER')", name=op.f('ck_sample_custody_events_exception_type')),
    sa.CheckConstraint("to_state IN ('REGISTERED', 'SEALED', 'IN_SHIPMENT', 'DISPATCHED', 'IN_TRANSIT', 'LAB_RECEIVED', 'REJECTED_AT_RECEIPT', 'LAB_REGISTERED', 'IN_ANALYSIS', 'ANALYSED', 'EXCEPTION', 'VOIDED')", name=op.f('ck_sample_custody_events_to_state')),
    sa.ForeignKeyConstraint(['actor_org_id'], ['organizations.id'], name=op.f('fk_sample_custody_events_actor_org_id_organizations')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_sample_custody_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_sample_custody_events_document_id_documents')),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], name=op.f('fk_sample_custody_events_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['shipment_id'], ['lab_shipments.id'], name=op.f('fk_sample_custody_events_shipment_id_lab_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_custody_events')),
    sa.UniqueConstraint('sample_id', 'sequence_no', name=op.f('uq_sample_custody_events_sample_id_sequence_no'))
    )
    op.create_index(op.f('ix_sample_custody_events_sample_id'), 'sample_custody_events', ['sample_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_result_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_by_result_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('sample_id', sa.Uuid(), nullable=False),
    sa.Column('root_sample_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_org_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_monitoring_rule_id', sa.Uuid(), nullable=False),
    sa.Column('mrv_plan_measurement_id', sa.Uuid(), nullable=False),
    sa.Column('result_type', sa.Unicode(length=10), nullable=False),
    sa.Column('value_number', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.Unicode(length=200), nullable=True),
    sa.Column('unit', sa.Unicode(length=40), nullable=True),
    sa.Column('analysed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('analyst_id', sa.Uuid(), nullable=False),
    sa.Column('method_reported', sa.Unicode(length=500), nullable=True),
    sa.Column('report_document_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Unicode(length=15), nullable=False),
    sa.Column('external_result_id', sa.Unicode(length=120), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(result_type = 'NUMERIC' AND value_number IS NOT NULL AND value_text IS NULL) OR (result_type = 'TEXT' AND value_text IS NOT NULL AND value_number IS NULL)", name=op.f('ck_lab_results_one_value')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_lab_results_environment')),
    sa.CheckConstraint("source <> 'LIMS_IMPORT' OR external_result_id IS NOT NULL", name=op.f('ck_lab_results_lims_external_id')),
    sa.CheckConstraint("source IN ('MANUAL', 'LIMS_IMPORT')", name=op.f('ck_lab_results_source')),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'QA_REVIEW', 'APPROVED', 'REJECTED', 'RETEST_REQUIRED', 'WITHDRAWN', 'SUPERSEDED')", name=op.f('ck_lab_results_status')),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], name=op.f('fk_lab_results_analyst_id_users')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_lab_results_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lab_results_created_by_users')),
    sa.ForeignKeyConstraint(['laboratory_org_id'], ['organizations.id'], name=op.f('fk_lab_results_laboratory_org_id_organizations')),
    sa.ForeignKeyConstraint(['methodology_monitoring_rule_id'], ['methodology_monitoring_rules.id'], name=op.f('fk_lab_results_methodology_monitoring_rule_id_methodology_monitoring_rules')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_lab_results_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['mrv_plan_measurement_id'], ['mrv_plan_measurements.id'], name=op.f('fk_lab_results_mrv_plan_measurement_id_mrv_plan_measurements')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lab_results_project_id_projects')),
    sa.ForeignKeyConstraint(['report_document_id'], ['documents.id'], name=op.f('fk_lab_results_report_document_id_documents')),
    sa.ForeignKeyConstraint(['root_sample_id'], ['lab_samples.id'], name=op.f('fk_lab_results_root_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['sample_id'], ['lab_samples.id'], name=op.f('fk_lab_results_sample_id_lab_samples')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_lab_results_submitted_by_users')),
    sa.ForeignKeyConstraint(['superseded_by_result_id'], ['lab_results.id'], name=op.f('fk_lab_results_superseded_by_result_id_lab_results')),
    sa.ForeignKeyConstraint(['supersedes_result_id'], ['lab_results.id'], name=op.f('fk_lab_results_supersedes_result_id_lab_results')),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], name=op.f('fk_lab_results_test_id_lab_tests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_results')),
    sa.UniqueConstraint('test_id', 'version', name=op.f('uq_lab_results_test_id_version'))
    )
    op.create_index('ix_lab_results_lab_status', 'lab_results', ['laboratory_org_id', 'status'], unique=False)
    op.create_index(op.f('ix_lab_results_project_id'), 'lab_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_lab_results_sample_id'), 'lab_results', ['sample_id'], unique=False)
    op.create_index(op.f('ix_lab_results_test_id'), 'lab_results', ['test_id'], unique=False)
    op.create_index('uq_lab_results_approved', 'lab_results', ['root_sample_id', 'methodology_monitoring_rule_id'], unique=True, mssql_where=sa.text("status = 'APPROVED'"))
    op.create_index('uq_lab_results_external', 'lab_results', ['laboratory_org_id', 'external_result_id'], unique=True, mssql_where=sa.text('external_result_id IS NOT NULL'))
    op.create_table('lab_result_qa_reviews',
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Unicode(length=20), nullable=False),
    sa.Column('checks', sa.UnicodeText(), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=False),
    sa.Column('configuration_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED', 'RETEST_REQUIRED')", name=op.f('ck_lab_result_qa_reviews_decision')),
    sa.CheckConstraint('checks IS NULL OR ISJSON(checks) = 1', name=op.f('ck_lab_result_qa_reviews_checks_json')),
    sa.ForeignKeyConstraint(['result_id'], ['lab_results.id'], name=op.f('fk_lab_result_qa_reviews_result_id_lab_results')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_lab_result_qa_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_result_qa_reviews'))
    )
    op.create_index(op.f('ix_lab_result_qa_reviews_result_id'), 'lab_result_qa_reviews', ['result_id'], unique=False)
    # ### end Alembic commands ###

    # ---- hand-written: sequences, documents category, append-only and approved-result immutability triggers
    op.execute("CREATE SEQUENCE dbo.seq_sample_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.execute("CREATE SEQUENCE dbo.seq_shipment_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.execute("CREATE SEQUENCE dbo.seq_lab_test_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_sample_custody_events_append_only ON dbo.sample_custody_events
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'sample_custody_events is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_lab_result_qa_reviews_append_only ON dbo.lab_result_qa_reviews
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'lab_result_qa_reviews is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_lab_results_approved_immutable ON dbo.lab_results
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted WHERE status IN ('APPROVED', 'SUPERSEDED'))
    BEGIN;
        THROW 51000, 'lab_results: approved results cannot be deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE d.status IN ('APPROVED', 'SUPERSEDED') AND (
            (d.status = 'APPROVED' AND i.status NOT IN ('APPROVED', 'SUPERSEDED'))
            OR (d.status = 'SUPERSEDED' AND (i.status <> 'SUPERSEDED' OR EXISTS (
                SELECT i.superseded_by_result_id, i.superseded_at EXCEPT SELECT d.superseded_by_result_id, d.superseded_at)))
            OR EXISTS (SELECT i.test_id, i.version, i.supersedes_result_id, i.sample_id, i.root_sample_id, i.project_id, i.laboratory_org_id, i.methodology_version_id, i.methodology_monitoring_rule_id, i.mrv_plan_measurement_id, i.result_type, i.value_number, i.value_text, i.unit, i.analysed_at, i.analyst_id, i.method_reported, i.report_document_id, i.source, i.external_result_id, i.status_reason, i.created_by, i.created_at, i.submitted_by, i.submitted_at, i.approved_by, i.approved_at, i.environment EXCEPT SELECT d.test_id, d.version, d.supersedes_result_id, d.sample_id, d.root_sample_id, d.project_id, d.laboratory_org_id, d.methodology_version_id, d.methodology_monitoring_rule_id, d.mrv_plan_measurement_id, d.result_type, d.value_number, d.value_text, d.unit, d.analysed_at, d.analyst_id, d.method_reported, d.report_document_id, d.source, d.external_result_id, d.status_reason, d.created_by, d.created_at, d.submitted_by, d.submitted_at, d.approved_by, d.approved_at, d.environment)))
    BEGIN;
        THROW 51000, 'lab_results: an approved result is immutable (only APPROVED -> SUPERSEDED is allowed).', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: refuse to drop the Phase 6 document categories while documents use them
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('LAB_REPORT', 'CUSTODY_DOCUMENT'))
BEGIN;
    THROW 51000, 'Downgrade refused: LAB_REPORT / CUSTODY_DOCUMENT documents exist.', 1;
END""")
    op.execute("DROP TRIGGER IF EXISTS trg_lab_results_approved_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_lab_result_qa_reviews_append_only")
    op.execute("DROP TRIGGER IF EXISTS trg_sample_custody_events_append_only")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'OTHER')")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_sample_code")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_shipment_code")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_lab_test_code")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_result_qa_reviews_result_id'), table_name='lab_result_qa_reviews')
    op.drop_table('lab_result_qa_reviews')
    op.drop_index('uq_lab_results_external', table_name='lab_results', mssql_where=sa.text('external_result_id IS NOT NULL'))
    op.drop_index('uq_lab_results_approved', table_name='lab_results', mssql_where=sa.text("status = 'APPROVED'"))
    op.drop_index(op.f('ix_lab_results_test_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_sample_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_project_id'), table_name='lab_results')
    op.drop_index('ix_lab_results_lab_status', table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_sample_custody_events_sample_id'), table_name='sample_custody_events')
    op.drop_table('sample_custody_events')
    op.drop_index('uq_lab_tests_sample_rule', table_name='lab_tests', mssql_where=sa.text("retest_of_test_id IS NULL AND status <> 'CANCELLED'"))
    op.drop_index(op.f('ix_lab_tests_sample_id'), table_name='lab_tests')
    op.drop_index('ix_lab_tests_lab_status', table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index('uq_lab_shipment_items_open', table_name='lab_shipment_items', mssql_where=sa.text("status = 'IN_SHIPMENT'"))
    op.drop_index(op.f('ix_lab_shipment_items_shipment_id'), table_name='lab_shipment_items')
    op.drop_index(op.f('ix_lab_shipment_items_sample_id'), table_name='lab_shipment_items')
    op.drop_table('lab_shipment_items')
    op.drop_index(op.f('ix_lab_samples_root_sample_id'), table_name='lab_samples')
    op.drop_index(op.f('ix_lab_samples_laboratory_org_id'), table_name='lab_samples')
    op.drop_index(op.f('ix_lab_samples_field_collection_id'), table_name='lab_samples')
    op.drop_table('lab_samples')
    op.drop_table('project_laboratory_engagement_rules')
    op.drop_index(op.f('ix_lab_shipments_project_id'), table_name='lab_shipments')
    op.drop_index('ix_lab_shipments_lab_status', table_name='lab_shipments')
    op.drop_table('lab_shipments')
    op.drop_index('uq_lab_engagements_proposed', table_name='project_laboratory_engagements', mssql_where=sa.text("status = 'PROPOSED'"))
    op.drop_index('uq_lab_engagements_active', table_name='project_laboratory_engagements', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_project_laboratory_engagements_project_id'), table_name='project_laboratory_engagements')
    op.drop_index(op.f('ix_project_laboratory_engagements_laboratory_org_id'), table_name='project_laboratory_engagements')
    op.drop_table('project_laboratory_engagements')
    # ### end Alembic commands ###
