"""phase5 mrv sampling

MRV (spec section 7.6, 7.7): MRV plans (+ measurement definitions), monitoring periods, versioned strata (+ farms,
characteristics), sampling designs + versions + stratum allocations, sampling points (geography, spatial index),
relocations, assignments, field collection records (versioned, GPS geography), monitoring records (versioned),
MRV evidence, versioned MRV datasets (frozen snapshot) and QA reviews. Code sequences SP- and FIELD-.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 23:50:26.591489
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

import app.models.gis

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_strata',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.Unicode(length=2000), nullable=True),
    sa.Column('criteria', sa.UnicodeText(), nullable=True),
    sa.Column('geometry', app.models.gis.Geography(), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('farm_boundary_ids', sa.UnicodeText(), nullable=True),
    sa.Column('source', sa.Unicode(length=15), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("source IN ('FARM_GROUPING', 'IMPORTED')", name=op.f('ck_project_strata_source')),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'SUPERSEDED', 'RETIRED')", name=op.f('ck_project_strata_status')),
    sa.CheckConstraint('criteria IS NULL OR ISJSON(criteria) = 1', name=op.f('ck_project_strata_criteria_json')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_project_strata_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_strata_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_strata_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_strata')),
    sa.UniqueConstraint('record_id', 'version', name=op.f('uq_project_strata_record_id_version'))
    )
    op.create_index(op.f('ix_project_strata_project_id'), 'project_strata', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_strata_record_id'), 'project_strata', ['record_id'], unique=False)
    op.create_index('uq_project_strata_current', 'project_strata', ['record_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    op.create_table('stratum_characteristics',
    sa.Column('stratum_id', sa.Uuid(), nullable=False),
    sa.Column('characteristic', sa.Unicode(length=25), nullable=False),
    sa.Column('value', sa.Unicode(length=200), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('required_by_methodology', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("characteristic IN ('SOIL_TYPE', 'CROP', 'LAND_USE', 'MANAGEMENT_PRACTICE', 'IRRIGATION', 'GEOGRAPHY', 'CLIMATE', 'OTHER')", name=op.f('ck_stratum_characteristics_characteristic')),
    sa.CheckConstraint("source IN ('FARM_DATA', 'FIELD_OBSERVATION', 'DECLARED', 'EXTERNAL_DATASET')", name=op.f('ck_stratum_characteristics_source')),
    sa.ForeignKeyConstraint(['stratum_id'], ['project_strata.id'], name=op.f('fk_stratum_characteristics_stratum_id_project_strata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stratum_characteristics')),
    sa.UniqueConstraint('stratum_id', 'characteristic', name=op.f('uq_stratum_characteristics_stratum_id_characteristic'))
    )
    op.create_index(op.f('ix_stratum_characteristics_stratum_id'), 'stratum_characteristics', ['stratum_id'], unique=False)
    op.create_table('stratum_farms',
    sa.Column('stratum_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farm_boundary_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['farm_boundary_id'], ['farm_boundaries.id'], name=op.f('fk_stratum_farms_farm_boundary_id_farm_boundaries')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_stratum_farms_farm_id_farms')),
    sa.ForeignKeyConstraint(['stratum_id'], ['project_strata.id'], name=op.f('fk_stratum_farms_stratum_id_project_strata')),
    sa.PrimaryKeyConstraint('stratum_id', 'farm_id', name=op.f('pk_stratum_farms'))
    )
    op.create_index(op.f('ix_stratum_farms_farm_id'), 'stratum_farms', ['farm_id'], unique=False)
    op.create_table('mrv_plans',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('project_methodology_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_frequency', sa.Unicode(length=200), nullable=True),
    sa.Column('monitoring_start', sa.Date(), nullable=True),
    sa.Column('monitoring_end', sa.Date(), nullable=True),
    sa.Column('quantification_approach', sa.Unicode(length=25), nullable=False),
    sa.Column('sampling_requirements_ref', sa.Unicode(length=1000), nullable=True),
    sa.Column('required_evidence', sa.Unicode(length=2000), nullable=True),
    sa.Column('configuration_status', sa.Unicode(length=25), nullable=False),
    sa.Column('configuration_gaps', sa.UnicodeText(), nullable=True),
    sa.Column('gaps_acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("configuration_status IN ('CONFIGURED', 'CONFIGURATION_REQUIRED')", name=op.f('ck_mrv_plans_configuration_status')),
    sa.CheckConstraint("quantification_approach IN ('MEASURE_AND_REMEASURE', 'MEASURE_AND_MODEL', 'OTHER', 'CONFIGURATION_REQUIRED')", name=op.f('ck_mrv_plans_quantification_approach')),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'SUPERSEDED', 'WITHDRAWN')", name=op.f('ck_mrv_plans_status')),
    sa.CheckConstraint('configuration_gaps IS NULL OR ISJSON(configuration_gaps) = 1', name=op.f('ck_mrv_plans_gaps_json')),
    sa.CheckConstraint('monitoring_end IS NULL OR monitoring_start IS NULL OR monitoring_end > monitoring_start', name=op.f('ck_mrv_plans_dates')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_mrv_plans_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mrv_plans_created_by_users')),
    sa.ForeignKeyConstraint(['gaps_acknowledged_by'], ['users.id'], name=op.f('fk_mrv_plans_gaps_acknowledged_by_users')),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_mrv_plans_methodology_id_methodologies')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_mrv_plans_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_mrv_plans_project_id_projects')),
    sa.ForeignKeyConstraint(['project_methodology_id'], ['project_methodologies.id'], name=op.f('fk_mrv_plans_project_methodology_id_project_methodologies')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_mrv_plans_submitted_by_users')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['mrv_plans.id'], name=op.f('fk_mrv_plans_supersedes_id_mrv_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrv_plans')),
    sa.UniqueConstraint('project_id', 'plan_version', name=op.f('uq_mrv_plans_project_id_plan_version'))
    )
    op.create_index(op.f('ix_mrv_plans_project_id'), 'mrv_plans', ['project_id'], unique=False)
    op.create_index('uq_mrv_plans_approved', 'mrv_plans', ['project_id'], unique=True, mssql_where=sa.text("status = 'APPROVED'"))
    op.create_table('monitoring_periods',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mrv_plan_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('purpose', sa.Unicode(length=15), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Unicode(length=16), nullable=False),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("purpose IN ('BASELINE', 'MONITORING', 'VERIFICATION', 'OTHER')", name=op.f('ck_monitoring_periods_purpose')),
    sa.CheckConstraint("status IN ('DRAFT', 'PLANNED', 'ACTIVE', 'DATA_COLLECTION', 'SUBMITTED', 'QA_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED')", name=op.f('ck_monitoring_periods_status')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_monitoring_periods_dates')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_monitoring_periods_created_by_users')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_monitoring_periods_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['mrv_plan_id'], ['mrv_plans.id'], name=op.f('fk_monitoring_periods_mrv_plan_id_mrv_plans')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_monitoring_periods_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_periods')),
    sa.UniqueConstraint('project_id', 'period_number', name=op.f('uq_monitoring_periods_project_id_period_number'))
    )
    op.create_index(op.f('ix_monitoring_periods_mrv_plan_id'), 'monitoring_periods', ['mrv_plan_id'], unique=False)
    op.create_index(op.f('ix_monitoring_periods_project_id'), 'monitoring_periods', ['project_id'], unique=False)
    op.create_table('mrv_plan_measurements',
    sa.Column('mrv_plan_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('category', sa.Unicode(length=20), nullable=False),
    sa.Column('value_type', sa.Unicode(length=10), nullable=False),
    sa.Column('unit', sa.Unicode(length=40), nullable=True),
    sa.Column('allowed_values', sa.UnicodeText(), nullable=True),
    sa.Column('level', sa.Unicode(length=20), nullable=False),
    sa.Column('frequency', sa.Unicode(length=120), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('monitoring_rule_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('SOIL', 'CROP', 'PLANTING', 'HARVEST', 'TILLAGE', 'FERTILIZER', 'MANURE', 'RESIDUE', 'IRRIGATION', 'WATER_MANAGEMENT', 'YIELD', 'PRACTICE_CHANGE', 'FUEL', 'OTHER')", name=op.f('ck_mrv_plan_measurements_category')),
    sa.CheckConstraint("level IN ('PROJECT', 'FARM', 'STRATUM', 'SAMPLING_POINT')", name=op.f('ck_mrv_plan_measurements_level')),
    sa.CheckConstraint("source IN ('METHODOLOGY', 'PROJECT_CONFIGURED')", name=op.f('ck_mrv_plan_measurements_source')),
    sa.CheckConstraint("value_type IN ('NUMBER', 'TEXT', 'DATE', 'BOOLEAN', 'CHOICE')", name=op.f('ck_mrv_plan_measurements_value_type')),
    sa.CheckConstraint('allowed_values IS NULL OR ISJSON(allowed_values) = 1', name=op.f('ck_mrv_plan_measurements_allowed_values_json')),
    sa.ForeignKeyConstraint(['monitoring_rule_id'], ['methodology_monitoring_rules.id'], name=op.f('fk_mrv_plan_measurements_monitoring_rule_id_methodology_monitoring_rules')),
    sa.ForeignKeyConstraint(['mrv_plan_id'], ['mrv_plans.id'], name=op.f('fk_mrv_plan_measurements_mrv_plan_id_mrv_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrv_plan_measurements')),
    sa.UniqueConstraint('mrv_plan_id', 'code', name=op.f('uq_mrv_plan_measurements_mrv_plan_id_code'))
    )
    op.create_index(op.f('ix_mrv_plan_measurements_mrv_plan_id'), 'mrv_plan_measurements', ['mrv_plan_id'], unique=False)
    op.create_table('mrv_datasets',
    sa.Column('dataset_code', sa.Unicode(length=40), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('mrv_plan_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('snapshot', sa.UnicodeText(), nullable=True),
    sa.Column('snapshot_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('configuration_gaps', sa.UnicodeText(), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'COLLECTING', 'SUBMITTED', 'QA_REVIEW', 'APPROVED', 'REJECTED', 'SUPERSEDED')", name=op.f('ck_mrv_datasets_status')),
    sa.CheckConstraint('snapshot IS NULL OR ISJSON(snapshot) = 1', name=op.f('ck_mrv_datasets_snapshot_json')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_mrv_datasets_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mrv_datasets_created_by_users')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_mrv_datasets_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_mrv_datasets_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['mrv_plan_id'], ['mrv_plans.id'], name=op.f('fk_mrv_datasets_mrv_plan_id_mrv_plans')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_mrv_datasets_project_id_projects')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_mrv_datasets_submitted_by_users')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['mrv_datasets.id'], name=op.f('fk_mrv_datasets_supersedes_id_mrv_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrv_datasets')),
    sa.UniqueConstraint('dataset_code', name=op.f('uq_mrv_datasets_dataset_code')),
    sa.UniqueConstraint('monitoring_period_id', 'version', name=op.f('uq_mrv_datasets_monitoring_period_id_version'))
    )
    op.create_index(op.f('ix_mrv_datasets_monitoring_period_id'), 'mrv_datasets', ['monitoring_period_id'], unique=False)
    op.create_index(op.f('ix_mrv_datasets_project_id'), 'mrv_datasets', ['project_id'], unique=False)
    op.create_index('uq_mrv_datasets_open', 'mrv_datasets', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status IN ('DRAFT', 'COLLECTING', 'SUBMITTED', 'QA_REVIEW')"))
    op.create_table('mrv_evidence',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.Unicode(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.Unicode(length=20), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('checksum_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('captured_at', mssql.DATETIME2(), nullable=True),
    sa.Column('description', sa.Unicode(length=2000), nullable=True),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("entity_type IN ('PROJECT', 'FARM', 'MONITORING_PERIOD', 'SAMPLING_POINT', 'FIELD_COLLECTION', 'MONITORING_RECORD')", name=op.f('ck_mrv_evidence_entity_type')),
    sa.CheckConstraint("evidence_type IN ('FIELD_PHOTO', 'FIELD_NOTE', 'PRACTICE_RECORD', 'DOCUMENT', 'GPS', 'OBSERVATION')", name=op.f('ck_mrv_evidence_evidence_type')),
    sa.CheckConstraint("source IN ('FIELD_COLLECTOR', 'STAFF', 'FARMER', 'DOCUMENT')", name=op.f('ck_mrv_evidence_source')),
    sa.CheckConstraint("status IN ('SUBMITTED', 'ACCEPTED', 'REJECTED')", name=op.f('ck_mrv_evidence_status')),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)', name=op.f('ck_mrv_evidence_coordinates')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_mrv_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_mrv_evidence_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_mrv_evidence_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_mrv_evidence_reviewed_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_mrv_evidence_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrv_evidence'))
    )
    op.create_index(op.f('ix_mrv_evidence_entity_id'), 'mrv_evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_mrv_evidence_project_id'), 'mrv_evidence', ['project_id'], unique=False)
    op.create_table('sampling_designs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mrv_plan_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sampling_designs_created_by_users')),
    sa.ForeignKeyConstraint(['methodology_id'], ['methodologies.id'], name=op.f('fk_sampling_designs_methodology_id_methodologies')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_sampling_designs_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_sampling_designs_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['mrv_plan_id'], ['mrv_plans.id'], name=op.f('fk_sampling_designs_mrv_plan_id_mrv_plans')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sampling_designs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_designs')),
    sa.UniqueConstraint('monitoring_period_id', 'code', name=op.f('uq_sampling_designs_monitoring_period_id_code'))
    )
    op.create_index(op.f('ix_sampling_designs_monitoring_period_id'), 'sampling_designs', ['monitoring_period_id'], unique=False)
    op.create_index(op.f('ix_sampling_designs_project_id'), 'sampling_designs', ['project_id'], unique=False)
    op.create_table('mrv_qa_reviews',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('checks', sa.UnicodeText(), nullable=True),
    sa.Column('result', sa.Unicode(length=25), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("result IS NULL OR result IN ('PASS', 'FAIL', 'REQUIRES_CORRECTION')", name=op.f('ck_mrv_qa_reviews_result')),
    sa.CheckConstraint('checks IS NULL OR ISJSON(checks) = 1', name=op.f('ck_mrv_qa_reviews_checks_json')),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_mrv_qa_reviews_completed_by_users')),
    sa.ForeignKeyConstraint(['dataset_id'], ['mrv_datasets.id'], name=op.f('fk_mrv_qa_reviews_dataset_id_mrv_datasets')),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_mrv_qa_reviews_started_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrv_qa_reviews'))
    )
    op.create_index(op.f('ix_mrv_qa_reviews_dataset_id'), 'mrv_qa_reviews', ['dataset_id'], unique=False)
    op.create_table('sampling_design_versions',
    sa.Column('design_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('statistical_design', sa.Unicode(length=20), nullable=False),
    sa.Column('target_precision_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence_level_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('variability_cv_pct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('min_detectable_difference', sa.Unicode(length=100), nullable=True),
    sa.Column('sampling_method', sa.Unicode(length=1000), nullable=True),
    sa.Column('depth_top_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('depth_bottom_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('min_distance_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('repeat_sampling', sa.Unicode(length=500), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('requirement_source', sa.Unicode(length=20), nullable=False),
    sa.Column('configuration_status', sa.Unicode(length=25), nullable=False),
    sa.Column('configuration_gaps', sa.UnicodeText(), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('points_generated_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("configuration_status IN ('CONFIGURED', 'CONFIGURATION_REQUIRED')", name=op.f('ck_sampling_design_versions_configuration_status')),
    sa.CheckConstraint("requirement_source IN ('METHODOLOGY', 'PROJECT_CONFIGURED')", name=op.f('ck_sampling_design_versions_requirement_source')),
    sa.CheckConstraint("statistical_design IN ('STRATIFIED_RANDOM', 'SIMPLE_RANDOM', 'SYSTEMATIC_GRID', 'OTHER')", name=op.f('ck_sampling_design_versions_statistical_design')),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'SUPERSEDED')", name=op.f('ck_sampling_design_versions_status')),
    sa.CheckConstraint('configuration_gaps IS NULL OR ISJSON(configuration_gaps) = 1', name=op.f('ck_sampling_design_versions_gaps_json')),
    sa.CheckConstraint('depth_bottom_cm > depth_top_cm', name=op.f('ck_sampling_design_versions_depth')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_sampling_design_versions_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sampling_design_versions_created_by_users')),
    sa.ForeignKeyConstraint(['design_id'], ['sampling_designs.id'], name=op.f('fk_sampling_design_versions_design_id_sampling_designs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_design_versions')),
    sa.UniqueConstraint('design_id', 'version', name=op.f('uq_sampling_design_versions_design_id_version'))
    )
    op.create_index(op.f('ix_sampling_design_versions_design_id'), 'sampling_design_versions', ['design_id'], unique=False)
    op.create_index('uq_sampling_design_versions_approved', 'sampling_design_versions', ['design_id'], unique=True, mssql_where=sa.text("status = 'APPROVED'"))
    op.create_table('sampling_design_strata',
    sa.Column('design_version_id', sa.Uuid(), nullable=False),
    sa.Column('stratum_id', sa.Uuid(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('allocation_basis', sa.Unicode(length=500), nullable=True),
    sa.CheckConstraint('sample_count > 0', name=op.f('ck_sampling_design_strata_sample_count')),
    sa.ForeignKeyConstraint(['design_version_id'], ['sampling_design_versions.id'], name=op.f('fk_sampling_design_strata_design_version_id_sampling_design_versions')),
    sa.ForeignKeyConstraint(['stratum_id'], ['project_strata.id'], name=op.f('fk_sampling_design_strata_stratum_id_project_strata')),
    sa.PrimaryKeyConstraint('design_version_id', 'stratum_id', name=op.f('pk_sampling_design_strata'))
    )
    op.create_table('sampling_points',
    sa.Column('point_code', sa.Unicode(length=30), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('design_version_id', sa.Uuid(), nullable=False),
    sa.Column('stratum_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farm_boundary_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('location', app.models.gis.Geography(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('planned_depth_top_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('planned_depth_bottom_cm', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('assigned_collector_id', sa.Uuid(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED', 'ASSIGNED', 'COLLECTED', 'SKIPPED', 'CANCELLED')", name=op.f('ck_sampling_points_status')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180', name=op.f('ck_sampling_points_coordinates')),
    sa.ForeignKeyConstraint(['assigned_collector_id'], ['users.id'], name=op.f('fk_sampling_points_assigned_collector_id_users')),
    sa.ForeignKeyConstraint(['design_version_id'], ['sampling_design_versions.id'], name=op.f('fk_sampling_points_design_version_id_sampling_design_versions')),
    sa.ForeignKeyConstraint(['farm_boundary_id'], ['farm_boundaries.id'], name=op.f('fk_sampling_points_farm_boundary_id_farm_boundaries')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_sampling_points_farm_id_farms')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_sampling_points_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sampling_points_project_id_projects')),
    sa.ForeignKeyConstraint(['stratum_id'], ['project_strata.id'], name=op.f('fk_sampling_points_stratum_id_project_strata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_points')),
    sa.UniqueConstraint('design_version_id', 'stratum_id', 'sequence', name=op.f('uq_sampling_points_design_version_id_stratum_id_sequence')),
    sa.UniqueConstraint('point_code', name=op.f('uq_sampling_points_point_code'))
    )
    op.create_index(op.f('ix_sampling_points_assigned_collector_id'), 'sampling_points', ['assigned_collector_id'], unique=False)
    op.create_index(op.f('ix_sampling_points_design_version_id'), 'sampling_points', ['design_version_id'], unique=False)
    op.create_index(op.f('ix_sampling_points_farm_id'), 'sampling_points', ['farm_id'], unique=False)
    op.create_index(op.f('ix_sampling_points_monitoring_period_id'), 'sampling_points', ['monitoring_period_id'], unique=False)
    op.create_index(op.f('ix_sampling_points_project_id'), 'sampling_points', ['project_id'], unique=False)
    op.create_index(op.f('ix_sampling_points_stratum_id'), 'sampling_points', ['stratum_id'], unique=False)
    op.create_table('sampling_assignments',
    sa.Column('sampling_point_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('instructions', sa.Unicode(length=1000), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('ended_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REASSIGNED', 'COMPLETED', 'CANCELLED')", name=op.f('ck_sampling_assignments_status')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_sampling_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_sampling_assignments_collector_id_users')),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['sampling_points.id'], name=op.f('fk_sampling_assignments_sampling_point_id_sampling_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_assignments'))
    )
    op.create_index(op.f('ix_sampling_assignments_collector_id'), 'sampling_assignments', ['collector_id'], unique=False)
    op.create_index(op.f('ix_sampling_assignments_sampling_point_id'), 'sampling_assignments', ['sampling_point_id'], unique=False)
    op.create_index('uq_sampling_assignments_active', 'sampling_assignments', ['sampling_point_id'], unique=True, mssql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('sampling_point_relocations',
    sa.Column('sampling_point_id', sa.Uuid(), nullable=False),
    sa.Column('old_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('old_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('new_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('new_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('reason', sa.Unicode(length=1000), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_sampling_point_relocations_status')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_sampling_point_relocations_requested_by_users')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_sampling_point_relocations_reviewed_by_users')),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['sampling_points.id'], name=op.f('fk_sampling_point_relocations_sampling_point_id_sampling_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_point_relocations'))
    )
    op.create_index(op.f('ix_sampling_point_relocations_sampling_point_id'), 'sampling_point_relocations', ['sampling_point_id'], unique=False)
    op.create_table('field_collection_records',
    sa.Column('collection_code', sa.Unicode(length=30), nullable=False),
    sa.Column('sampling_point_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('collected_at', mssql.DATETIME2(), nullable=True),
    sa.Column('gps_location', app.models.gis.Geography(), nullable=True),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_accuracy_m', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('distance_from_point_m', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('gps_inside_farm', sa.Boolean(), nullable=True),
    sa.Column('deviation_note', sa.Unicode(length=1000), nullable=True),
    sa.Column('actual_depth_top_cm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('actual_depth_bottom_cm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('sample_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sample_unit', sa.Unicode(length=20), nullable=True),
    sa.Column('observations', sa.Unicode(length=2000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('checklist', sa.UnicodeText(), nullable=True),
    sa.Column('correction_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'SUBMITTED', 'ACCEPTED', 'RETURNED', 'SUPERSEDED')", name=op.f('ck_field_collection_records_status')),
    sa.CheckConstraint('actual_depth_bottom_cm IS NULL OR actual_depth_top_cm IS NULL OR actual_depth_bottom_cm > actual_depth_top_cm', name=op.f('ck_field_collection_records_depth')),
    sa.CheckConstraint('checklist IS NULL OR ISJSON(checklist) = 1', name=op.f('ck_field_collection_records_checklist_json')),
    sa.CheckConstraint('gps_latitude IS NULL OR gps_latitude BETWEEN -90 AND 90', name=op.f('ck_field_collection_records_gps_lat')),
    sa.CheckConstraint('gps_longitude IS NULL OR gps_longitude BETWEEN -180 AND 180', name=op.f('ck_field_collection_records_gps_lon')),
    sa.ForeignKeyConstraint(['assignment_id'], ['sampling_assignments.id'], name=op.f('fk_field_collection_records_assignment_id_sampling_assignments')),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], name=op.f('fk_field_collection_records_collector_id_users')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_field_collection_records_farm_id_farms')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_field_collection_records_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_field_collection_records_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_field_collection_records_reviewed_by_users')),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['sampling_points.id'], name=op.f('fk_field_collection_records_sampling_point_id_sampling_points')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['field_collection_records.id'], name=op.f('fk_field_collection_records_supersedes_id_field_collection_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_collection_records')),
    sa.UniqueConstraint('collection_code', name=op.f('uq_field_collection_records_collection_code'))
    )
    op.create_index(op.f('ix_field_collection_records_collector_id'), 'field_collection_records', ['collector_id'], unique=False)
    op.create_index(op.f('ix_field_collection_records_monitoring_period_id'), 'field_collection_records', ['monitoring_period_id'], unique=False)
    op.create_index(op.f('ix_field_collection_records_project_id'), 'field_collection_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_field_collection_records_sampling_point_id'), 'field_collection_records', ['sampling_point_id'], unique=False)
    op.create_table('monitoring_records',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('measurement_id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('stratum_id', sa.Uuid(), nullable=True),
    sa.Column('sampling_point_id', sa.Uuid(), nullable=True),
    sa.Column('field_collection_id', sa.Uuid(), nullable=True),
    sa.Column('measurement_phase', sa.Unicode(length=12), nullable=False),
    sa.Column('value_number', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.Unicode(length=1000), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.Unicode(length=40), nullable=True),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('source', sa.Unicode(length=20), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('notes', sa.Unicode(length=1000), nullable=True),
    sa.Column('change_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("measurement_phase IN ('BASELINE', 'PROJECT', 'MONITORING')", name=op.f('ck_monitoring_records_measurement_phase')),
    sa.CheckConstraint("source IN ('FIELD_OBSERVATION', 'FARMER_CLAIM', 'DOCUMENT', 'INSTRUMENT', 'OTHER')", name=op.f('ck_monitoring_records_source')),
    sa.CheckConstraint("status IN ('RECORDED', 'SUPERSEDED', 'RETRACTED')", name=op.f('ck_monitoring_records_status')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_monitoring_records_farm_id_farms')),
    sa.ForeignKeyConstraint(['field_collection_id'], ['field_collection_records.id'], name=op.f('fk_monitoring_records_field_collection_id_field_collection_records')),
    sa.ForeignKeyConstraint(['measurement_id'], ['mrv_plan_measurements.id'], name=op.f('fk_monitoring_records_measurement_id_mrv_plan_measurements')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_monitoring_records_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_monitoring_records_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_monitoring_records_recorded_by_users')),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['sampling_points.id'], name=op.f('fk_monitoring_records_sampling_point_id_sampling_points')),
    sa.ForeignKeyConstraint(['stratum_id'], ['project_strata.id'], name=op.f('fk_monitoring_records_stratum_id_project_strata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoring_records')),
    sa.UniqueConstraint('record_id', 'version', name=op.f('uq_monitoring_records_record_id_version'))
    )
    op.create_index(op.f('ix_monitoring_records_monitoring_period_id'), 'monitoring_records', ['monitoring_period_id'], unique=False)
    op.create_index(op.f('ix_monitoring_records_project_id'), 'monitoring_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_monitoring_records_record_id'), 'monitoring_records', ['record_id'], unique=False)
    op.create_index('uq_monitoring_records_current', 'monitoring_records', ['record_id'], unique=True, mssql_where=sa.text('is_current = 1'))
    # ### end Alembic commands ###
    op.execute("CREATE SPATIAL INDEX six_project_strata_geometry ON dbo.project_strata(geometry) USING GEOGRAPHY_AUTO_GRID")
    op.execute("CREATE SPATIAL INDEX six_sampling_points_location ON dbo.sampling_points(location) USING GEOGRAPHY_AUTO_GRID")
    op.execute("CREATE SPATIAL INDEX six_field_collection_records_gps ON dbo.field_collection_records(gps_location) USING GEOGRAPHY_AUTO_GRID")
    op.execute("CREATE SEQUENCE dbo.seq_sampling_point_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.execute("CREATE SEQUENCE dbo.seq_field_collection_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_sampling_point_code")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_field_collection_code")
    op.execute("DROP INDEX IF EXISTS six_project_strata_geometry ON dbo.project_strata")
    op.execute("DROP INDEX IF EXISTS six_sampling_points_location ON dbo.sampling_points")
    op.execute("DROP INDEX IF EXISTS six_field_collection_records_gps ON dbo.field_collection_records")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_monitoring_records_current', table_name='monitoring_records', mssql_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_monitoring_records_record_id'), table_name='monitoring_records')
    op.drop_index(op.f('ix_monitoring_records_project_id'), table_name='monitoring_records')
    op.drop_index(op.f('ix_monitoring_records_monitoring_period_id'), table_name='monitoring_records')
    op.drop_table('monitoring_records')
    op.drop_index(op.f('ix_field_collection_records_sampling_point_id'), table_name='field_collection_records')
    op.drop_index(op.f('ix_field_collection_records_project_id'), table_name='field_collection_records')
    op.drop_index(op.f('ix_field_collection_records_monitoring_period_id'), table_name='field_collection_records')
    op.drop_index(op.f('ix_field_collection_records_collector_id'), table_name='field_collection_records')
    op.drop_table('field_collection_records')
    op.drop_index(op.f('ix_sampling_point_relocations_sampling_point_id'), table_name='sampling_point_relocations')
    op.drop_table('sampling_point_relocations')
    op.drop_index('uq_sampling_assignments_active', table_name='sampling_assignments', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_sampling_assignments_sampling_point_id'), table_name='sampling_assignments')
    op.drop_index(op.f('ix_sampling_assignments_collector_id'), table_name='sampling_assignments')
    op.drop_table('sampling_assignments')
    op.drop_index(op.f('ix_sampling_points_stratum_id'), table_name='sampling_points')
    op.drop_index(op.f('ix_sampling_points_project_id'), table_name='sampling_points')
    op.drop_index(op.f('ix_sampling_points_monitoring_period_id'), table_name='sampling_points')
    op.drop_index(op.f('ix_sampling_points_farm_id'), table_name='sampling_points')
    op.drop_index(op.f('ix_sampling_points_design_version_id'), table_name='sampling_points')
    op.drop_index(op.f('ix_sampling_points_assigned_collector_id'), table_name='sampling_points')
    op.drop_table('sampling_points')
    op.drop_table('sampling_design_strata')
    op.drop_index('uq_sampling_design_versions_approved', table_name='sampling_design_versions', mssql_where=sa.text("status = 'APPROVED'"))
    op.drop_index(op.f('ix_sampling_design_versions_design_id'), table_name='sampling_design_versions')
    op.drop_table('sampling_design_versions')
    op.drop_index(op.f('ix_mrv_qa_reviews_dataset_id'), table_name='mrv_qa_reviews')
    op.drop_table('mrv_qa_reviews')
    op.drop_index(op.f('ix_sampling_designs_project_id'), table_name='sampling_designs')
    op.drop_index(op.f('ix_sampling_designs_monitoring_period_id'), table_name='sampling_designs')
    op.drop_table('sampling_designs')
    op.drop_index(op.f('ix_mrv_evidence_project_id'), table_name='mrv_evidence')
    op.drop_index(op.f('ix_mrv_evidence_entity_id'), table_name='mrv_evidence')
    op.drop_table('mrv_evidence')
    op.drop_index('uq_mrv_datasets_open', table_name='mrv_datasets', mssql_where=sa.text("status IN ('DRAFT', 'COLLECTING', 'SUBMITTED', 'QA_REVIEW')"))
    op.drop_index(op.f('ix_mrv_datasets_project_id'), table_name='mrv_datasets')
    op.drop_index(op.f('ix_mrv_datasets_monitoring_period_id'), table_name='mrv_datasets')
    op.drop_table('mrv_datasets')
    op.drop_index(op.f('ix_mrv_plan_measurements_mrv_plan_id'), table_name='mrv_plan_measurements')
    op.drop_table('mrv_plan_measurements')
    op.drop_index(op.f('ix_monitoring_periods_project_id'), table_name='monitoring_periods')
    op.drop_index(op.f('ix_monitoring_periods_mrv_plan_id'), table_name='monitoring_periods')
    op.drop_table('monitoring_periods')
    op.drop_index('uq_mrv_plans_approved', table_name='mrv_plans', mssql_where=sa.text("status = 'APPROVED'"))
    op.drop_index(op.f('ix_mrv_plans_project_id'), table_name='mrv_plans')
    op.drop_table('mrv_plans')
    op.drop_index(op.f('ix_stratum_farms_farm_id'), table_name='stratum_farms')
    op.drop_table('stratum_farms')
    op.drop_index(op.f('ix_stratum_characteristics_stratum_id'), table_name='stratum_characteristics')
    op.drop_table('stratum_characteristics')
    op.drop_index('uq_project_strata_current', table_name='project_strata', mssql_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_project_strata_record_id'), table_name='project_strata')
    op.drop_index(op.f('ix_project_strata_project_id'), table_name='project_strata')
    op.drop_table('project_strata')
    # ### end Alembic commands ###
