"""Phase 8B — VVB / ACVA verification workflow (verification only: no validation, registry, issuance or credits).

7 tables (verification assignments, submissions, findings + append-only finding events, corrective actions + append-only events,
decisions), sequences VAS / VSUB / VFND / CAR / VDEC, filtered unique indexes (one open assignment per monitoring period, one SUBMITTED
submission per assignment, one CURRENT decision per period), the documents categories VERIFICATION_REPORT / VERIFICATION_EVIDENCE
(removed on downgrade only when unused) and immutability triggers: events append-only; identities never change; a COI declaration is
fixed once made; closed assignments, closed submissions, accepted / cancelled corrective actions are final; a decision is immutable
except CURRENT -> SUPERSEDED; nothing is deleted. No Phase 1–8A data is changed or backfilled.

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-03 13:26:16.548086
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_assignments',
    sa.Column('assignment_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('vvb_organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('previous_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('proposed_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('coi_declaration', sa.Unicode(length=4000), nullable=True),
    sa.Column('coi_declared_by', sa.Uuid(), nullable=True),
    sa.Column('coi_declared_at', mssql.DATETIME2(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_side', sa.Unicode(length=10), nullable=True),
    sa.Column('closed_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_verification_assignments_environment')),
    sa.CheckConstraint("status IN ('PROPOSED', 'ACCEPTED', 'COMPLETED', 'DECLINED', 'WITHDRAWN', 'TERMINATED')", name=op.f('ck_verification_assignments_status')),
    sa.CheckConstraint("status NOT IN ('ACCEPTED', 'COMPLETED', 'TERMINATED') OR (coi_declaration IS NOT NULL AND accepted_by IS NOT NULL)", name=op.f('ck_verification_assignments_coi_on_accept')),
    sa.CheckConstraint("status NOT IN ('DECLINED', 'WITHDRAWN', 'TERMINATED') OR closed_reason IS NOT NULL", name=op.f('ck_verification_assignments_closed_reason')),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name=op.f('fk_verification_assignments_accepted_by_users')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_verification_assignments_closed_by_users')),
    sa.ForeignKeyConstraint(['coi_declared_by'], ['users.id'], name=op.f('fk_verification_assignments_coi_declared_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_verification_assignments_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['previous_assignment_id'], ['verification_assignments.id'], name=op.f('fk_verification_assignments_previous_assignment_id_verification_assignments')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_verification_assignments_project_id_projects')),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_verification_assignments_proposed_by_users')),
    sa.ForeignKeyConstraint(['vvb_organization_id'], ['organizations.id'], name=op.f('fk_verification_assignments_vvb_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_assignments')),
    sa.UniqueConstraint('assignment_code', name=op.f('uq_verification_assignments_assignment_code'))
    )
    op.create_index(op.f('ix_verification_assignments_project_id'), 'verification_assignments', ['project_id'], unique=False)
    op.create_index('ix_verification_assignments_vvb', 'verification_assignments', ['vvb_organization_id', 'status'], unique=False)
    op.create_index('uq_verification_assignments_open', 'verification_assignments', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status IN ('PROPOSED', 'ACCEPTED')"))
    op.create_table('verification_submissions',
    sa.Column('submission_code', sa.Unicode(length=20), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('readiness_review_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_run_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_report_id', sa.Uuid(), nullable=False),
    sa.Column('manifest_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('superseded_by_submission_id', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_verification_submissions_environment')),
    sa.CheckConstraint("status IN ('SUBMITTED', 'SUPERSEDED', 'INVALIDATED')", name=op.f('ck_verification_submissions_status')),
    sa.ForeignKeyConstraint(['assignment_id'], ['verification_assignments.id'], name=op.f('fk_verification_submissions_assignment_id_verification_assignments')),
    sa.ForeignKeyConstraint(['calculation_report_id'], ['calculation_reports.id'], name=op.f('fk_verification_submissions_calculation_report_id_calculation_reports')),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['calculation_runs.id'], name=op.f('fk_verification_submissions_calculation_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_verification_submissions_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_verification_submissions_project_id_projects')),
    sa.ForeignKeyConstraint(['readiness_review_id'], ['calculation_readiness_reviews.id'], name=op.f('fk_verification_submissions_readiness_review_id_calculation_readiness_reviews')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_verification_submissions_submitted_by_users')),
    sa.ForeignKeyConstraint(['superseded_by_submission_id'], ['verification_submissions.id'], name=op.f('fk_verification_submissions_superseded_by_submission_id_verification_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_submissions')),
    sa.UniqueConstraint('assignment_id', 'seq', name=op.f('uq_verification_submissions_assignment_id_seq')),
    sa.UniqueConstraint('submission_code', name=op.f('uq_verification_submissions_submission_code'))
    )
    op.create_index(op.f('ix_verification_submissions_assignment_id'), 'verification_submissions', ['assignment_id'], unique=False)
    op.create_index('uq_verification_submissions_current', 'verification_submissions', ['assignment_id'], unique=True, mssql_where=sa.text("status = 'SUBMITTED'"))
    op.create_table('verification_decisions',
    sa.Column('decision_code', sa.Unicode(length=20), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('vvb_organization_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Unicode(length=15), nullable=False),
    sa.Column('verified_quantity', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('verified_quantity_unit', sa.Unicode(length=40), nullable=True),
    sa.Column('rationale', sa.Unicode(length=4000), nullable=False),
    sa.Column('report_document_id', sa.Uuid(), nullable=False),
    sa.Column('report_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('decided_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('superseded_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_verification_decisions_environment')),
    sa.CheckConstraint("outcome IN ('VERIFIED', 'NOT_VERIFIED')", name=op.f('ck_verification_decisions_outcome')),
    sa.CheckConstraint("status IN ('CURRENT', 'SUPERSEDED')", name=op.f('ck_verification_decisions_status')),
    sa.CheckConstraint('(verified_quantity IS NULL AND verified_quantity_unit IS NULL) OR (verified_quantity IS NOT NULL AND verified_quantity_unit IS NOT NULL)', name=op.f('ck_verification_decisions_quantity_unit')),
    sa.ForeignKeyConstraint(['assignment_id'], ['verification_assignments.id'], name=op.f('fk_verification_decisions_assignment_id_verification_assignments')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_verification_decisions_decided_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_verification_decisions_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_verification_decisions_project_id_projects')),
    sa.ForeignKeyConstraint(['report_document_id'], ['documents.id'], name=op.f('fk_verification_decisions_report_document_id_documents')),
    sa.ForeignKeyConstraint(['submission_id'], ['verification_submissions.id'], name=op.f('fk_verification_decisions_submission_id_verification_submissions')),
    sa.ForeignKeyConstraint(['vvb_organization_id'], ['organizations.id'], name=op.f('fk_verification_decisions_vvb_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_decisions')),
    sa.UniqueConstraint('decision_code', name=op.f('uq_verification_decisions_decision_code')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_verification_decisions_submission_id'))
    )
    op.create_index(op.f('ix_verification_decisions_assignment_id'), 'verification_decisions', ['assignment_id'], unique=False)
    op.create_index('uq_verification_decisions_current', 'verification_decisions', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status = 'CURRENT'"))
    op.create_table('verification_findings',
    sa.Column('finding_code', sa.Unicode(length=20), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Unicode(length=20), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.Unicode(length=4000), nullable=False),
    sa.Column('target_type', sa.Unicode(length=20), nullable=False),
    sa.Column('target_ref', sa.Unicode(length=80), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('raised_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('response_text', sa.Unicode(length=4000), nullable=True),
    sa.Column('response_document_id', sa.Uuid(), nullable=True),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('responded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closure_note', sa.Unicode(length=2000), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('OBSERVATION', 'NON_CONFORMITY', 'CLARIFICATION', 'MISSING_EVIDENCE', 'CALCULATION_ISSUE', 'METHODOLOGY_ISSUE')", name=op.f('ck_verification_findings_category')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_verification_findings_environment')),
    sa.CheckConstraint("status IN ('OPEN', 'RESPONDED', 'CLOSED')", name=op.f('ck_verification_findings_status')),
    sa.CheckConstraint("target_type IN ('SUBMISSION', 'MONITORING_PERIOD', 'CALCULATION_RUN', 'INPUT', 'OUTPUT', 'LAB_RESULT', 'MRV_EVIDENCE', 'DATASET', 'CALCULATION_REPORT', 'METHODOLOGY', 'DOCUMENT')", name=op.f('ck_verification_findings_target_type')),
    sa.ForeignKeyConstraint(['assignment_id'], ['verification_assignments.id'], name=op.f('fk_verification_findings_assignment_id_verification_assignments')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_verification_findings_closed_by_users')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_verification_findings_raised_by_users')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_verification_findings_responded_by_users')),
    sa.ForeignKeyConstraint(['response_document_id'], ['documents.id'], name=op.f('fk_verification_findings_response_document_id_documents')),
    sa.ForeignKeyConstraint(['submission_id'], ['verification_submissions.id'], name=op.f('fk_verification_findings_submission_id_verification_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_findings')),
    sa.UniqueConstraint('finding_code', name=op.f('uq_verification_findings_finding_code'))
    )
    op.create_index(op.f('ix_verification_findings_assignment_id'), 'verification_findings', ['assignment_id'], unique=False)
    op.create_index('ix_verification_findings_submission_status', 'verification_findings', ['submission_id', 'status'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('action_code', sa.Unicode(length=20), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Unicode(length=4000), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('response_text', sa.Unicode(length=4000), nullable=True),
    sa.Column('response_document_id', sa.Uuid(), nullable=True),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('responded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('review_note', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_corrective_actions_environment')),
    sa.CheckConstraint("status IN ('REQUESTED', 'RESPONDED', 'ACCEPTED', 'CANCELLED')", name=op.f('ck_corrective_actions_status')),
    sa.ForeignKeyConstraint(['assignment_id'], ['verification_assignments.id'], name=op.f('fk_corrective_actions_assignment_id_verification_assignments')),
    sa.ForeignKeyConstraint(['finding_id'], ['verification_findings.id'], name=op.f('fk_corrective_actions_finding_id_verification_findings')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_corrective_actions_requested_by_users')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_corrective_actions_responded_by_users')),
    sa.ForeignKeyConstraint(['response_document_id'], ['documents.id'], name=op.f('fk_corrective_actions_response_document_id_documents')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_corrective_actions_reviewed_by_users')),
    sa.ForeignKeyConstraint(['submission_id'], ['verification_submissions.id'], name=op.f('fk_corrective_actions_submission_id_verification_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_actions')),
    sa.UniqueConstraint('action_code', name=op.f('uq_corrective_actions_action_code'))
    )
    op.create_index(op.f('ix_corrective_actions_finding_id'), 'corrective_actions', ['finding_id'], unique=False)
    op.create_index('ix_corrective_actions_submission_status', 'corrective_actions', ['submission_id', 'status'], unique=False)
    op.create_table('verification_finding_events',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.Unicode(length=20), nullable=False),
    sa.Column('from_status', sa.Unicode(length=12), nullable=True),
    sa.Column('to_status', sa.Unicode(length=12), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_side', sa.Unicode(length=10), nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('note', sa.Unicode(length=4000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_verification_finding_events_actor_id_users')),
    sa.ForeignKeyConstraint(['actor_org_id'], ['organizations.id'], name=op.f('fk_verification_finding_events_actor_org_id_organizations')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_verification_finding_events_document_id_documents')),
    sa.ForeignKeyConstraint(['finding_id'], ['verification_findings.id'], name=op.f('fk_verification_finding_events_finding_id_verification_findings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_finding_events')),
    sa.UniqueConstraint('finding_id', 'seq', name=op.f('uq_verification_finding_events_finding_id_seq'))
    )
    op.create_index(op.f('ix_verification_finding_events_finding_id'), 'verification_finding_events', ['finding_id'], unique=False)
    op.create_table('corrective_action_events',
    sa.Column('corrective_action_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.Unicode(length=20), nullable=False),
    sa.Column('from_status', sa.Unicode(length=12), nullable=True),
    sa.Column('to_status', sa.Unicode(length=12), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_org_id', sa.Uuid(), nullable=False),
    sa.Column('actor_side', sa.Unicode(length=10), nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('note', sa.Unicode(length=4000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_corrective_action_events_actor_id_users')),
    sa.ForeignKeyConstraint(['actor_org_id'], ['organizations.id'], name=op.f('fk_corrective_action_events_actor_org_id_organizations')),
    sa.ForeignKeyConstraint(['corrective_action_id'], ['corrective_actions.id'], name=op.f('fk_corrective_action_events_corrective_action_id_corrective_actions')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_corrective_action_events_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_action_events')),
    sa.UniqueConstraint('corrective_action_id', 'seq', name=op.f('uq_corrective_action_events_corrective_action_id_seq'))
    )
    op.create_index(op.f('ix_corrective_action_events_corrective_action_id'), 'corrective_action_events', ['corrective_action_id'], unique=False)
    # ### end Alembic commands ###

    # ---- hand-written: sequences, documents categories, append-only / immutability triggers
    for seq in ("seq_verification_assignment_code", "seq_verification_submission_code", "seq_verification_finding_code", "seq_corrective_action_code",
                "seq_verification_decision_code"):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'OTHER')")
    for table in ("verification_finding_events", "corrective_action_events"):
        op.execute(f"""
CREATE TRIGGER trg_{table}_append_only ON dbo.{table}
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, '{table} is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_verification_assignments_immutable ON dbo.verification_assignments
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'verification_assignments: assignments are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.assignment_code, i.project_id, i.monitoring_period_id, i.vvb_organization_id, i.previous_assignment_id, i.notes, i.proposed_by, i.proposed_at, i.environment EXCEPT SELECT d.assignment_code, d.project_id, d.monitoring_period_id, d.vvb_organization_id, d.previous_assignment_id, d.notes, d.proposed_by, d.proposed_at, d.environment)
           OR (d.coi_declaration IS NOT NULL AND EXISTS (SELECT i.accepted_by, i.accepted_at, i.coi_declaration, i.coi_declared_by, i.coi_declared_at EXCEPT SELECT d.accepted_by, d.accepted_at, d.coi_declaration, d.coi_declared_by, d.coi_declared_at))
           OR (d.status IN ('COMPLETED', 'DECLINED', 'WITHDRAWN', 'TERMINATED') AND EXISTS (SELECT i.assignment_code, i.project_id, i.monitoring_period_id, i.vvb_organization_id, i.previous_assignment_id, i.notes, i.proposed_by, i.proposed_at, i.environment, i.status, i.accepted_by, i.accepted_at, i.coi_declaration, i.coi_declared_by, i.coi_declared_at, i.completed_at, i.closed_by, i.closed_at, i.closed_side, i.closed_reason EXCEPT SELECT d.assignment_code, d.project_id, d.monitoring_period_id, d.vvb_organization_id, d.previous_assignment_id, d.notes, d.proposed_by, d.proposed_at, d.environment, d.status, d.accepted_by, d.accepted_at, d.coi_declaration, d.coi_declared_by, d.coi_declared_at, d.completed_at, d.closed_by, d.closed_at, d.closed_side, d.closed_reason)))
    BEGIN;
        THROW 51000, 'verification_assignments: identity and the COI declaration are immutable; a closed assignment is final (no reactivation).', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_verification_submissions_immutable ON dbo.verification_submissions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'verification_submissions: submissions are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.submission_code, i.assignment_id, i.seq, i.project_id, i.monitoring_period_id, i.readiness_review_id, i.calculation_run_id, i.calculation_report_id, i.manifest_sha256, i.submitted_by, i.submitted_at, i.environment EXCEPT SELECT d.submission_code, d.assignment_id, d.seq, d.project_id, d.monitoring_period_id, d.readiness_review_id, d.calculation_run_id, d.calculation_report_id, d.manifest_sha256, d.submitted_by, d.submitted_at, d.environment)
           OR (d.status <> 'SUBMITTED' AND EXISTS (SELECT i.status, i.closed_at, i.closed_reason EXCEPT SELECT d.status, d.closed_at, d.closed_reason))
           OR (d.superseded_by_submission_id IS NOT NULL AND (i.superseded_by_submission_id IS NULL OR i.superseded_by_submission_id <> d.superseded_by_submission_id)))
    BEGIN;
        THROW 51000, 'verification_submissions: a submitted package is never mutated; SUPERSEDED / INVALIDATED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_verification_findings_immutable ON dbo.verification_findings
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'verification_findings: findings are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.finding_code, i.assignment_id, i.submission_id, i.category, i.blocking, i.title, i.description, i.target_type, i.target_ref, i.raised_by, i.raised_at, i.environment EXCEPT SELECT d.finding_code, d.assignment_id, d.submission_id, d.category, d.blocking, d.title, d.description, d.target_type, d.target_ref, d.raised_by, d.raised_at, d.environment))
    BEGIN;
        THROW 51000, 'verification_findings: identity, category, target and original text are immutable.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_corrective_actions_immutable ON dbo.corrective_actions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'corrective_actions: corrective actions are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.action_code, i.finding_id, i.submission_id, i.assignment_id, i.description, i.due_date, i.requested_by, i.requested_at, i.environment EXCEPT SELECT d.action_code, d.finding_id, d.submission_id, d.assignment_id, d.description, d.due_date, d.requested_by, d.requested_at, d.environment)
           OR (d.status IN ('ACCEPTED', 'CANCELLED') AND EXISTS (SELECT i.action_code, i.finding_id, i.submission_id, i.assignment_id, i.description, i.due_date, i.requested_by, i.requested_at, i.environment, i.status, i.response_text, i.response_document_id, i.responded_by, i.responded_at, i.reviewed_by, i.reviewed_at, i.review_note EXCEPT SELECT d.action_code, d.finding_id, d.submission_id, d.assignment_id, d.description, d.due_date, d.requested_by, d.requested_at, d.environment, d.status, d.response_text, d.response_document_id, d.responded_by, d.responded_at, d.reviewed_by, d.reviewed_at, d.review_note)))
    BEGIN;
        THROW 51000, 'corrective_actions: identity and request are immutable; ACCEPTED / CANCELLED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_verification_decisions_immutable ON dbo.verification_decisions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'verification_decisions: decisions are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.decision_code, i.assignment_id, i.submission_id, i.project_id, i.monitoring_period_id, i.vvb_organization_id, i.outcome, i.verified_quantity, i.verified_quantity_unit, i.rationale, i.report_document_id, i.report_sha256, i.manifest_sha256, i.decided_by, i.decided_at, i.environment EXCEPT SELECT d.decision_code, d.assignment_id, d.submission_id, d.project_id, d.monitoring_period_id, d.vvb_organization_id, d.outcome, d.verified_quantity, d.verified_quantity_unit, d.rationale, d.report_document_id, d.report_sha256, d.manifest_sha256, d.decided_by, d.decided_at, d.environment)
           OR (d.status = 'SUPERSEDED' AND EXISTS (SELECT i.status, i.superseded_at, i.superseded_reason EXCEPT SELECT d.status, d.superseded_at, d.superseded_reason)))
    BEGIN;
        THROW 51000, 'verification_decisions: a recorded decision is immutable (only CURRENT -> SUPERSEDED).', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: Phase 8B history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.verification_assignments) OR EXISTS (SELECT 1 FROM dbo.verification_submissions)
   OR EXISTS (SELECT 1 FROM dbo.verification_findings) OR EXISTS (SELECT 1 FROM dbo.verification_finding_events)
   OR EXISTS (SELECT 1 FROM dbo.corrective_actions) OR EXISTS (SELECT 1 FROM dbo.corrective_action_events)
   OR EXISTS (SELECT 1 FROM dbo.verification_decisions)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE'))
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 8B verification assignments, submissions, findings, corrective actions, decisions or verification documents exist.', 1;
END""")
    for trigger in ("trg_verification_decisions_immutable", "trg_corrective_actions_immutable", "trg_verification_findings_immutable",
                    "trg_verification_submissions_immutable", "trg_verification_assignments_immutable", "trg_corrective_action_events_append_only",
                    "trg_verification_finding_events_append_only"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'OTHER')")
    for seq in ("seq_verification_assignment_code", "seq_verification_submission_code", "seq_verification_finding_code", "seq_corrective_action_code",
                "seq_verification_decision_code"):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrective_action_events_corrective_action_id'), table_name='corrective_action_events')
    op.drop_table('corrective_action_events')
    op.drop_index(op.f('ix_verification_finding_events_finding_id'), table_name='verification_finding_events')
    op.drop_table('verification_finding_events')
    op.drop_index('ix_corrective_actions_submission_status', table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_finding_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index('ix_verification_findings_submission_status', table_name='verification_findings')
    op.drop_index(op.f('ix_verification_findings_assignment_id'), table_name='verification_findings')
    op.drop_table('verification_findings')
    op.drop_index('uq_verification_decisions_current', table_name='verification_decisions', mssql_where=sa.text("status = 'CURRENT'"))
    op.drop_index(op.f('ix_verification_decisions_assignment_id'), table_name='verification_decisions')
    op.drop_table('verification_decisions')
    op.drop_index('uq_verification_submissions_current', table_name='verification_submissions', mssql_where=sa.text("status = 'SUBMITTED'"))
    op.drop_index(op.f('ix_verification_submissions_assignment_id'), table_name='verification_submissions')
    op.drop_table('verification_submissions')
    op.drop_index('uq_verification_assignments_open', table_name='verification_assignments', mssql_where=sa.text("status IN ('PROPOSED', 'ACCEPTED')"))
    op.drop_index('ix_verification_assignments_vvb', table_name='verification_assignments')
    op.drop_index(op.f('ix_verification_assignments_project_id'), table_name='verification_assignments')
    op.drop_table('verification_assignments')
    # ### end Alembic commands ###
