"""Phase 9A — registry submission & credit issuance (no inventory, ownership, reservation, transfer or retirement).

7 tables (registry accounts, project registrations, registry submissions, append-only registry events, credit issuances, credit
batches, credit serial ranges), sequences RREG / RSUB / ISS / CB, filtered unique indexes (one open / accepted registry submission per
monitoring period across registries; registry + external submission / issuance / project ID; registry + serial start / end of current
ranges; idempotency keys), the documents categories REGISTRY_SUBMISSION / REGISTRY_RESPONSE / ISSUANCE_STATEMENT (removed on downgrade only
when unused) and triggers: registry events append-only; identities and recorded registry facts never change; the frozen snapshot, its
hash, the idempotency key and external references are fixed once set; final states are frozen; issuances, batches and serial ranges
change only along their lifecycle (status / current flag); nothing is deleted. No Phase 1–8B data is changed or backfilled.

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-03 14:26:49.791306
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0013'
down_revision: str | None = '0012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_accounts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('external_account_id', sa.Unicode(length=120), nullable=False),
    sa.Column('label', sa.Unicode(length=200), nullable=False),
    sa.Column('adapter_code', sa.Unicode(length=30), nullable=False),
    sa.Column('credit_unit', sa.Unicode(length=40), nullable=True),
    sa.Column('verified_unit_equivalent', sa.Unicode(length=40), nullable=True),
    sa.Column('document_checklist', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_registry_accounts_environment')),
    sa.CheckConstraint("status <> 'CLOSED' OR closed_reason IS NOT NULL", name=op.f('ck_registry_accounts_closed_reason')),
    sa.CheckConstraint("status IN ('ACTIVE', 'CLOSED')", name=op.f('ck_registry_accounts_status')),
    sa.CheckConstraint('(credit_unit IS NULL AND verified_unit_equivalent IS NULL) OR (credit_unit IS NOT NULL AND verified_unit_equivalent IS NOT NULL)', name=op.f('ck_registry_accounts_unit_equivalence')),
    sa.CheckConstraint('document_checklist IS NULL OR ISJSON(document_checklist) = 1', name=op.f('ck_registry_accounts_checklist_json')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_registry_accounts_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_registry_accounts_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_registry_accounts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_registry_accounts_registry_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_accounts'))
    )
    op.create_index(op.f('ix_registry_accounts_organization_id'), 'registry_accounts', ['organization_id'], unique=False)
    op.create_index('uq_registry_accounts_external', 'registry_accounts', ['registry_organization_id', 'external_account_id'], unique=True)
    op.create_table('registry_project_registrations',
    sa.Column('registration_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('external_project_id', sa.Unicode(length=120), nullable=True),
    sa.Column('registered_on', sa.Date(), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('response_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_registry_project_registrations_environment')),
    sa.CheckConstraint("status <> 'REGISTERED' OR (external_project_id IS NOT NULL AND evidence_document_id IS NOT NULL AND recorded_by IS NOT NULL)", name=op.f('ck_registry_project_registrations_registered_evidence')),
    sa.CheckConstraint("status <> 'REJECTED' OR (response_reason IS NOT NULL AND evidence_document_id IS NOT NULL)", name=op.f('ck_registry_project_registrations_rejected_evidence')),
    sa.CheckConstraint("status IN ('PENDING', 'REGISTERED', 'REJECTED')", name=op.f('ck_registry_project_registrations_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_registry_project_registrations_created_by_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_registry_project_registrations_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_registry_project_registrations_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_registry_project_registrations_recorded_by_users')),
    sa.ForeignKeyConstraint(['registry_account_id'], ['registry_accounts.id'], name=op.f('fk_registry_project_registrations_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_registry_project_registrations_registry_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_project_registrations')),
    sa.UniqueConstraint('registration_code', name=op.f('uq_registry_project_registrations_registration_code'))
    )
    op.create_index(op.f('ix_registry_project_registrations_project_id'), 'registry_project_registrations', ['project_id'], unique=False)
    op.create_index('uq_registry_registrations_external', 'registry_project_registrations', ['registry_organization_id', 'external_project_id'], unique=True, mssql_where=sa.text('external_project_id IS NOT NULL'))
    op.create_index('uq_registry_registrations_open', 'registry_project_registrations', ['project_id', 'registry_organization_id'], unique=True, mssql_where=sa.text("status IN ('PENDING', 'REGISTERED')"))
    op.create_table('registry_submissions',
    sa.Column('submission_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('verification_decision_id', sa.Uuid(), nullable=False),
    sa.Column('verification_submission_id', sa.Uuid(), nullable=False),
    sa.Column('previous_submission_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=25), nullable=False),
    sa.Column('snapshot', sa.UnicodeText(), nullable=True),
    sa.Column('snapshot_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('idempotency_key', sa.Unicode(length=64), nullable=True),
    sa.Column('client_request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('external_submission_id', sa.Unicode(length=120), nullable=True),
    sa.Column('submission_evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('response_document_id', sa.Uuid(), nullable=True),
    sa.Column('response_payload_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('external_response_ref', sa.Unicode(length=120), nullable=True),
    sa.Column('response_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('frozen_by', sa.Uuid(), nullable=True),
    sa.Column('frozen_at', mssql.DATETIME2(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('response_by', sa.Uuid(), nullable=True),
    sa.Column('response_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('closed_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_registry_submissions_environment')),
    sa.CheckConstraint("status <> 'REJECTED' OR response_reason IS NOT NULL", name=op.f('ck_registry_submissions_rejection_reason')),
    sa.CheckConstraint("status IN ('DRAFT', 'CANCELLED', 'INVALIDATED') OR (snapshot IS NOT NULL AND snapshot_sha256 IS NOT NULL AND idempotency_key IS NOT NULL)", name=op.f('ck_registry_submissions_frozen_snapshot')),
    sa.CheckConstraint("status IN ('DRAFT', 'FROZEN', 'SUBMITTING', 'SUBMISSION_UNCONFIRMED', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'CANCELLED', 'INVALIDATED')", name=op.f('ck_registry_submissions_status')),
    sa.CheckConstraint("status NOT IN ('ACCEPTED', 'REJECTED') OR response_document_id IS NOT NULL OR response_payload_sha256 IS NOT NULL", name=op.f('ck_registry_submissions_response_evidence')),
    sa.CheckConstraint("status NOT IN ('SUBMITTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN') OR external_submission_id IS NOT NULL", name=op.f('ck_registry_submissions_external_reference')),
    sa.CheckConstraint("status NOT IN ('WITHDRAWN', 'CANCELLED', 'INVALIDATED') OR closed_reason IS NOT NULL", name=op.f('ck_registry_submissions_closed_reason')),
    sa.CheckConstraint('snapshot IS NULL OR ISJSON(snapshot) = 1', name=op.f('ck_registry_submissions_snapshot_json')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_registry_submissions_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_registry_submissions_created_by_users')),
    sa.ForeignKeyConstraint(['frozen_by'], ['users.id'], name=op.f('fk_registry_submissions_frozen_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_registry_submissions_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['previous_submission_id'], ['registry_submissions.id'], name=op.f('fk_registry_submissions_previous_submission_id_registry_submissions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_registry_submissions_project_id_projects')),
    sa.ForeignKeyConstraint(['registration_id'], ['registry_project_registrations.id'], name=op.f('fk_registry_submissions_registration_id_registry_project_registrations')),
    sa.ForeignKeyConstraint(['registry_account_id'], ['registry_accounts.id'], name=op.f('fk_registry_submissions_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_registry_submissions_registry_organization_id_organizations')),
    sa.ForeignKeyConstraint(['response_by'], ['users.id'], name=op.f('fk_registry_submissions_response_by_users')),
    sa.ForeignKeyConstraint(['response_document_id'], ['documents.id'], name=op.f('fk_registry_submissions_response_document_id_documents')),
    sa.ForeignKeyConstraint(['submission_evidence_document_id'], ['documents.id'], name=op.f('fk_registry_submissions_submission_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_registry_submissions_submitted_by_users')),
    sa.ForeignKeyConstraint(['verification_decision_id'], ['verification_decisions.id'], name=op.f('fk_registry_submissions_verification_decision_id_verification_decisions')),
    sa.ForeignKeyConstraint(['verification_submission_id'], ['verification_submissions.id'], name=op.f('fk_registry_submissions_verification_submission_id_verification_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_submissions')),
    sa.UniqueConstraint('submission_code', name=op.f('uq_registry_submissions_submission_code'))
    )
    op.create_index(op.f('ix_registry_submissions_project_id'), 'registry_submissions', ['project_id'], unique=False)
    op.create_index('uq_registry_submissions_external', 'registry_submissions', ['registry_organization_id', 'external_submission_id'], unique=True, mssql_where=sa.text('external_submission_id IS NOT NULL'))
    op.create_index('uq_registry_submissions_idempotency', 'registry_submissions', ['idempotency_key'], unique=True, mssql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('uq_registry_submissions_open_period', 'registry_submissions', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status IN ('DRAFT', 'FROZEN', 'SUBMITTING', 'SUBMISSION_UNCONFIRMED', 'SUBMITTED', 'ACCEPTED')"))
    op.create_index('uq_registry_submissions_request_key', 'registry_submissions', ['client_request_key'], unique=True, mssql_where=sa.text('client_request_key IS NOT NULL'))
    op.create_table('credit_issuances',
    sa.Column('issuance_code', sa.Unicode(length=20), nullable=False),
    sa.Column('registry_submission_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('verification_decision_id', sa.Uuid(), nullable=False),
    sa.Column('external_issuance_id', sa.Unicode(length=120), nullable=False),
    sa.Column('issuance_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('unit', sa.Unicode(length=40), nullable=False),
    sa.Column('source', sa.Unicode(length=10), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('api_response_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('corrects_issuance_id', sa.Uuid(), nullable=True),
    sa.Column('corrected_by_issuance_id', sa.Uuid(), nullable=True),
    sa.Column('correction_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('client_request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('voided_by', sa.Uuid(), nullable=True),
    sa.Column('voided_at', mssql.DATETIME2(), nullable=True),
    sa.Column('void_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('cancelled_by', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', mssql.DATETIME2(), nullable=True),
    sa.Column('cancel_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('cancel_document_id', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_issuances_environment')),
    sa.CheckConstraint("source IN ('MANUAL', 'API')", name=op.f('ck_credit_issuances_source')),
    sa.CheckConstraint("status <> 'CANCELLED' OR (cancel_reason IS NOT NULL AND cancel_document_id IS NOT NULL)", name=op.f('ck_credit_issuances_cancel_evidence')),
    sa.CheckConstraint("status <> 'VOIDED' OR void_reason IS NOT NULL", name=op.f('ck_credit_issuances_void_reason')),
    sa.CheckConstraint("status IN ('RECORDED', 'CONFIRMED', 'VOIDED', 'CORRECTED', 'CANCELLED')", name=op.f('ck_credit_issuances_status')),
    sa.CheckConstraint("status NOT IN ('CONFIRMED', 'CORRECTED', 'CANCELLED') OR confirmed_by IS NOT NULL", name=op.f('ck_credit_issuances_confirmed')),
    sa.CheckConstraint('confirmed_by IS NULL OR confirmed_by <> recorded_by', name=op.f('ck_credit_issuances_dual_control')),
    sa.CheckConstraint('evidence_document_id IS NOT NULL OR api_response_sha256 IS NOT NULL', name=op.f('ck_credit_issuances_evidence')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_issuances_quantity_positive')),
    sa.ForeignKeyConstraint(['cancel_document_id'], ['documents.id'], name=op.f('fk_credit_issuances_cancel_document_id_documents')),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name=op.f('fk_credit_issuances_cancelled_by_users')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_credit_issuances_confirmed_by_users')),
    sa.ForeignKeyConstraint(['corrected_by_issuance_id'], ['credit_issuances.id'], name=op.f('fk_credit_issuances_corrected_by_issuance_id_credit_issuances')),
    sa.ForeignKeyConstraint(['corrects_issuance_id'], ['credit_issuances.id'], name=op.f('fk_credit_issuances_corrects_issuance_id_credit_issuances')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_credit_issuances_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_credit_issuances_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_credit_issuances_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_credit_issuances_recorded_by_users')),
    sa.ForeignKeyConstraint(['registry_account_id'], ['registry_accounts.id'], name=op.f('fk_credit_issuances_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_credit_issuances_registry_organization_id_organizations')),
    sa.ForeignKeyConstraint(['registry_submission_id'], ['registry_submissions.id'], name=op.f('fk_credit_issuances_registry_submission_id_registry_submissions')),
    sa.ForeignKeyConstraint(['verification_decision_id'], ['verification_decisions.id'], name=op.f('fk_credit_issuances_verification_decision_id_verification_decisions')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_credit_issuances_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_issuances')),
    sa.UniqueConstraint('issuance_code', name=op.f('uq_credit_issuances_issuance_code'))
    )
    op.create_index(op.f('ix_credit_issuances_project_id'), 'credit_issuances', ['project_id'], unique=False)
    op.create_index('ix_credit_issuances_submission', 'credit_issuances', ['registry_submission_id', 'status'], unique=False)
    op.create_index('uq_credit_issuances_external', 'credit_issuances', ['registry_organization_id', 'external_issuance_id'], unique=True, mssql_where=sa.text("status = 'CONFIRMED'"))
    op.create_index('uq_credit_issuances_request_key', 'credit_issuances', ['client_request_key'], unique=True, mssql_where=sa.text('client_request_key IS NOT NULL'))
    op.create_table('credit_batches',
    sa.Column('batch_code', sa.Unicode(length=20), nullable=False),
    sa.Column('issuance_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('verification_decision_id', sa.Uuid(), nullable=False),
    sa.Column('methodology_version_id', sa.Uuid(), nullable=True),
    sa.Column('standard_id', sa.Uuid(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('vintage', sa.Unicode(length=60), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('unit', sa.Unicode(length=40), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_batches_environment')),
    sa.CheckConstraint("status IN ('RECORDED', 'ISSUED', 'VOIDED', 'SUPERSEDED', 'CANCELLED')", name=op.f('ck_credit_batches_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_batches_quantity_positive')),
    sa.ForeignKeyConstraint(['issuance_id'], ['credit_issuances.id'], name=op.f('fk_credit_batches_issuance_id_credit_issuances')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], name=op.f('fk_credit_batches_methodology_version_id_methodology_versions')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_credit_batches_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_credit_batches_project_id_projects')),
    sa.ForeignKeyConstraint(['registry_account_id'], ['registry_accounts.id'], name=op.f('fk_credit_batches_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_credit_batches_registry_organization_id_organizations')),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name=op.f('fk_credit_batches_standard_id_standards')),
    sa.ForeignKeyConstraint(['verification_decision_id'], ['verification_decisions.id'], name=op.f('fk_credit_batches_verification_decision_id_verification_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_batches')),
    sa.UniqueConstraint('batch_code', name=op.f('uq_credit_batches_batch_code'))
    )
    op.create_index(op.f('ix_credit_batches_issuance_id'), 'credit_batches', ['issuance_id'], unique=False)
    op.create_index('ix_credit_batches_project_period', 'credit_batches', ['project_id', 'monitoring_period_id'], unique=False)
    op.create_table('registry_events',
    sa.Column('registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=True),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('issuance_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Unicode(length=30), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('adapter_code', sa.Unicode(length=30), nullable=False),
    sa.Column('idempotency_key', sa.Unicode(length=64), nullable=True),
    sa.Column('external_ref', sa.Unicode(length=120), nullable=True),
    sa.Column('payload_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('outcome', sa.Unicode(length=40), nullable=True),
    sa.Column('checklist_item', sa.Unicode(length=60), nullable=True),
    sa.Column('note', sa.Unicode(length=2000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_registry_events_environment')),
    sa.CheckConstraint("event_type IN ('SUBMIT_ATTEMPT', 'SUBMIT_CONFIRMED', 'TIMEOUT', 'STATUS_QUERIED', 'QUERY_RECEIVED', 'RESPONSE_RECORDED', 'ERROR', 'RECONCILED', 'MISMATCH', 'SOURCE_SUPERSEDED', 'DOCUMENT_ATTACHED', 'EXTERNAL_REFERENCE_RECORDED')", name=op.f('ck_registry_events_event_type')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_registry_events_actor_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_registry_events_document_id_documents')),
    sa.ForeignKeyConstraint(['issuance_id'], ['credit_issuances.id'], name=op.f('fk_registry_events_issuance_id_credit_issuances')),
    sa.ForeignKeyConstraint(['registration_id'], ['registry_project_registrations.id'], name=op.f('fk_registry_events_registration_id_registry_project_registrations')),
    sa.ForeignKeyConstraint(['registry_account_id'], ['registry_accounts.id'], name=op.f('fk_registry_events_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['submission_id'], ['registry_submissions.id'], name=op.f('fk_registry_events_submission_id_registry_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_events'))
    )
    op.create_index('ix_registry_events_submission', 'registry_events', ['submission_id', 'occurred_at'], unique=False)
    op.create_table('credit_serial_ranges',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('serial_start', sa.Unicode(length=200), nullable=True),
    sa.Column('serial_end', sa.Unicode(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('parsed_series', sa.Unicode(length=120), nullable=True),
    sa.Column('parsed_start', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('parsed_end', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_serial_ranges_environment')),
    sa.CheckConstraint('(parsed_series IS NULL AND parsed_start IS NULL AND parsed_end IS NULL) OR (parsed_series IS NOT NULL AND parsed_start IS NOT NULL AND parsed_end IS NOT NULL AND parsed_end >= parsed_start)', name=op.f('ck_credit_serial_ranges_parsed_bounds')),
    sa.CheckConstraint('(serial_start IS NULL AND serial_end IS NULL) OR (serial_start IS NOT NULL AND serial_end IS NOT NULL)', name=op.f('ck_credit_serial_ranges_serial_pair')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_serial_ranges_quantity_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_serial_ranges_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_credit_serial_ranges_registry_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_serial_ranges'))
    )
    op.create_index(op.f('ix_credit_serial_ranges_batch_id'), 'credit_serial_ranges', ['batch_id'], unique=False)
    op.create_index('uq_credit_serial_ranges_end', 'credit_serial_ranges', ['registry_organization_id', 'serial_end'], unique=True, mssql_where=sa.text('serial_end IS NOT NULL AND is_current = 1'))
    op.create_index('uq_credit_serial_ranges_start', 'credit_serial_ranges', ['registry_organization_id', 'serial_start'], unique=True, mssql_where=sa.text('serial_start IS NOT NULL AND is_current = 1'))
    # ### end Alembic commands ###

    # ---- hand-written: sequences, documents categories, append-only / immutability triggers
    for seq in ("seq_registry_registration_code", "seq_registry_submission_code", "seq_credit_issuance_code", "seq_credit_batch_code"):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents',
                               "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_registry_events_append_only ON dbo.registry_events
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'registry_events is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_registry_accounts_immutable ON dbo.registry_accounts
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'registry_accounts: registry accounts are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.organization_id, i.registry_organization_id, i.external_account_id, i.adapter_code, i.created_by, i.created_at, i.environment EXCEPT SELECT d.organization_id, d.registry_organization_id, d.external_account_id, d.adapter_code, d.created_by, d.created_at, d.environment)
           OR (d.status = 'CLOSED' AND EXISTS (SELECT i.organization_id, i.registry_organization_id, i.external_account_id, i.adapter_code, i.created_by, i.created_at, i.environment, i.label, i.credit_unit, i.verified_unit_equivalent, i.document_checklist, i.status, i.closed_by, i.closed_at, i.closed_reason EXCEPT SELECT d.organization_id, d.registry_organization_id, d.external_account_id, d.adapter_code, d.created_by, d.created_at, d.environment, d.label, d.credit_unit, d.verified_unit_equivalent, d.document_checklist, d.status, d.closed_by, d.closed_at, d.closed_reason)))
    BEGIN;
        THROW 51000, 'registry_accounts: identity is immutable; a closed account is final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_registry_registrations_immutable ON dbo.registry_project_registrations
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'registry_project_registrations: registrations are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.registration_code, i.project_id, i.registry_account_id, i.registry_organization_id, i.notes, i.created_by, i.created_at, i.environment EXCEPT SELECT d.registration_code, d.project_id, d.registry_account_id, d.registry_organization_id, d.notes, d.created_by, d.created_at, d.environment)
           OR (d.status IN ('REGISTERED', 'REJECTED') AND EXISTS (SELECT i.registration_code, i.project_id, i.registry_account_id, i.registry_organization_id, i.notes, i.created_by, i.created_at, i.environment, i.status, i.external_project_id, i.registered_on, i.evidence_document_id, i.response_reason, i.recorded_by, i.recorded_at EXCEPT SELECT d.registration_code, d.project_id, d.registry_account_id, d.registry_organization_id, d.notes, d.created_by, d.created_at, d.environment, d.status, d.external_project_id, d.registered_on, d.evidence_document_id, d.response_reason, d.recorded_by, d.recorded_at)))
    BEGIN;
        THROW 51000, 'registry_project_registrations: identity is immutable; a recorded registry answer is final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_registry_submissions_immutable ON dbo.registry_submissions
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'registry_submissions: registry submissions are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.submission_code, i.project_id, i.monitoring_period_id, i.registration_id, i.registry_account_id, i.registry_organization_id, i.verification_decision_id, i.verification_submission_id, i.previous_submission_id, i.client_request_key, i.created_by, i.created_at, i.environment EXCEPT SELECT d.submission_code, d.project_id, d.monitoring_period_id, d.registration_id, d.registry_account_id, d.registry_organization_id, d.verification_decision_id, d.verification_submission_id, d.previous_submission_id, d.client_request_key, d.created_by, d.created_at, d.environment)
           OR (d.snapshot_sha256 IS NOT NULL AND EXISTS (SELECT i.snapshot, i.snapshot_sha256, i.idempotency_key, i.frozen_by, i.frozen_at EXCEPT SELECT d.snapshot, d.snapshot_sha256, d.idempotency_key, d.frozen_by, d.frozen_at))
           OR (d.external_submission_id IS NOT NULL AND (i.external_submission_id IS NULL OR i.external_submission_id <> d.external_submission_id))
           OR (d.status IN ('ACCEPTED', 'REJECTED', 'WITHDRAWN', 'CANCELLED', 'INVALIDATED') AND EXISTS (SELECT i.submission_code, i.project_id, i.monitoring_period_id, i.registration_id, i.registry_account_id, i.registry_organization_id, i.verification_decision_id, i.verification_submission_id, i.previous_submission_id, i.client_request_key, i.created_by, i.created_at, i.environment, i.snapshot, i.snapshot_sha256, i.idempotency_key, i.frozen_by, i.frozen_at, i.status, i.external_submission_id, i.submission_evidence_document_id, i.response_document_id, i.response_payload_sha256, i.external_response_ref, i.response_reason, i.submitted_by, i.submitted_at, i.response_by, i.response_at, i.closed_by, i.closed_at, i.closed_reason EXCEPT SELECT d.submission_code, d.project_id, d.monitoring_period_id, d.registration_id, d.registry_account_id, d.registry_organization_id, d.verification_decision_id, d.verification_submission_id, d.previous_submission_id, d.client_request_key, d.created_by, d.created_at, d.environment, d.snapshot, d.snapshot_sha256, d.idempotency_key, d.frozen_by, d.frozen_at, d.status, d.external_submission_id, d.submission_evidence_document_id, d.response_document_id, d.response_payload_sha256, d.external_response_ref, d.response_reason, d.submitted_by, d.submitted_at, d.response_by, d.response_at, d.closed_by, d.closed_at, d.closed_reason)))
    BEGIN;
        THROW 51000, 'registry_submissions: the frozen snapshot, its hash, the idempotency key and external references are fixed; final states are frozen.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_issuances_immutable ON dbo.credit_issuances
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_issuances: issuances are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.issuance_code, i.registry_submission_id, i.project_id, i.monitoring_period_id, i.registry_account_id, i.registry_organization_id, i.verification_decision_id, i.external_issuance_id, i.issuance_date, i.quantity, i.unit, i.source, i.evidence_document_id, i.api_response_sha256, i.corrects_issuance_id, i.correction_reason, i.client_request_key, i.recorded_by, i.recorded_at, i.environment EXCEPT SELECT d.issuance_code, d.registry_submission_id, d.project_id, d.monitoring_period_id, d.registry_account_id, d.registry_organization_id, d.verification_decision_id, d.external_issuance_id, d.issuance_date, d.quantity, d.unit, d.source, d.evidence_document_id, d.api_response_sha256, d.corrects_issuance_id, d.correction_reason, d.client_request_key, d.recorded_by, d.recorded_at, d.environment)
           OR (d.confirmed_by IS NOT NULL AND (i.confirmed_by IS NULL OR i.confirmed_by <> d.confirmed_by OR i.confirmed_at <> d.confirmed_at))
           OR (d.status = 'CONFIRMED' AND i.status NOT IN ('CONFIRMED', 'CORRECTED', 'CANCELLED'))
           OR (d.status IN ('VOIDED', 'CORRECTED', 'CANCELLED') AND EXISTS (SELECT i.issuance_code, i.registry_submission_id, i.project_id, i.monitoring_period_id, i.registry_account_id, i.registry_organization_id, i.verification_decision_id, i.external_issuance_id, i.issuance_date, i.quantity, i.unit, i.source, i.evidence_document_id, i.api_response_sha256, i.corrects_issuance_id, i.correction_reason, i.client_request_key, i.recorded_by, i.recorded_at, i.environment, i.status, i.confirmed_by, i.confirmed_at, i.corrected_by_issuance_id, i.voided_by, i.voided_at, i.void_reason, i.cancelled_by, i.cancelled_at, i.cancel_reason, i.cancel_document_id EXCEPT SELECT d.issuance_code, d.registry_submission_id, d.project_id, d.monitoring_period_id, d.registry_account_id, d.registry_organization_id, d.verification_decision_id, d.external_issuance_id, d.issuance_date, d.quantity, d.unit, d.source, d.evidence_document_id, d.api_response_sha256, d.corrects_issuance_id, d.correction_reason, d.client_request_key, d.recorded_by, d.recorded_at, d.environment, d.status, d.confirmed_by, d.confirmed_at, d.corrected_by_issuance_id, d.voided_by, d.voided_at, d.void_reason, d.cancelled_by, d.cancelled_at, d.cancel_reason, d.cancel_document_id)))
    BEGIN;
        THROW 51000, 'credit_issuances: recorded registry data is immutable; a confirmed issuance only becomes CORRECTED or CANCELLED; final states are frozen.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_batches_immutable ON dbo.credit_batches
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_batches: credit batches are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.batch_code, i.issuance_id, i.project_id, i.monitoring_period_id, i.registry_organization_id, i.registry_account_id, i.verification_decision_id, i.methodology_version_id, i.standard_id, i.seq, i.vintage, i.quantity, i.unit, i.created_at, i.environment EXCEPT SELECT d.batch_code, d.issuance_id, d.project_id, d.monitoring_period_id, d.registry_organization_id, d.registry_account_id, d.verification_decision_id, d.methodology_version_id, d.standard_id, d.seq, d.vintage, d.quantity, d.unit, d.created_at, d.environment)
           OR (i.status <> d.status AND NOT ((d.status = 'RECORDED' AND i.status IN ('ISSUED', 'VOIDED')) OR (d.status = 'ISSUED' AND i.status IN ('SUPERSEDED', 'CANCELLED')))))
    BEGIN;
        THROW 51000, 'credit_batches: a batch never changes; only RECORDED -> ISSUED / VOIDED and ISSUED -> SUPERSEDED / CANCELLED.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_serial_ranges_immutable ON dbo.credit_serial_ranges
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_serial_ranges: serial ranges are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.batch_id, i.registry_organization_id, i.seq, i.serial_start, i.serial_end, i.quantity, i.parsed_series, i.parsed_start, i.parsed_end, i.environment EXCEPT SELECT d.batch_id, d.registry_organization_id, d.seq, d.serial_start, d.serial_end, d.quantity, d.parsed_series, d.parsed_start, d.parsed_end, d.environment))
    BEGIN;
        THROW 51000, 'credit_serial_ranges: registry serial numbers are stored exactly as supplied and never change.', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: Phase 9A history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.registry_accounts) OR EXISTS (SELECT 1 FROM dbo.registry_project_registrations)
   OR EXISTS (SELECT 1 FROM dbo.registry_submissions) OR EXISTS (SELECT 1 FROM dbo.registry_events)
   OR EXISTS (SELECT 1 FROM dbo.credit_issuances) OR EXISTS (SELECT 1 FROM dbo.credit_batches) OR EXISTS (SELECT 1 FROM dbo.credit_serial_ranges)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT'))
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 9A registry accounts, registrations, submissions, events, issuances, credit batches or registry documents exist.', 1;
END""")
    for trigger in ("trg_credit_serial_ranges_immutable", "trg_credit_batches_immutable", "trg_credit_issuances_immutable",
                    "trg_registry_submissions_immutable", "trg_registry_registrations_immutable", "trg_registry_accounts_immutable",
                    "trg_registry_events_append_only"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'OTHER')")
    for seq in ("seq_registry_registration_code", "seq_registry_submission_code", "seq_credit_issuance_code", "seq_credit_batch_code"):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_credit_serial_ranges_start', table_name='credit_serial_ranges', mssql_where=sa.text('serial_start IS NOT NULL AND is_current = 1'))
    op.drop_index('uq_credit_serial_ranges_end', table_name='credit_serial_ranges', mssql_where=sa.text('serial_end IS NOT NULL AND is_current = 1'))
    op.drop_index(op.f('ix_credit_serial_ranges_batch_id'), table_name='credit_serial_ranges')
    op.drop_table('credit_serial_ranges')
    op.drop_index('ix_registry_events_submission', table_name='registry_events')
    op.drop_table('registry_events')
    op.drop_index('ix_credit_batches_project_period', table_name='credit_batches')
    op.drop_index(op.f('ix_credit_batches_issuance_id'), table_name='credit_batches')
    op.drop_table('credit_batches')
    op.drop_index('uq_credit_issuances_request_key', table_name='credit_issuances', mssql_where=sa.text('client_request_key IS NOT NULL'))
    op.drop_index('uq_credit_issuances_external', table_name='credit_issuances', mssql_where=sa.text("status = 'CONFIRMED'"))
    op.drop_index('ix_credit_issuances_submission', table_name='credit_issuances')
    op.drop_index(op.f('ix_credit_issuances_project_id'), table_name='credit_issuances')
    op.drop_table('credit_issuances')
    op.drop_index('uq_registry_submissions_request_key', table_name='registry_submissions', mssql_where=sa.text('client_request_key IS NOT NULL'))
    op.drop_index('uq_registry_submissions_open_period', table_name='registry_submissions', mssql_where=sa.text("status IN ('DRAFT', 'FROZEN', 'SUBMITTING', 'SUBMISSION_UNCONFIRMED', 'SUBMITTED', 'ACCEPTED')"))
    op.drop_index('uq_registry_submissions_idempotency', table_name='registry_submissions', mssql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('uq_registry_submissions_external', table_name='registry_submissions', mssql_where=sa.text('external_submission_id IS NOT NULL'))
    op.drop_index(op.f('ix_registry_submissions_project_id'), table_name='registry_submissions')
    op.drop_table('registry_submissions')
    op.drop_index('uq_registry_registrations_open', table_name='registry_project_registrations', mssql_where=sa.text("status IN ('PENDING', 'REGISTERED')"))
    op.drop_index('uq_registry_registrations_external', table_name='registry_project_registrations', mssql_where=sa.text('external_project_id IS NOT NULL'))
    op.drop_index(op.f('ix_registry_project_registrations_project_id'), table_name='registry_project_registrations')
    op.drop_table('registry_project_registrations')
    op.drop_index('uq_registry_accounts_external', table_name='registry_accounts')
    op.drop_index(op.f('ix_registry_accounts_organization_id'), table_name='registry_accounts')
    op.drop_table('registry_accounts')
    # ### end Alembic commands ###
