"""phase1 identity access audit

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 19:22:27.909040
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# Append-only enforcement (spec section 35): UPDATE/DELETE on these tables raise an error for
# every database user. Retention or legal erasure must be done by a DBA who explicitly disables the trigger.
APPEND_ONLY = ("audit_logs", "workflow_events", "login_audit", "security_events")

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_access_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('request_id', sa.Unicode(length=64), nullable=False),
    sa.Column('method', sa.Unicode(length=10), nullable=False),
    sa.Column('path', sa.Unicode(length=400), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
    sa.Column('user_agent', sa.Unicode(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_access_logs'))
    )
    op.create_index(op.f('ix_api_access_logs_occurred_at'), 'api_access_logs', ['occurred_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Unicode(length=80), nullable=False),
    sa.Column('entity_type', sa.Unicode(length=60), nullable=False),
    sa.Column('entity_id', sa.Unicode(length=64), nullable=True),
    sa.Column('old_value', sa.UnicodeText(), nullable=True),
    sa.Column('new_value', sa.UnicodeText(), nullable=True),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
    sa.Column('user_agent', sa.Unicode(length=400), nullable=True),
    sa.CheckConstraint('new_value IS NULL OR ISJSON(new_value) = 1', name=op.f('ck_audit_logs_new_value_json')),
    sa.CheckConstraint('old_value IS NULL OR ISJSON(old_value) = 1', name=op.f('ck_audit_logs_old_value_json')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_occurred_at', 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('login_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email_attempted', sa.Unicode(length=320), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Unicode(length=60), nullable=True),
    sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
    sa.Column('user_agent', sa.Unicode(length=400), nullable=True),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_audit'))
    )
    op.create_index(op.f('ix_login_audit_occurred_at'), 'login_audit', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_login_audit_user_id'), 'login_audit', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('code', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('org_type', sa.Unicode(length=30), nullable=False),
    sa.Column('country', sa.Unicode(length=2), nullable=True),
    sa.Column('registration_number', sa.Unicode(length=100), nullable=True),
    sa.Column('contact_email', sa.Unicode(length=320), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_organizations_environment')),
    sa.CheckConstraint("org_type IN ('PLATFORM', 'PROJECT_DEVELOPER', 'FIELD_PARTNER', 'FARMER_GROUP', 'LABORATORY', 'VVB', 'REGISTRY', 'BUYER')", name=op.f('ck_organizations_org_type')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'ARCHIVED')", name=op.f('ck_organizations_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_organizations_code'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.Unicode(length=80), nullable=False),
    sa.Column('module', sa.Unicode(length=40), nullable=False),
    sa.Column('name', sa.Unicode(length=120), nullable=False),
    sa.Column('description', sa.Unicode(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('code', sa.Unicode(length=60), nullable=False),
    sa.Column('name', sa.Unicode(length=120), nullable=False),
    sa.Column('description', sa.Unicode(length=1000), nullable=True),
    sa.Column('scope', sa.Unicode(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("scope IN ('PLATFORM', 'ORGANIZATION')", name=op.f('ck_roles_scope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('event_type', sa.Unicode(length=60), nullable=False),
    sa.Column('severity', sa.Unicode(length=10), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
    sa.Column('details', sa.UnicodeText(), nullable=True),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'CRITICAL')", name=op.f('ck_security_events_severity')),
    sa.CheckConstraint('details IS NULL OR ISJSON(details) = 1', name=op.f('ck_security_events_details_json')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.Unicode(length=320), nullable=False),
    sa.Column('full_name', sa.Unicode(length=200), nullable=False),
    sa.Column('phone', sa.Unicode(length=30), nullable=True),
    sa.Column('password_hash', sa.Unicode(length=255), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('password_changed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', mssql.DATETIME2(), nullable=True),
    sa.Column('last_login_at', mssql.DATETIME2(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('mfa_secret_ref', sa.Unicode(length=200), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_users_environment')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('entity_type', sa.Unicode(length=60), nullable=False),
    sa.Column('entity_id', sa.Unicode(length=64), nullable=False),
    sa.Column('from_status', sa.Unicode(length=40), nullable=True),
    sa.Column('to_status', sa.Unicode(length=40), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('request_id', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_events'))
    )
    op.create_index('ix_workflow_events_entity', 'workflow_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('organization_users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Unicode(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('joined_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_users_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_users')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_organization_users_organization_id_user_id'))
    )
    op.create_index(op.f('ix_organization_users_organization_id'), 'organization_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_users_user_id'), 'organization_users', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('last_seen_at', mssql.DATETIME2(), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(), nullable=False),
    sa.Column('revoked_at', mssql.DATETIME2(), nullable=True),
    sa.Column('revoked_reason', sa.Unicode(length=100), nullable=True),
    sa.Column('ip_address', sa.Unicode(length=64), nullable=True),
    sa.Column('user_agent', sa.Unicode(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id', name=op.f('uq_user_roles_user_id_role_id_organization_id'))
    )
    op.create_index('ix_user_roles_organization_id', 'user_roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Unicode(length=64), nullable=False),
    sa.Column('issued_at', mssql.DATETIME2(), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(), nullable=False),
    sa.Column('used_at', mssql.DATETIME2(), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    # ### end Alembic commands ###
    for table in APPEND_ONLY:
        op.execute(f"""
CREATE TRIGGER trg_{table}_append_only ON dbo.{table}
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, '{table} is append-only: updates and deletes are not permitted.', 1;
END""")


def downgrade() -> None:
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index('ix_user_roles_organization_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_organization_users_user_id'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_organization_id'), table_name='organization_users')
    op.drop_table('organization_users')
    op.drop_index('ix_workflow_events_entity', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_login_audit_user_id'), table_name='login_audit')
    op.drop_index(op.f('ix_login_audit_occurred_at'), table_name='login_audit')
    op.drop_table('login_audit')
    op.drop_index('ix_audit_logs_occurred_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_access_logs_occurred_at'), table_name='api_access_logs')
    op.drop_table('api_access_logs')
    # ### end Alembic commands ###
