"""Phase 12A — background job infrastructure (SQL Server is the system of record; Redis is only the Celery broker).

Tables: background_jobs (allow-listed task, environment, small identifier payload + SHA-256, idempotency key — filtered unique — status
QUEUED / CLAIMED / RUNNING / SUCCEEDED / RETRY_WAITING / FAILED / CANCELLED, lease, retry counters, publication bookkeeping),
background_job_attempts (append-only; one row per execution, completed once), background_worker_heartbeats (operational only).
Also: the JOB- sequence; user status SYSTEM and two non-login SYSTEM actors (LIVE, DEMO) for audit attribution of background work;
triggers (attempts append-only; job identity fixed; SUCCEEDED / CANCELLED final; FAILED only requeued; nothing deleted); a downgrade guard.
No Phase 1–11 table changes other than the widened users.status CHECK.

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-03 20:22:51.999318
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0017'
down_revision: str | None = '0016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_worker_heartbeats',
    sa.Column('worker_identity', sa.Unicode(length=200), nullable=False),
    sa.Column('hostname', sa.Unicode(length=200), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('queues', sa.Unicode(length=200), nullable=False),
    sa.Column('started_at', mssql.DATETIME2(), nullable=False),
    sa.Column('last_heartbeat_at', mssql.DATETIME2(), nullable=False),
    sa.Column('stopped_at', mssql.DATETIME2(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_worker_heartbeats')),
    sa.UniqueConstraint('worker_identity', name=op.f('uq_background_worker_heartbeats_worker_identity'))
    )
    op.create_table('background_jobs',
    sa.Column('job_code', sa.Unicode(length=20), nullable=False),
    sa.Column('job_type', sa.Unicode(length=60), nullable=False),
    sa.Column('task_name', sa.Unicode(length=120), nullable=False),
    sa.Column('queue_name', sa.Unicode(length=40), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('trigger_type', sa.Unicode(length=10), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.Unicode(length=40), nullable=True),
    sa.Column('entity_id', sa.Unicode(length=64), nullable=True),
    sa.Column('idempotency_key', sa.Unicode(length=160), nullable=True),
    sa.Column('payload', sa.UnicodeText(), nullable=False),
    sa.Column('payload_hash', sa.Unicode(length=64), nullable=False),
    sa.Column('result', sa.UnicodeText(), nullable=True),
    sa.Column('scheduled_at', mssql.DATETIME2(), nullable=True),
    sa.Column('available_at', mssql.DATETIME2(), nullable=False),
    sa.Column('claimed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('claimed_by', sa.Unicode(length=200), nullable=True),
    sa.Column('lease_expires_at', mssql.DATETIME2(), nullable=True),
    sa.Column('started_at', mssql.DATETIME2(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('failed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('cancelled_at', mssql.DATETIME2(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Unicode(length=60), nullable=True),
    sa.Column('error_message', sa.Unicode(length=1000), nullable=True),
    sa.Column('published_at', mssql.DATETIME2(), nullable=True),
    sa.Column('publish_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_publish_error', sa.Unicode(length=500), nullable=True),
    sa.Column('reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_background_jobs_environment')),
    sa.CheckConstraint("status <> 'FAILED' OR (failed_at IS NOT NULL AND error_code IS NOT NULL)", name=op.f('ck_background_jobs_failed')),
    sa.CheckConstraint("status <> 'SUCCEEDED' OR completed_at IS NOT NULL", name=op.f('ck_background_jobs_succeeded')),
    sa.CheckConstraint("status IN ('QUEUED', 'CLAIMED', 'RUNNING', 'SUCCEEDED', 'RETRY_WAITING', 'FAILED', 'CANCELLED')", name=op.f('ck_background_jobs_status')),
    sa.CheckConstraint("status NOT IN ('CLAIMED', 'RUNNING') OR (claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)", name=op.f('ck_background_jobs_claimed')),
    sa.CheckConstraint("trigger_type IN ('SCHEDULE', 'MANUAL', 'SERVICE')", name=op.f('ck_background_jobs_trigger_type')),
    sa.CheckConstraint('ISJSON(payload) = 1', name=op.f('ck_background_jobs_payload_json')),
    sa.CheckConstraint('result IS NULL OR ISJSON(result) = 1', name=op.f('ck_background_jobs_result_json')),
    sa.CheckConstraint('retry_count >= 0 AND max_retries >= 0', name=op.f('ck_background_jobs_retries')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_background_jobs_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_background_jobs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs')),
    sa.UniqueConstraint('job_code', name=op.f('uq_background_jobs_job_code'))
    )
    op.create_index('ix_background_jobs_due', 'background_jobs', ['status', 'available_at'], unique=False)
    op.create_index('ix_background_jobs_task', 'background_jobs', ['environment', 'task_name', 'created_at'], unique=False)
    op.create_index('uq_background_jobs_idempotency', 'background_jobs', ['idempotency_key'], unique=True, mssql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('background_job_attempts',
    sa.Column('background_job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_identity', sa.Unicode(length=200), nullable=False),
    sa.Column('task_name', sa.Unicode(length=120), nullable=False),
    sa.Column('system_actor_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('started_at', mssql.DATETIME2(), nullable=False),
    sa.Column('finished_at', mssql.DATETIME2(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Unicode(length=60), nullable=True),
    sa.Column('error_message', sa.Unicode(length=1000), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status = 'RUNNING' OR finished_at IS NOT NULL", name=op.f('ck_background_job_attempts_finished')),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCEEDED', 'RETRYABLE_ERROR', 'FAILED', 'ABANDONED')", name=op.f('ck_background_job_attempts_status')),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], name=op.f('fk_background_job_attempts_background_job_id_background_jobs')),
    sa.ForeignKeyConstraint(['system_actor_id'], ['users.id'], name=op.f('fk_background_job_attempts_system_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_job_attempts'))
    )
    op.create_index(op.f('ix_background_job_attempts_background_job_id'), 'background_job_attempts', ['background_job_id'], unique=False)
    op.create_index('uq_background_job_attempts_number', 'background_job_attempts', ['background_job_id', 'attempt_number'], unique=True)
    # ### end Alembic commands ###
    # ---- hand-written: JOB- sequence, SYSTEM actors, append-only / immutability triggers
    op.execute("CREATE SEQUENCE dbo.seq_job_code AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_users_status'), 'users', type_='check')
    op.create_check_constraint(op.f('ck_users_status'), 'users', "status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED', 'SYSTEM')")
    # One non-login SYSTEM actor per data environment: no password (an unusable marker, never a bcrypt hash), no role, no
    # organization; status SYSTEM is refused at sign-in and hidden from user administration. It only attributes system-owned
    # transitions (deadline expiry) performed by background jobs.
    op.execute("""
INSERT INTO dbo.users (id, email, full_name, password_hash, status, must_change_password, failed_login_count, mfa_enabled, environment)
VALUES ('00000000-0000-4000-8000-00000000a001', 'system.live@carbon-platform.invalid', 'SYSTEM — background jobs (LIVE)', '!SYSTEM-ACTOR-NO-LOGIN', 'SYSTEM', 0, 0, 0, 'LIVE'),
       ('00000000-0000-4000-8000-00000000a002', 'system.demo@carbon-platform.invalid', 'SYSTEM — background jobs (DEMO)', '!SYSTEM-ACTOR-NO-LOGIN', 'SYSTEM', 0, 0, 0, 'DEMO')""")
    op.execute("""
CREATE TRIGGER trg_background_job_attempts_guard ON dbo.background_job_attempts
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'background_job_attempts: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.background_job_id, i.attempt_number, i.worker_identity, i.task_name, i.system_actor_id, i.started_at, i.created_at EXCEPT SELECT d.background_job_id, d.attempt_number, d.worker_identity, d.task_name, d.system_actor_id, d.started_at, d.created_at)
           OR d.status <> 'RUNNING')
    BEGIN;
        THROW 51000, 'background_job_attempts: attempts are append-only: identity fixed; a RUNNING attempt is completed once and never changed afterwards.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_background_jobs_guard ON dbo.background_jobs
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'background_jobs: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.job_code, i.job_type, i.task_name, i.queue_name, i.environment, i.trigger_type, i.organization_id, i.entity_type, i.entity_id, i.idempotency_key, i.payload, i.payload_hash, i.scheduled_at, i.max_retries, i.created_by, i.created_at EXCEPT SELECT d.job_code, d.job_type, d.task_name, d.queue_name, d.environment, d.trigger_type, d.organization_id, d.entity_type, d.entity_id, d.idempotency_key, d.payload, d.payload_hash, d.scheduled_at, d.max_retries, d.created_by, d.created_at)
           OR (d.status IN ('SUCCEEDED', 'CANCELLED') AND EXISTS (SELECT i.job_code, i.job_type, i.task_name, i.queue_name, i.environment, i.trigger_type, i.organization_id, i.entity_type, i.entity_id, i.idempotency_key, i.payload, i.payload_hash, i.scheduled_at, i.max_retries, i.created_by, i.created_at, i.status, i.result, i.available_at, i.claimed_at, i.claimed_by, i.lease_expires_at, i.started_at, i.completed_at, i.failed_at, i.cancelled_at, i.retry_count, i.error_code, i.error_message, i.published_at, i.publish_attempts, i.last_publish_error, i.reason EXCEPT SELECT d.job_code, d.job_type, d.task_name, d.queue_name, d.environment, d.trigger_type, d.organization_id, d.entity_type, d.entity_id, d.idempotency_key, d.payload, d.payload_hash, d.scheduled_at, d.max_retries, d.created_by, d.created_at, d.status, d.result, d.available_at, d.claimed_at, d.claimed_by, d.lease_expires_at, d.started_at, d.completed_at, d.failed_at, d.cancelled_at, d.retry_count, d.error_code, d.error_message, d.published_at, d.publish_attempts, d.last_publish_error, d.reason))
           OR (d.status = 'FAILED' AND i.status NOT IN ('FAILED', 'QUEUED')))
    BEGIN;
        THROW 51000, 'background_jobs: identity and payload are fixed; SUCCEEDED / CANCELLED are final; a FAILED job may only be requeued.', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: job history is never dropped silently; SYSTEM actors are removed only while unreferenced
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.background_jobs) OR EXISTS (SELECT 1 FROM dbo.background_job_attempts)
   OR EXISTS (SELECT 1 FROM dbo.background_worker_heartbeats)
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 12A background jobs, attempts or worker heartbeats exist.', 1;
END;
IF EXISTS (SELECT 1 FROM dbo.credit_ledger_entries WHERE actor_id IN ('00000000-0000-4000-8000-00000000a001', '00000000-0000-4000-8000-00000000a002'))
BEGIN;
    THROW 51000, 'Downgrade refused: the SYSTEM actors are referenced by ledger entries.', 1;
END;""")
    for trigger in ('trg_background_jobs_guard', 'trg_background_job_attempts_guard'):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.execute("DELETE FROM dbo.users WHERE id IN ('00000000-0000-4000-8000-00000000a001', '00000000-0000-4000-8000-00000000a002') AND status = 'SYSTEM'")
    op.drop_constraint(op.f('ck_users_status'), 'users', type_='check')
    op.create_check_constraint(op.f('ck_users_status'), 'users', "status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')")
    op.execute("DROP SEQUENCE IF EXISTS dbo.seq_job_code")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_background_job_attempts_number', table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_background_job_id'), table_name='background_job_attempts')
    op.drop_table('background_job_attempts')
    op.drop_index('uq_background_jobs_idempotency', table_name='background_jobs', mssql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_background_jobs_task', table_name='background_jobs')
    op.drop_index('ix_background_jobs_due', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_table('background_worker_heartbeats')
    # ### end Alembic commands ###
