"""Phase 12B-I — document safety: append-only antivirus scan history.

Table: document_scans (one row per scan — acceptance, background rescan, release rescan — with the scanned SHA-256, result
CLEAN / INFECTED / NOT_SCANNED / ERROR, scanner identity / engine version, threat, trigger, job, actor, duration). A trigger makes it
append-only (no UPDATE, no DELETE). No Phase 1–12A table changes: documents.status already allows QUARANTINED and
document_versions.scan_status stays the immutable acceptance result. A downgrade guard refuses to drop recorded scan history.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-03 21:56:31.978407
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0018'
down_revision: str | None = '0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_scans',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('checksum_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('result', sa.Unicode(length=15), nullable=False),
    sa.Column('provider', sa.Unicode(length=60), nullable=False),
    sa.Column('engine_version', sa.Unicode(length=120), nullable=True),
    sa.Column('threat_name', sa.Unicode(length=200), nullable=True),
    sa.Column('error_code', sa.Unicode(length=60), nullable=True),
    sa.Column('detail', sa.Unicode(length=400), nullable=True),
    sa.Column('trigger_type', sa.Unicode(length=10), nullable=False),
    sa.Column('background_job_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scanned_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_document_scans_environment')),
    sa.CheckConstraint("result IN ('CLEAN', 'INFECTED', 'NOT_SCANNED', 'ERROR')", name=op.f('ck_document_scans_result')),
    sa.CheckConstraint("trigger_type IN ('UPLOAD', 'RESCAN', 'RELEASE')", name=op.f('ck_document_scans_trigger_type')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_document_scans_actor_id_users')),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], name=op.f('fk_document_scans_background_job_id_background_jobs')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_scans_document_id_documents')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_scans_document_version_id_document_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_scans'))
    )
    op.create_index('ix_document_scans_document', 'document_scans', ['document_id', 'scanned_at'], unique=False)
    op.create_index('ix_document_scans_version', 'document_scans', ['document_version_id', 'scanned_at'], unique=False)
    # ### end Alembic commands ###
    # ---- hand-written: scan history is append-only (D15)
    op.execute("""
CREATE TRIGGER trg_document_scans_append_only ON dbo.document_scans
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'document_scans: scan history is append-only; rows are never changed or deleted.', 1;
END""")


def downgrade() -> None:
    # ---- hand-written: recorded scan history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.document_scans)
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 12B document scan history exists.', 1;
END;""")
    op.execute("DROP TRIGGER IF EXISTS trg_document_scans_append_only")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_scans_version', table_name='document_scans')
    op.drop_index('ix_document_scans_document', table_name='document_scans')
    op.drop_table('document_scans')
    # ### end Alembic commands ###
