"""Phase 9B — credit ledger: inventory, ownership positions, reservations, transfers, retirements (no marketplace, pricing, orders,
payment or payout).

7 tables (credit_ledger_entries — append-only, posted once; credit_positions — immutable, consumed exactly once; credit_openings,
credit_reservations, credit_transfers, credit_retirements, credit_reversals), sequences LEDG / OPN / RSV / TRF / RET / REV, filtered
unique indexes (one open / confirmed opening per batch; registry + transfer / retirement reference; idempotency keys; one open reversal per
entry), the documents categories RETIREMENT_CERTIFICATE / REGISTRY_TRANSFER_EVIDENCE (removed on downgrade only when unused) and
triggers: entry posting validates inputs = outputs and batch conservation (open positions = registry-issued batch quantity; zero after an
ISSUANCE_ADJUSTMENT) and parser-derived sub-range overlaps; positions are created OPEN inside an unposted entry, never edited except
OPEN → CONSUMED once (RETIRED never); final states frozen; nothing deleted. 9A batches and serial ranges are not touched.

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-03 15:20:53.175169
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0014'
down_revision: str | None = '0013'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger_entries',
    sa.Column('entry_code', sa.Unicode(length=20), nullable=False),
    sa.Column('entry_type', sa.Unicode(length=25), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_organization_id', sa.Uuid(), nullable=True),
    sa.Column('opening_id', sa.Uuid(), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('retirement_id', sa.Uuid(), nullable=True),
    sa.Column('reversal_id', sa.Uuid(), nullable=True),
    sa.Column('issuance_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("entry_type IN ('OPEN_INVENTORY', 'RESERVE', 'RESERVATION_RELEASE', 'RESERVATION_EXPIRE', 'TRANSFER_REQUEST', 'TRANSFER_COMPLETE', 'TRANSFER_CANCEL', 'TRANSFER_REJECT', 'RETIREMENT_REQUEST', 'RETIREMENT_RETIRE', 'RETIREMENT_REJECT', 'RETIREMENT_CANCEL', 'REVERSAL', 'ISSUANCE_ADJUSTMENT')", name=op.f('ck_credit_ledger_entries_entry_type')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_ledger_entries_environment')),
    sa.CheckConstraint('confirmed_by IS NULL OR confirmed_by <> actor_id', name=op.f('ck_credit_ledger_entries_dual_control')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_credit_ledger_entries_actor_id_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_ledger_entries_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_credit_ledger_entries_confirmed_by_users')),
    sa.ForeignKeyConstraint(['counterparty_organization_id'], ['organizations.id'], name=op.f('fk_credit_ledger_entries_counterparty_organization_id_organizations')),
    sa.ForeignKeyConstraint(['issuance_id'], ['credit_issuances.id'], name=op.f('fk_credit_ledger_entries_issuance_id_credit_issuances')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_credit_ledger_entries_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger_entries')),
    sa.UniqueConstraint('entry_code', name=op.f('uq_credit_ledger_entries_entry_code'))
    )
    op.create_index('ix_credit_ledger_entries_batch', 'credit_ledger_entries', ['batch_id', 'created_at'], unique=False)
    op.create_index('uq_credit_ledger_entries_request_key', 'credit_ledger_entries', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_openings',
    sa.Column('opening_code', sa.Unicode(length=20), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('owner_organization_id', sa.Uuid(), nullable=False),
    sa.Column('holding_registry_account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('cancelled_by', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', mssql.DATETIME2(), nullable=True),
    sa.Column('cancel_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_openings_environment')),
    sa.CheckConstraint("status <> 'CANCELLED' OR cancel_reason IS NOT NULL", name=op.f('ck_credit_openings_cancel_reason')),
    sa.CheckConstraint("status <> 'CONFIRMED' OR (confirmed_by IS NOT NULL AND entry_id IS NOT NULL)", name=op.f('ck_credit_openings_confirmed')),
    sa.CheckConstraint("status IN ('REQUESTED', 'CONFIRMED', 'CANCELLED')", name=op.f('ck_credit_openings_status')),
    sa.CheckConstraint('confirmed_by IS NULL OR confirmed_by <> requested_by', name=op.f('ck_credit_openings_dual_control')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_openings_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name=op.f('fk_credit_openings_cancelled_by_users')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_credit_openings_confirmed_by_users')),
    sa.ForeignKeyConstraint(['entry_id'], ['credit_ledger_entries.id'], name=op.f('fk_credit_openings_entry_id_credit_ledger_entries')),
    sa.ForeignKeyConstraint(['holding_registry_account_id'], ['registry_accounts.id'], name=op.f('fk_credit_openings_holding_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], name=op.f('fk_credit_openings_owner_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_credit_openings_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_openings')),
    sa.UniqueConstraint('opening_code', name=op.f('uq_credit_openings_opening_code'))
    )
    op.create_index('uq_credit_openings_batch', 'credit_openings', ['batch_id'], unique=True, mssql_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"))
    op.create_index('uq_credit_openings_request_key', 'credit_openings', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_reservations',
    sa.Column('reservation_code', sa.Unicode(length=20), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=True),
    sa.Column('owner_organization_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_organization_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.Unicode(length=200), nullable=False),
    sa.Column('purpose_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('expires_at', mssql.DATETIME2(), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('released_by', sa.Uuid(), nullable=True),
    sa.Column('released_at', mssql.DATETIME2(), nullable=True),
    sa.Column('release_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_reservations_environment')),
    sa.CheckConstraint("status <> 'RELEASED' OR (released_by IS NOT NULL AND release_reason IS NOT NULL)", name=op.f('ck_credit_reservations_release_reason')),
    sa.CheckConstraint("status IN ('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED')", name=op.f('ck_credit_reservations_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_reservations_quantity_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_reservations_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_credit_reservations_created_by_users')),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], name=op.f('fk_credit_reservations_owner_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recipient_organization_id'], ['organizations.id'], name=op.f('fk_credit_reservations_recipient_organization_id_organizations')),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_credit_reservations_released_by_users')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_credit_reservations_serial_range_id_credit_serial_ranges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_reservations')),
    sa.UniqueConstraint('reservation_code', name=op.f('uq_credit_reservations_reservation_code'))
    )
    op.create_index('ix_credit_reservations_active', 'credit_reservations', ['batch_id', 'expires_at'], unique=False, mssql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_credit_reservations_owner_organization_id'), 'credit_reservations', ['owner_organization_id'], unique=False)
    op.create_index('uq_credit_reservations_request_key', 'credit_reservations', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_reversals',
    sa.Column('reversal_code', sa.Unicode(length=20), nullable=False),
    sa.Column('reversed_entry_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Unicode(length=2000), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', mssql.DATETIME2(), nullable=True),
    sa.Column('decision_note', sa.Unicode(length=2000), nullable=True),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_reversals_environment')),
    sa.CheckConstraint("status IN ('REQUESTED', 'APPLIED', 'REJECTED')", name=op.f('ck_credit_reversals_status')),
    sa.CheckConstraint('decided_by IS NULL OR decided_by <> requested_by', name=op.f('ck_credit_reversals_dual_control')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_reversals_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_credit_reversals_decided_by_users')),
    sa.ForeignKeyConstraint(['entry_id'], ['credit_ledger_entries.id'], name=op.f('fk_credit_reversals_entry_id_credit_ledger_entries')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_credit_reversals_requested_by_users')),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['credit_ledger_entries.id'], name=op.f('fk_credit_reversals_reversed_entry_id_credit_ledger_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_reversals')),
    sa.UniqueConstraint('reversal_code', name=op.f('uq_credit_reversals_reversal_code'))
    )
    op.create_index('uq_credit_reversals_open', 'credit_reversals', ['reversed_entry_id'], unique=True, mssql_where=sa.text("status IN ('REQUESTED', 'APPLIED')"))
    op.create_index('uq_credit_reversals_request_key', 'credit_reversals', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_retirements',
    sa.Column('retirement_code', sa.Unicode(length=20), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('owner_organization_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('beneficiary', sa.Unicode(length=300), nullable=False),
    sa.Column('reason', sa.Unicode(length=2000), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('retired_by', sa.Uuid(), nullable=True),
    sa.Column('retired_at', mssql.DATETIME2(), nullable=True),
    sa.Column('registry_retirement_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('certificate_document_id', sa.Uuid(), nullable=True),
    sa.Column('retired_serials', sa.UnicodeText(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('close_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_retirements_environment')),
    sa.CheckConstraint("status <> 'RETIRED' OR (registry_retirement_reference IS NOT NULL AND certificate_document_id IS NOT NULL AND retired_by IS NOT NULL AND retirement_date IS NOT NULL)", name=op.f('ck_credit_retirements_registry_evidence')),
    sa.CheckConstraint("status IN ('REQUESTED', 'RETIRED', 'REJECTED', 'CANCELLED')", name=op.f('ck_credit_retirements_status')),
    sa.CheckConstraint("status NOT IN ('CANCELLED', 'REJECTED') OR close_reason IS NOT NULL", name=op.f('ck_credit_retirements_close_reason')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_retirements_quantity_positive')),
    sa.CheckConstraint('retired_by IS NULL OR retired_by <> requested_by', name=op.f('ck_credit_retirements_dual_control')),
    sa.CheckConstraint('retired_serials IS NULL OR ISJSON(retired_serials) = 1', name=op.f('ck_credit_retirements_retired_serials_json')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_retirements_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['certificate_document_id'], ['documents.id'], name=op.f('fk_credit_retirements_certificate_document_id_documents')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_credit_retirements_closed_by_users')),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], name=op.f('fk_credit_retirements_owner_organization_id_organizations')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_credit_retirements_registry_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_credit_retirements_requested_by_users')),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], name=op.f('fk_credit_retirements_reservation_id_credit_reservations')),
    sa.ForeignKeyConstraint(['retired_by'], ['users.id'], name=op.f('fk_credit_retirements_retired_by_users')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_credit_retirements_serial_range_id_credit_serial_ranges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_retirements')),
    sa.UniqueConstraint('retirement_code', name=op.f('uq_credit_retirements_retirement_code'))
    )
    op.create_index(op.f('ix_credit_retirements_owner_organization_id'), 'credit_retirements', ['owner_organization_id'], unique=False)
    op.create_index('uq_credit_retirements_registry_ref', 'credit_retirements', ['registry_organization_id', 'registry_retirement_reference'], unique=True, mssql_where=sa.text('registry_retirement_reference IS NOT NULL'))
    op.create_index('uq_credit_retirements_request_key', 'credit_retirements', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_transfers',
    sa.Column('transfer_code', sa.Unicode(length=20), nullable=False),
    sa.Column('kind', sa.Unicode(length=10), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('registry_organization_id', sa.Uuid(), nullable=False),
    sa.Column('sender_organization_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_organization_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_external_account_id', sa.Unicode(length=120), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('purpose', sa.Unicode(length=200), nullable=True),
    sa.Column('purpose_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('registry_transfer_reference', sa.Unicode(length=120), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', mssql.DATETIME2(), nullable=True),
    sa.Column('close_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('request_key', sa.Unicode(length=80), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("NOT (status = 'COMPLETED' AND kind = 'REGISTRY') OR (registry_transfer_reference IS NOT NULL AND evidence_document_id IS NOT NULL)", name=op.f('ck_credit_transfers_registry_evidence')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_transfers_environment')),
    sa.CheckConstraint("kind <> 'REGISTRY' OR recipient_external_account_id IS NOT NULL", name=op.f('ck_credit_transfers_registry_recipient_account')),
    sa.CheckConstraint("kind IN ('INTERNAL', 'REGISTRY')", name=op.f('ck_credit_transfers_kind')),
    sa.CheckConstraint("sender_organization_id <> recipient_organization_id OR kind = 'REGISTRY'", name=op.f('ck_credit_transfers_distinct_parties')),
    sa.CheckConstraint("status IN ('REQUESTED', 'COMPLETED', 'CANCELLED', 'REJECTED')", name=op.f('ck_credit_transfers_status')),
    sa.CheckConstraint("status NOT IN ('CANCELLED', 'REJECTED') OR close_reason IS NOT NULL", name=op.f('ck_credit_transfers_close_reason')),
    sa.CheckConstraint('completed_by IS NULL OR completed_by <> requested_by', name=op.f('ck_credit_transfers_dual_control')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_transfers_quantity_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_transfers_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_credit_transfers_closed_by_users')),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_credit_transfers_completed_by_users')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_credit_transfers_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['recipient_organization_id'], ['organizations.id'], name=op.f('fk_credit_transfers_recipient_organization_id_organizations')),
    sa.ForeignKeyConstraint(['registry_organization_id'], ['organizations.id'], name=op.f('fk_credit_transfers_registry_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_credit_transfers_requested_by_users')),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], name=op.f('fk_credit_transfers_reservation_id_credit_reservations')),
    sa.ForeignKeyConstraint(['sender_organization_id'], ['organizations.id'], name=op.f('fk_credit_transfers_sender_organization_id_organizations')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_credit_transfers_serial_range_id_credit_serial_ranges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transfers')),
    sa.UniqueConstraint('transfer_code', name=op.f('uq_credit_transfers_transfer_code'))
    )
    op.create_index(op.f('ix_credit_transfers_recipient_organization_id'), 'credit_transfers', ['recipient_organization_id'], unique=False)
    op.create_index(op.f('ix_credit_transfers_sender_organization_id'), 'credit_transfers', ['sender_organization_id'], unique=False)
    op.create_index('uq_credit_transfers_registry_ref', 'credit_transfers', ['registry_organization_id', 'registry_transfer_reference'], unique=True, mssql_where=sa.text('registry_transfer_reference IS NOT NULL'))
    op.create_index('uq_credit_transfers_request_key', 'credit_transfers', ['request_key'], unique=True, mssql_where=sa.text('request_key IS NOT NULL'))
    op.create_table('credit_positions',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('serial_range_id', sa.Uuid(), nullable=False),
    sa.Column('owner_organization_id', sa.Uuid(), nullable=False),
    sa.Column('holding_registry_account_id', sa.Uuid(), nullable=True),
    sa.Column('holding_external_account_id', sa.Unicode(length=120), nullable=False),
    sa.Column('state', sa.Unicode(length=20), nullable=False),
    sa.Column('status', sa.Unicode(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=0), nullable=False),
    sa.Column('sub_start', sa.Unicode(length=200), nullable=True),
    sa.Column('sub_end', sa.Unicode(length=200), nullable=True),
    sa.Column('parsed_series', sa.Unicode(length=120), nullable=True),
    sa.Column('parsed_start', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('parsed_end', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('reservation_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('retirement_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_entry_id', sa.Uuid(), nullable=False),
    sa.Column('consumed_by_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(status = 'OPEN' AND consumed_by_entry_id IS NULL) OR (status = 'CONSUMED' AND consumed_by_entry_id IS NOT NULL)", name=op.f('ck_credit_positions_consumed_link')),
    sa.CheckConstraint("NOT (state = 'RETIRED' AND status = 'CONSUMED')", name=op.f('ck_credit_positions_retired_terminal')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_credit_positions_environment')),
    sa.CheckConstraint("state IN ('AVAILABLE', 'RESERVED', 'TRANSFER_PENDING', 'RETIREMENT_PENDING', 'RETIRED')", name=op.f('ck_credit_positions_state')),
    sa.CheckConstraint("status IN ('OPEN', 'CONSUMED')", name=op.f('ck_credit_positions_status')),
    sa.CheckConstraint('(parsed_series IS NULL AND parsed_start IS NULL AND parsed_end IS NULL) OR (parsed_series IS NOT NULL AND parsed_start IS NOT NULL AND parsed_end IS NOT NULL AND parsed_end >= parsed_start AND parsed_end - parsed_start + 1 = quantity)', name=op.f('ck_credit_positions_parsed_bounds')),
    sa.CheckConstraint('(sub_start IS NULL AND sub_end IS NULL) OR (sub_start IS NOT NULL AND sub_end IS NOT NULL)', name=op.f('ck_credit_positions_sub_range_pair')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_credit_positions_quantity_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['credit_batches.id'], name=op.f('fk_credit_positions_batch_id_credit_batches')),
    sa.ForeignKeyConstraint(['consumed_by_entry_id'], ['credit_ledger_entries.id'], name=op.f('fk_credit_positions_consumed_by_entry_id_credit_ledger_entries')),
    sa.ForeignKeyConstraint(['created_by_entry_id'], ['credit_ledger_entries.id'], name=op.f('fk_credit_positions_created_by_entry_id_credit_ledger_entries')),
    sa.ForeignKeyConstraint(['holding_registry_account_id'], ['registry_accounts.id'], name=op.f('fk_credit_positions_holding_registry_account_id_registry_accounts')),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], name=op.f('fk_credit_positions_owner_organization_id_organizations')),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], name=op.f('fk_credit_positions_reservation_id_credit_reservations')),
    sa.ForeignKeyConstraint(['retirement_id'], ['credit_retirements.id'], name=op.f('fk_credit_positions_retirement_id_credit_retirements')),
    sa.ForeignKeyConstraint(['serial_range_id'], ['credit_serial_ranges.id'], name=op.f('fk_credit_positions_serial_range_id_credit_serial_ranges')),
    sa.ForeignKeyConstraint(['transfer_id'], ['credit_transfers.id'], name=op.f('fk_credit_positions_transfer_id_credit_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_positions'))
    )
    op.create_index('ix_credit_positions_consumed_by', 'credit_positions', ['consumed_by_entry_id'], unique=False)
    op.create_index('ix_credit_positions_created_by', 'credit_positions', ['created_by_entry_id'], unique=False)
    op.create_index('ix_credit_positions_open', 'credit_positions', ['batch_id', 'serial_range_id', 'owner_organization_id', 'state'], unique=False, mssql_where=sa.text("status = 'OPEN'"))
    op.create_index(op.f('ix_credit_positions_owner_organization_id'), 'credit_positions', ['owner_organization_id'], unique=False)
    # ### end Alembic commands ###

    # ---- hand-written: cyclic foreign keys, sequences, documents categories, ledger triggers
    op.create_foreign_key(op.f('fk_credit_ledger_entries_opening_id_credit_openings'), 'credit_ledger_entries', 'credit_openings', ['opening_id'], ['id'])
    op.create_foreign_key(op.f('fk_credit_ledger_entries_reservation_id_credit_reservations'), 'credit_ledger_entries', 'credit_reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(op.f('fk_credit_ledger_entries_retirement_id_credit_retirements'), 'credit_ledger_entries', 'credit_retirements', ['retirement_id'], ['id'])
    op.create_foreign_key(op.f('fk_credit_ledger_entries_reversal_id_credit_reversals'), 'credit_ledger_entries', 'credit_reversals', ['reversal_id'], ['id'])
    op.create_foreign_key(op.f('fk_credit_ledger_entries_transfer_id_credit_transfers'), 'credit_ledger_entries', 'credit_transfers', ['transfer_id'], ['id'])
    for seq in ("seq_credit_entry_code", "seq_credit_opening_code", "seq_credit_reservation_code", "seq_credit_transfer_code", "seq_credit_retirement_code",
                "seq_credit_reversal_code"):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents',
                               "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_credit_ledger_entries_guard ON dbo.credit_ledger_entries
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_ledger_entries is append-only: entries are never deleted.', 1;
    END;
    IF EXISTS (SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
               WHERE d.posted = 1 OR i.posted = 0 OR EXISTS (SELECT i.entry_code, i.entry_type, i.batch_id, i.organization_id, i.counterparty_organization_id, i.opening_id, i.reservation_id, i.transfer_id, i.retirement_id, i.reversal_id, i.issuance_id, i.quantity, i.actor_id, i.confirmed_by, i.reason, i.request_key, i.created_at, i.environment EXCEPT SELECT d.entry_code, d.entry_type, d.batch_id, d.organization_id, d.counterparty_organization_id, d.opening_id, d.reservation_id, d.transfer_id, d.retirement_id, d.reversal_id, d.issuance_id, d.quantity, d.actor_id, d.confirmed_by, d.reason, d.request_key, d.created_at, d.environment))
    BEGIN;
        THROW 51000, 'credit_ledger_entries is append-only: an entry is posted once and never changed.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN dbo.credit_batches b ON b.id = i.batch_id
        CROSS APPLY (SELECT COALESCE(SUM(quantity), 0) AS q FROM dbo.credit_positions WHERE consumed_by_entry_id = i.id) ins
        CROSS APPLY (SELECT COALESCE(SUM(quantity), 0) AS q FROM dbo.credit_positions WHERE created_by_entry_id = i.id) outs
        CROSS APPLY (SELECT COALESCE(SUM(quantity), 0) AS q FROM dbo.credit_positions WHERE batch_id = i.batch_id AND status = 'OPEN') opn
        WHERE NOT (
            (i.entry_type = 'OPEN_INVENTORY' AND ins.q = 0 AND outs.q = b.quantity AND b.status = 'ISSUED' AND opn.q = b.quantity)
            OR (i.entry_type = 'ISSUANCE_ADJUSTMENT' AND outs.q = 0 AND ins.q > 0 AND opn.q = 0)
            OR (i.entry_type NOT IN ('OPEN_INVENTORY', 'ISSUANCE_ADJUSTMENT') AND ins.q > 0 AND ins.q = outs.q AND opn.q = b.quantity)))
    BEGIN;
        THROW 51000, 'credit ledger conservation violated: inputs must equal outputs and open positions must equal the registry-issued batch quantity.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN dbo.credit_positions o ON o.created_by_entry_id = i.id
        JOIN dbo.credit_positions p1 ON p1.serial_range_id = o.serial_range_id AND p1.status = 'OPEN' AND p1.parsed_series IS NOT NULL
        JOIN dbo.credit_positions p2 ON p2.serial_range_id = p1.serial_range_id AND p2.status = 'OPEN' AND p2.parsed_series = p1.parsed_series
                                    AND p2.id <> p1.id
        WHERE p1.parsed_start <= p2.parsed_end AND p2.parsed_start <= p1.parsed_end)
    BEGIN;
        THROW 51000, 'credit ledger: parser-derived serial sub-ranges overlap.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_positions_guard ON dbo.credit_positions
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_positions: positions are never deleted.', 1;
    END;
    IF NOT EXISTS (SELECT 1 FROM deleted)
    BEGIN
        IF EXISTS (SELECT 1 FROM inserted i JOIN dbo.credit_ledger_entries e ON e.id = i.created_by_entry_id WHERE e.posted = 1)
           OR EXISTS (SELECT 1 FROM inserted WHERE status <> 'OPEN')
        BEGIN;
            THROW 51000, 'credit_positions: positions are created OPEN, only inside an unposted ledger entry.', 1;
        END;
        RETURN;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.batch_id, i.serial_range_id, i.owner_organization_id, i.holding_registry_account_id, i.holding_external_account_id, i.state, i.quantity, i.sub_start, i.sub_end, i.parsed_series, i.parsed_start, i.parsed_end, i.reservation_id, i.transfer_id, i.retirement_id, i.created_by_entry_id, i.created_at, i.environment EXCEPT SELECT d.batch_id, d.serial_range_id, d.owner_organization_id, d.holding_registry_account_id, d.holding_external_account_id, d.state, d.quantity, d.sub_start, d.sub_end, d.parsed_series, d.parsed_start, d.parsed_end, d.reservation_id, d.transfer_id, d.retirement_id, d.created_by_entry_id, d.created_at, d.environment)
           OR NOT (d.status = 'OPEN' AND i.status = 'CONSUMED' AND d.consumed_by_entry_id IS NULL AND i.consumed_by_entry_id IS NOT NULL)
           OR d.state = 'RETIRED')
    BEGIN;
        THROW 51000, 'credit_positions: positions are immutable — consumed exactly once; RETIRED positions are terminal.', 1;
    END;
    IF EXISTS (SELECT 1 FROM inserted i JOIN dbo.credit_ledger_entries e ON e.id = i.consumed_by_entry_id WHERE e.posted = 1)
    BEGIN;
        THROW 51000, 'credit_positions: a position is consumed only inside an unposted ledger entry.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_openings_immutable ON dbo.credit_openings
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_openings: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.opening_code, i.batch_id, i.owner_organization_id, i.holding_registry_account_id, i.requested_by, i.requested_at, i.request_key, i.environment EXCEPT SELECT d.opening_code, d.batch_id, d.owner_organization_id, d.holding_registry_account_id, d.requested_by, d.requested_at, d.request_key, d.environment)
           OR (d.status IN ('CONFIRMED', 'CANCELLED') AND EXISTS (SELECT i.opening_code, i.batch_id, i.owner_organization_id, i.holding_registry_account_id, i.requested_by, i.requested_at, i.request_key, i.environment, i.status, i.confirmed_by, i.confirmed_at, i.cancelled_by, i.cancelled_at, i.cancel_reason, i.entry_id EXCEPT SELECT d.opening_code, d.batch_id, d.owner_organization_id, d.holding_registry_account_id, d.requested_by, d.requested_at, d.request_key, d.environment, d.status, d.confirmed_by, d.confirmed_at, d.cancelled_by, d.cancelled_at, d.cancel_reason, d.entry_id)))
    BEGIN;
        THROW 51000, 'credit_openings: identity fixed; CONFIRMED / CANCELLED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_reservations_immutable ON dbo.credit_reservations
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_reservations: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.reservation_code, i.batch_id, i.serial_range_id, i.owner_organization_id, i.recipient_organization_id, i.purpose, i.purpose_reference, i.quantity, i.expires_at, i.created_by, i.created_at, i.request_key, i.environment EXCEPT SELECT d.reservation_code, d.batch_id, d.serial_range_id, d.owner_organization_id, d.recipient_organization_id, d.purpose, d.purpose_reference, d.quantity, d.expires_at, d.created_by, d.created_at, d.request_key, d.environment)
           OR (d.status IN ('CONSUMED', 'RELEASED', 'EXPIRED') AND EXISTS (SELECT i.reservation_code, i.batch_id, i.serial_range_id, i.owner_organization_id, i.recipient_organization_id, i.purpose, i.purpose_reference, i.quantity, i.expires_at, i.created_by, i.created_at, i.request_key, i.environment, i.status, i.released_by, i.released_at, i.release_reason, i.closed_at EXCEPT SELECT d.reservation_code, d.batch_id, d.serial_range_id, d.owner_organization_id, d.recipient_organization_id, d.purpose, d.purpose_reference, d.quantity, d.expires_at, d.created_by, d.created_at, d.request_key, d.environment, d.status, d.released_by, d.released_at, d.release_reason, d.closed_at)))
    BEGIN;
        THROW 51000, 'credit_reservations: identity fixed; closed reservations are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_transfers_immutable ON dbo.credit_transfers
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_transfers: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.transfer_code, i.kind, i.batch_id, i.serial_range_id, i.reservation_id, i.registry_organization_id, i.sender_organization_id, i.recipient_organization_id, i.recipient_external_account_id, i.quantity, i.purpose, i.purpose_reference, i.requested_by, i.requested_at, i.request_key, i.environment EXCEPT SELECT d.transfer_code, d.kind, d.batch_id, d.serial_range_id, d.reservation_id, d.registry_organization_id, d.sender_organization_id, d.recipient_organization_id, d.recipient_external_account_id, d.quantity, d.purpose, d.purpose_reference, d.requested_by, d.requested_at, d.request_key, d.environment)
           OR (d.status IN ('COMPLETED', 'CANCELLED', 'REJECTED') AND EXISTS (SELECT i.transfer_code, i.kind, i.batch_id, i.serial_range_id, i.reservation_id, i.registry_organization_id, i.sender_organization_id, i.recipient_organization_id, i.recipient_external_account_id, i.quantity, i.purpose, i.purpose_reference, i.requested_by, i.requested_at, i.request_key, i.environment, i.status, i.completed_by, i.completed_at, i.registry_transfer_reference, i.evidence_document_id, i.closed_by, i.closed_at, i.close_reason EXCEPT SELECT d.transfer_code, d.kind, d.batch_id, d.serial_range_id, d.reservation_id, d.registry_organization_id, d.sender_organization_id, d.recipient_organization_id, d.recipient_external_account_id, d.quantity, d.purpose, d.purpose_reference, d.requested_by, d.requested_at, d.request_key, d.environment, d.status, d.completed_by, d.completed_at, d.registry_transfer_reference, d.evidence_document_id, d.closed_by, d.closed_at, d.close_reason)))
    BEGIN;
        THROW 51000, 'credit_transfers: identity fixed; closed transfers are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_retirements_immutable ON dbo.credit_retirements
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_retirements: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.retirement_code, i.batch_id, i.serial_range_id, i.reservation_id, i.registry_organization_id, i.owner_organization_id, i.quantity, i.beneficiary, i.reason, i.requested_by, i.requested_at, i.request_key, i.environment EXCEPT SELECT d.retirement_code, d.batch_id, d.serial_range_id, d.reservation_id, d.registry_organization_id, d.owner_organization_id, d.quantity, d.beneficiary, d.reason, d.requested_by, d.requested_at, d.request_key, d.environment)
           OR (d.status IN ('RETIRED', 'REJECTED', 'CANCELLED') AND EXISTS (SELECT i.retirement_code, i.batch_id, i.serial_range_id, i.reservation_id, i.registry_organization_id, i.owner_organization_id, i.quantity, i.beneficiary, i.reason, i.requested_by, i.requested_at, i.request_key, i.environment, i.status, i.retired_by, i.retired_at, i.registry_retirement_reference, i.retirement_date, i.certificate_document_id, i.retired_serials, i.closed_by, i.closed_at, i.close_reason EXCEPT SELECT d.retirement_code, d.batch_id, d.serial_range_id, d.reservation_id, d.registry_organization_id, d.owner_organization_id, d.quantity, d.beneficiary, d.reason, d.requested_by, d.requested_at, d.request_key, d.environment, d.status, d.retired_by, d.retired_at, d.registry_retirement_reference, d.retirement_date, d.certificate_document_id, d.retired_serials, d.closed_by, d.closed_at, d.close_reason)))
    BEGIN;
        THROW 51000, 'credit_retirements: identity fixed; RETIRED (permanent), REJECTED and CANCELLED are final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_credit_reversals_immutable ON dbo.credit_reversals
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'credit_reversals: records are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.reversal_code, i.reversed_entry_id, i.batch_id, i.reason, i.requested_by, i.requested_at, i.request_key, i.environment EXCEPT SELECT d.reversal_code, d.reversed_entry_id, d.batch_id, d.reason, d.requested_by, d.requested_at, d.request_key, d.environment)
           OR (d.status IN ('APPLIED', 'REJECTED') AND EXISTS (SELECT i.reversal_code, i.reversed_entry_id, i.batch_id, i.reason, i.requested_by, i.requested_at, i.request_key, i.environment, i.status, i.decided_by, i.decided_at, i.decision_note, i.entry_id EXCEPT SELECT d.reversal_code, d.reversed_entry_id, d.batch_id, d.reason, d.requested_by, d.requested_at, d.request_key, d.environment, d.status, d.decided_by, d.decided_at, d.decision_note, d.entry_id)))
    BEGIN;
        THROW 51000, 'credit_reversals: identity fixed; decided reversals are final.', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: Phase 9B history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.credit_ledger_entries) OR EXISTS (SELECT 1 FROM dbo.credit_positions) OR EXISTS (SELECT 1 FROM dbo.credit_openings)
   OR EXISTS (SELECT 1 FROM dbo.credit_reservations) OR EXISTS (SELECT 1 FROM dbo.credit_transfers) OR EXISTS (SELECT 1 FROM dbo.credit_retirements)
   OR EXISTS (SELECT 1 FROM dbo.credit_reversals)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category IN ('RETIREMENT_CERTIFICATE', 'REGISTRY_TRANSFER_EVIDENCE'))
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 9B credit ledger entries, positions, openings, reservations, transfers, retirements, reversals or ledger documents exist.', 1;
END""")
    for trigger in ('trg_credit_reversals_immutable', 'trg_credit_retirements_immutable', 'trg_credit_transfers_immutable', 'trg_credit_reservations_immutable', 'trg_credit_openings_immutable', 'trg_credit_positions_guard', 'trg_credit_ledger_entries_guard'):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'VERIFICATION_REPORT', 'VERIFICATION_EVIDENCE', 'REGISTRY_SUBMISSION', 'REGISTRY_RESPONSE', 'ISSUANCE_STATEMENT', 'OTHER')")
    for seq in ("seq_credit_entry_code", "seq_credit_opening_code", "seq_credit_reservation_code", "seq_credit_transfer_code", "seq_credit_retirement_code",
                "seq_credit_reversal_code"):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    op.drop_constraint(op.f('fk_credit_ledger_entries_opening_id_credit_openings'), 'credit_ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_credit_ledger_entries_reservation_id_credit_reservations'), 'credit_ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_credit_ledger_entries_retirement_id_credit_retirements'), 'credit_ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_credit_ledger_entries_reversal_id_credit_reversals'), 'credit_ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_credit_ledger_entries_transfer_id_credit_transfers'), 'credit_ledger_entries', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_positions_owner_organization_id'), table_name='credit_positions')
    op.drop_index('ix_credit_positions_open', table_name='credit_positions', mssql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_credit_positions_created_by', table_name='credit_positions')
    op.drop_index('ix_credit_positions_consumed_by', table_name='credit_positions')
    op.drop_table('credit_positions')
    op.drop_index('uq_credit_transfers_request_key', table_name='credit_transfers', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_credit_transfers_registry_ref', table_name='credit_transfers', mssql_where=sa.text('registry_transfer_reference IS NOT NULL'))
    op.drop_index(op.f('ix_credit_transfers_sender_organization_id'), table_name='credit_transfers')
    op.drop_index(op.f('ix_credit_transfers_recipient_organization_id'), table_name='credit_transfers')
    op.drop_table('credit_transfers')
    op.drop_index('uq_credit_retirements_request_key', table_name='credit_retirements', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_credit_retirements_registry_ref', table_name='credit_retirements', mssql_where=sa.text('registry_retirement_reference IS NOT NULL'))
    op.drop_index(op.f('ix_credit_retirements_owner_organization_id'), table_name='credit_retirements')
    op.drop_table('credit_retirements')
    op.drop_index('uq_credit_reversals_request_key', table_name='credit_reversals', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_credit_reversals_open', table_name='credit_reversals', mssql_where=sa.text("status IN ('REQUESTED', 'APPLIED')"))
    op.drop_table('credit_reversals')
    op.drop_index('uq_credit_reservations_request_key', table_name='credit_reservations', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index(op.f('ix_credit_reservations_owner_organization_id'), table_name='credit_reservations')
    op.drop_index('ix_credit_reservations_active', table_name='credit_reservations', mssql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('credit_reservations')
    op.drop_index('uq_credit_openings_request_key', table_name='credit_openings', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('uq_credit_openings_batch', table_name='credit_openings', mssql_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"))
    op.drop_table('credit_openings')
    op.drop_index('uq_credit_ledger_entries_request_key', table_name='credit_ledger_entries', mssql_where=sa.text('request_key IS NOT NULL'))
    op.drop_index('ix_credit_ledger_entries_batch', table_name='credit_ledger_entries')
    op.drop_table('credit_ledger_entries')
    # ### end Alembic commands ###
