"""Phase 8A — internal pre-verification (not VVB / ACVA).

4 tables (calculation findings + append-only finding events, calculation reports, calculation readiness reviews), sequences
CFND / CRPT / RDY, filtered unique indexes (one CURRENT report per run; one open and one READY readiness per monitoring period),
the documents category CALCULATION_REPORT (removed on downgrade only when unused) and immutability triggers: finding events
append-only; a finding's identity, target and original text never change; reports immutable except CURRENT -> SUPERSEDED; readiness
identity fixed, decisions and manifests frozen, READY -> INVALIDATED only; nothing is deleted. No Phase 1–7 data is changed or backfilled.

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-03 12:44:04.176172
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_findings',
    sa.Column('finding_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Unicode(length=20), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('description', sa.Unicode(length=4000), nullable=False),
    sa.Column('target_input_seq', sa.Integer(), nullable=True),
    sa.Column('target_output_seq', sa.Integer(), nullable=True),
    sa.Column('target_calculation_rule_id', sa.Uuid(), nullable=True),
    sa.Column('target_source_type', sa.Unicode(length=30), nullable=True),
    sa.Column('target_source_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('raised_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('response_text', sa.Unicode(length=4000), nullable=True),
    sa.Column('response_document_id', sa.Uuid(), nullable=True),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('responded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('resolution_note', sa.Unicode(length=2000), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', mssql.DATETIME2(), nullable=True),
    sa.Column('resolved_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_by', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', mssql.DATETIME2(), nullable=True),
    sa.Column('withdraw_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('OBSERVATION', 'NON_CONFORMITY', 'CLARIFICATION', 'MISSING_EVIDENCE', 'CALCULATION_ISSUE', 'METHODOLOGY_ISSUE')", name=op.f('ck_calculation_findings_category')),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_calculation_findings_environment')),
    sa.CheckConstraint("status <> 'WITHDRAWN' OR withdraw_reason IS NOT NULL", name=op.f('ck_calculation_findings_withdraw_reason')),
    sa.CheckConstraint("status IN ('OPEN', 'RESPONDED', 'RESOLVED', 'WITHDRAWN')", name=op.f('ck_calculation_findings_status')),
    sa.CheckConstraint("target_source_type IS NULL OR target_source_type IN ('LAB_RESULT', 'MONITORING_RECORD', 'STRATUM_AREA', 'SAMPLING_DESIGN_PARAMETER', 'MODULE_CONSTANT')", name=op.f('ck_calculation_findings_target_source_type')),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_calculation_findings_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_calculation_findings_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calculation_findings_project_id_projects')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_calculation_findings_raised_by_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_calculation_findings_resolved_by_users')),
    sa.ForeignKeyConstraint(['resolved_by_run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_findings_resolved_by_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_calculation_findings_responded_by_users')),
    sa.ForeignKeyConstraint(['response_document_id'], ['documents.id'], name=op.f('fk_calculation_findings_response_document_id_documents')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_findings_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['target_calculation_rule_id'], ['methodology_calculation_rules.id'], name=op.f('fk_calculation_findings_target_calculation_rule_id_methodology_calculation_rules')),
    sa.ForeignKeyConstraint(['withdrawn_by'], ['users.id'], name=op.f('fk_calculation_findings_withdrawn_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_findings')),
    sa.UniqueConstraint('finding_code', name=op.f('uq_calculation_findings_finding_code'))
    )
    op.create_index('ix_calculation_findings_period_status', 'calculation_findings', ['monitoring_period_id', 'status'], unique=False)
    op.create_index('ix_calculation_findings_project_status', 'calculation_findings', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_calculation_findings_run_id'), 'calculation_findings', ['run_id'], unique=False)
    op.create_table('calculation_reports',
    sa.Column('report_code', sa.Unicode(length=20), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generator_version', sa.Unicode(length=40), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.Column('content_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('pdf_sha256', sa.Unicode(length=64), nullable=False),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('superseded_by_report_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', mssql.DATETIME2(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('generated_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_calculation_reports_environment')),
    sa.CheckConstraint("status IN ('CURRENT', 'SUPERSEDED')", name=op.f('ck_calculation_reports_status')),
    sa.CheckConstraint('ISJSON(content) = 1', name=op.f('ck_calculation_reports_content_json')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_calculation_reports_document_id_documents')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_calculation_reports_generated_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_calculation_reports_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calculation_reports_project_id_projects')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_reports_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['superseded_by_report_id'], ['calculation_reports.id'], name=op.f('fk_calculation_reports_superseded_by_report_id_calculation_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_reports')),
    sa.UniqueConstraint('report_code', name=op.f('uq_calculation_reports_report_code')),
    sa.UniqueConstraint('run_id', 'version', name=op.f('uq_calculation_reports_run_id_version'))
    )
    op.create_index('uq_calculation_reports_current', 'calculation_reports', ['run_id'], unique=True, mssql_where=sa.text("status = 'CURRENT'"))
    op.create_table('calculation_finding_events',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.Unicode(length=20), nullable=False),
    sa.Column('from_status', sa.Unicode(length=12), nullable=True),
    sa.Column('to_status', sa.Unicode(length=12), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('note', sa.Unicode(length=4000), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_calculation_finding_events_actor_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_calculation_finding_events_document_id_documents')),
    sa.ForeignKeyConstraint(['finding_id'], ['calculation_findings.id'], name=op.f('fk_calculation_finding_events_finding_id_calculation_findings')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_finding_events_run_id_calculation_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_finding_events')),
    sa.UniqueConstraint('finding_id', 'seq', name=op.f('uq_calculation_finding_events_finding_id_seq'))
    )
    op.create_index(op.f('ix_calculation_finding_events_finding_id'), 'calculation_finding_events', ['finding_id'], unique=False)
    op.create_table('calculation_readiness_reviews',
    sa.Column('readiness_code', sa.Unicode(length=20), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('monitoring_period_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Unicode(length=12), nullable=False),
    sa.Column('checks', sa.UnicodeText(), nullable=True),
    sa.Column('manifest', sa.UnicodeText(), nullable=True),
    sa.Column('manifest_sha256', sa.Unicode(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('SYSUTCDATETIME()'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', mssql.DATETIME2(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', mssql.DATETIME2(), nullable=True),
    sa.Column('decision_notes', sa.Unicode(length=2000), nullable=True),
    sa.Column('withdrawn_by', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', mssql.DATETIME2(), nullable=True),
    sa.Column('withdraw_reason', sa.Unicode(length=1000), nullable=True),
    sa.Column('invalidated_at', mssql.DATETIME2(), nullable=True),
    sa.Column('invalidation_reason', sa.Unicode(length=2000), nullable=True),
    sa.Column('environment', sa.Unicode(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("environment IN ('LIVE', 'DEMO')", name=op.f('ck_calculation_readiness_reviews_environment')),
    sa.CheckConstraint("status <> 'INVALIDATED' OR invalidation_reason IS NOT NULL", name=op.f('ck_calculation_readiness_reviews_invalidation_reason')),
    sa.CheckConstraint("status <> 'READY' OR (manifest IS NOT NULL AND manifest_sha256 IS NOT NULL)", name=op.f('ck_calculation_readiness_reviews_ready_manifest')),
    sa.CheckConstraint("status <> 'WITHDRAWN' OR withdraw_reason IS NOT NULL", name=op.f('ck_calculation_readiness_reviews_withdraw_reason')),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'READY', 'REJECTED', 'WITHDRAWN', 'INVALIDATED')", name=op.f('ck_calculation_readiness_reviews_status')),
    sa.CheckConstraint('checks IS NULL OR ISJSON(checks) = 1', name=op.f('ck_calculation_readiness_reviews_checks_json')),
    sa.CheckConstraint('manifest IS NULL OR ISJSON(manifest) = 1', name=op.f('ck_calculation_readiness_reviews_manifest_json')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calculation_readiness_reviews_created_by_users')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_calculation_readiness_reviews_decided_by_users')),
    sa.ForeignKeyConstraint(['monitoring_period_id'], ['monitoring_periods.id'], name=op.f('fk_calculation_readiness_reviews_monitoring_period_id_monitoring_periods')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calculation_readiness_reviews_project_id_projects')),
    sa.ForeignKeyConstraint(['report_id'], ['calculation_reports.id'], name=op.f('fk_calculation_readiness_reviews_report_id_calculation_reports')),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], name=op.f('fk_calculation_readiness_reviews_run_id_calculation_runs')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_calculation_readiness_reviews_submitted_by_users')),
    sa.ForeignKeyConstraint(['withdrawn_by'], ['users.id'], name=op.f('fk_calculation_readiness_reviews_withdrawn_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_readiness_reviews')),
    sa.UniqueConstraint('readiness_code', name=op.f('uq_calculation_readiness_reviews_readiness_code'))
    )
    op.create_index(op.f('ix_calculation_readiness_reviews_project_id'), 'calculation_readiness_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_calculation_readiness_reviews_run_id'), 'calculation_readiness_reviews', ['run_id'], unique=False)
    op.create_index('uq_calculation_readiness_open', 'calculation_readiness_reviews', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status IN ('DRAFT', 'SUBMITTED')"))
    op.create_index('uq_calculation_readiness_ready', 'calculation_readiness_reviews', ['monitoring_period_id'], unique=True, mssql_where=sa.text("status = 'READY'"))
    # ### end Alembic commands ###

    # ---- hand-written: sequences, documents category, immutability triggers
    for seq in ("seq_calculation_finding_code", "seq_calculation_report_code", "seq_calculation_readiness_code"):
        op.execute(f"CREATE SEQUENCE dbo.{seq} AS bigint START WITH 1 INCREMENT BY 1 NO CACHE")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'CALCULATION_REPORT', 'OTHER')")
    op.execute("""
CREATE TRIGGER trg_calculation_finding_events_append_only ON dbo.calculation_finding_events
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51000, 'calculation_finding_events is append-only: updates and deletes are not permitted.', 1;
END""")
    op.execute("""
CREATE TRIGGER trg_calculation_findings_immutable ON dbo.calculation_findings
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'calculation_findings: findings are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.finding_code, i.project_id, i.monitoring_period_id, i.run_id, i.category, i.blocking, i.title, i.description, i.target_input_seq, i.target_output_seq, i.target_calculation_rule_id, i.target_source_type, i.target_source_id, i.evidence_document_id, i.raised_by, i.raised_at, i.environment EXCEPT SELECT d.finding_code, d.project_id, d.monitoring_period_id, d.run_id, d.category, d.blocking, d.title, d.description, d.target_input_seq, d.target_output_seq, d.target_calculation_rule_id, d.target_source_type, d.target_source_id, d.evidence_document_id, d.raised_by, d.raised_at, d.environment)
           OR (d.status = 'WITHDRAWN' AND EXISTS (SELECT i.finding_code, i.project_id, i.monitoring_period_id, i.run_id, i.category, i.blocking, i.title, i.description, i.target_input_seq, i.target_output_seq, i.target_calculation_rule_id, i.target_source_type, i.target_source_id, i.evidence_document_id, i.raised_by, i.raised_at, i.environment, i.status, i.response_text, i.response_document_id, i.responded_by, i.responded_at, i.resolution_note, i.resolved_by, i.resolved_at, i.resolved_by_run_id, i.withdrawn_by, i.withdrawn_at, i.withdraw_reason EXCEPT SELECT d.finding_code, d.project_id, d.monitoring_period_id, d.run_id, d.category, d.blocking, d.title, d.description, d.target_input_seq, d.target_output_seq, d.target_calculation_rule_id, d.target_source_type, d.target_source_id, d.evidence_document_id, d.raised_by, d.raised_at, d.environment, d.status, d.response_text, d.response_document_id, d.responded_by, d.responded_at, d.resolution_note, d.resolved_by, d.resolved_at, d.resolved_by_run_id, d.withdrawn_by, d.withdrawn_at, d.withdraw_reason)))
    BEGIN;
        THROW 51000, 'calculation_findings: identity, target and original text are immutable; a withdrawn finding is final.', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_calculation_reports_immutable ON dbo.calculation_reports
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'calculation_reports: reports are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.report_code, i.run_id, i.project_id, i.monitoring_period_id, i.version, i.generator_version, i.content, i.content_sha256, i.document_id, i.pdf_sha256, i.generated_by, i.generated_at, i.environment EXCEPT SELECT d.report_code, d.run_id, d.project_id, d.monitoring_period_id, d.version, d.generator_version, d.content, d.content_sha256, d.document_id, d.pdf_sha256, d.generated_by, d.generated_at, d.environment)
           OR (d.status = 'SUPERSEDED' AND i.status <> 'SUPERSEDED')
           OR (d.superseded_by_report_id IS NOT NULL AND (i.superseded_by_report_id IS NULL OR i.superseded_by_report_id <> d.superseded_by_report_id))
           OR (d.superseded_at IS NOT NULL AND (i.superseded_at IS NULL OR i.superseded_at <> d.superseded_at)))
    BEGIN;
        THROW 51000, 'calculation_reports: a report is immutable (only CURRENT -> SUPERSEDED).', 1;
    END;
END""")
    op.execute("""
CREATE TRIGGER trg_calculation_readiness_reviews_immutable ON dbo.calculation_readiness_reviews
AFTER UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM deleted) AND NOT EXISTS (SELECT 1 FROM inserted)
    BEGIN;
        THROW 51000, 'calculation_readiness_reviews: readiness reviews are never deleted.', 1;
    END;
    IF EXISTS (
        SELECT 1 FROM inserted i JOIN deleted d ON d.id = i.id
        WHERE EXISTS (SELECT i.readiness_code, i.project_id, i.monitoring_period_id, i.run_id, i.created_by, i.created_at, i.environment EXCEPT SELECT d.readiness_code, d.project_id, d.monitoring_period_id, d.run_id, d.created_by, d.created_at, d.environment)
           OR (d.status IN ('REJECTED', 'WITHDRAWN', 'INVALIDATED') AND EXISTS (SELECT i.status, i.report_id, i.checks, i.manifest, i.manifest_sha256, i.submitted_by, i.submitted_at, i.decided_by, i.decided_at, i.decision_notes, i.withdrawn_by, i.withdrawn_at, i.withdraw_reason, i.invalidated_at, i.invalidation_reason EXCEPT SELECT d.status, d.report_id, d.checks, d.manifest, d.manifest_sha256, d.submitted_by, d.submitted_at, d.decided_by, d.decided_at, d.decision_notes, d.withdrawn_by, d.withdrawn_at, d.withdraw_reason, d.invalidated_at, d.invalidation_reason))
           OR (d.status = 'READY' AND (i.status NOT IN ('READY', 'INVALIDATED') OR EXISTS (SELECT i.report_id, i.checks, i.manifest, i.manifest_sha256, i.submitted_by, i.submitted_at, i.decided_by, i.decided_at, i.decision_notes, i.withdrawn_by, i.withdrawn_at, i.withdraw_reason EXCEPT SELECT d.report_id, d.checks, d.manifest, d.manifest_sha256, d.submitted_by, d.submitted_at, d.decided_by, d.decided_at, d.decision_notes, d.withdrawn_by, d.withdrawn_at, d.withdraw_reason))))
    BEGIN;
        THROW 51000, 'calculation_readiness_reviews: a decided readiness is immutable (only READY -> INVALIDATED).', 1;
    END;
END""")


def downgrade() -> None:
    # ---- hand-written: Phase 8A history is never dropped silently
    op.execute("""
IF EXISTS (SELECT 1 FROM dbo.calculation_findings) OR EXISTS (SELECT 1 FROM dbo.calculation_finding_events)
   OR EXISTS (SELECT 1 FROM dbo.calculation_reports) OR EXISTS (SELECT 1 FROM dbo.calculation_readiness_reviews)
   OR EXISTS (SELECT 1 FROM dbo.documents WHERE category = 'CALCULATION_REPORT')
BEGIN;
    THROW 51000, 'Downgrade refused: Phase 8A findings, reports, readiness reviews or CALCULATION_REPORT documents exist.', 1;
END""")
    for trigger in ("trg_calculation_readiness_reviews_immutable", "trg_calculation_reports_immutable", "trg_calculation_findings_immutable",
                    "trg_calculation_finding_events_append_only"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.drop_constraint(op.f('ck_documents_category'), 'documents', type_='check')
    op.create_check_constraint(op.f('ck_documents_category'), 'documents', "category IN ('KYC_ID', 'LAND_TITLE', 'LEASE_AGREEMENT', 'LAND_RECORD', 'CONSENT_FORM', 'AGREEMENT', 'BANK_PROOF', 'FIELD_PHOTO', 'INPUT_RECORD', 'GEOSPATIAL_FILE', 'PROJECT_DESIGN', 'CARBON_RIGHTS', 'BASELINE_DATA', 'METHODOLOGY_DOCUMENT', 'LAB_REPORT', 'CUSTODY_DOCUMENT', 'OTHER')")
    for seq in ("seq_calculation_finding_code", "seq_calculation_report_code", "seq_calculation_readiness_code"):
        op.execute(f"DROP SEQUENCE IF EXISTS dbo.{seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_calculation_readiness_ready', table_name='calculation_readiness_reviews', mssql_where=sa.text("status = 'READY'"))
    op.drop_index('uq_calculation_readiness_open', table_name='calculation_readiness_reviews', mssql_where=sa.text("status IN ('DRAFT', 'SUBMITTED')"))
    op.drop_index(op.f('ix_calculation_readiness_reviews_run_id'), table_name='calculation_readiness_reviews')
    op.drop_index(op.f('ix_calculation_readiness_reviews_project_id'), table_name='calculation_readiness_reviews')
    op.drop_table('calculation_readiness_reviews')
    op.drop_index(op.f('ix_calculation_finding_events_finding_id'), table_name='calculation_finding_events')
    op.drop_table('calculation_finding_events')
    op.drop_index('uq_calculation_reports_current', table_name='calculation_reports', mssql_where=sa.text("status = 'CURRENT'"))
    op.drop_table('calculation_reports')
    op.drop_index(op.f('ix_calculation_findings_run_id'), table_name='calculation_findings')
    op.drop_index('ix_calculation_findings_project_status', table_name='calculation_findings')
    op.drop_index('ix_calculation_findings_period_status', table_name='calculation_findings')
    op.drop_table('calculation_findings')
    # ### end Alembic commands ###
