/** Permission codes — must match backend app/security/permissions.py (class P). */
export const P = {
  USERS_READ: 'users.read',
  USERS_MANAGE: 'users.manage',
  USERS_ASSIGN_ROLES: 'users.assign_roles',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  ORGANIZATIONS_READ: 'organizations.read',
  ORGANIZATIONS_MANAGE: 'organizations.manage',
  ORGANIZATIONS_MANAGE_MEMBERS: 'organizations.manage_members',
  AUDIT_READ: 'audit.read',
  SECURITY_READ: 'security.read',
  SECURITY_MANAGE: 'security.manage',
  FARMERS_READ: 'farmers.read',
  FARMERS_MANAGE: 'farmers.manage',
  FARMERS_KYC_VERIFY: 'farmers.kyc_verify',
  FARMERS_BANK_MANAGE: 'farmers.bank_manage',
  FARMERS_BANK_VERIFY: 'farmers.bank_verify',
  FARMERS_SELF: 'farmers.self',
  FARMS_READ: 'farms.read',
  FARMS_MANAGE: 'farms.manage',
  FARMS_REVIEW: 'farms.review',
  FARMS_REVIEW_CROSS_ORG: 'farms.review_cross_org',
  CONSENTS_CONFIGURE: 'consents.configure',
  PROJECTS_READ: 'projects.read',
  PROJECTS_MANAGE: 'projects.manage',
  PROJECTS_REVIEW: 'projects.review',
  STANDARDS_MANAGE: 'standards.manage',
} as const;

export type PermissionCode = (typeof P)[keyof typeof P];
